insert into public.benchmark_cases (
  slug, input, context, expected_concepts, forbidden_interpretations,
  expected_interaction_mode, expected_assumptions, forbidden_questions, notes, active
) values
('magia-foto', 'Haz magia con esta foto.', 'edición fotográfica', '["mejora extraordinaria","preservar identidad"]', '["efectos sobrenaturales"]', 'EXECUTE', '["ajustes fotográficos naturales"]', '["seed","sampler","CFG"]', null, true),
('magia-balon', 'Hizo magia con el balón.', 'fútbol', '["habilidad","creatividad","control"]', '["magia sobrenatural"]', 'ASSUME', '["elogio figurado"]', '["seed","sampler","CFG"]', null, true),
('magia-manos', 'Pon magia saliendo de sus manos.', 'ilustración fantástica', '["magia"]', '[]', 'ASSUME', '[]', '["seed","sampler","CFG"]', 'En fantasía, la lectura literal sí puede ser correcta.', true),
('pesado-personaje', 'Hazlo más pesado.', 'personaje de videojuego', '["masa","presencia"]', '["peso físico del archivo"]', 'SHOW_OPTIONS', '["silueta"]', '["seed","sampler","CFG"]', null, true),
('pesado-diseno', 'Hazlo más pesado.', 'diseño de póster', '["peso visual","impacto"]', '["peso físico"]', 'SHOW_OPTIONS', '["contraste"]', '["seed","sampler","CFG"]', null, true),
('pesado-musica', 'Hazlo más pesado.', 'mezcla musical', '["cuerpo","pegada"]', '["peso físico"]', 'SHOW_OPTIONS', '["graves"]', '["seed","sampler","CFG"]', null, true),
('demasiado-ia', 'Se ve demasiado IA.', 'retrato fotográfico', '["natural","artefactos de IA"]', '[]', 'EXECUTE', '["piel","manos"]', '["seed","sampler","CFG"]', null, true),
('bonito-pero-no', 'Está bonito pero como que no.', 'branding', '["rechazo","diagnóstico"]', '[]', 'EXPLORE', '[]', '["seed","sampler","CFG"]', null, true),
('mas-limpio-poster', 'Más limpio.', 'diseño de póster', '["menos ruido","jerarquía"]', '[]', 'EXECUTE', '[]', '["seed","sampler","CFG"]', null, true),
('mas-limpio-codigo', 'Más limpio.', 'código TypeScript', '["simplificar"]', '[]', 'EXECUTE', '[]', '["seed","sampler","CFG"]', null, true),
('dejalo-igual-contexto', 'Déjalo igual, nomás arregla eso.', 'La mano derecha tiene seis dedos.', '["edición estrictamente local","preservar todo"]', '[]', 'EXECUTE', '["área indicada"]', '["qué quieres preservar","seed","CFG"]', null, true),
('dejalo-igual-sin-referencia', 'Déjalo igual, nomás arregla eso.', null, '["referencia","antecedente"]', '[]', 'ASK', '[]', '["seed","sampler","CFG"]', 'Sin estado, eso es bloqueante.', true),
('cara-otra-vez', 'Otra vez me cambiaste la cara.', 'edición de retrato', '["frustrada","rostro original","identidad"]', '[]', 'EXECUTE', '["rostro original"]', '["cómo quieres la cara","seed","sampler"]', null, true),
('mas-pro-branding', 'Hazlo más pro.', 'branding para una cafetería', '["jerarquía","acabado","credibilidad"]', '[]', 'EXECUTE', '[]', '["seed","sampler","CFG"]', null, true),
('mas-pro-codigo', 'Hazlo más pro.', 'aplicación web', '["profesional","coherente"]', '[]', 'EXECUTE', '[]', '["seed","sampler","CFG"]', null, true),
('no-exagerado', 'No tan exagerado.', 'efecto visual', '["reducir","mantener la dirección"]', '[]', 'EXECUTE', '[]', '["seed","sampler","CFG"]', null, true),
('caro-no-mamador', 'Que se vea caro pero no mamador.', 'branding de restaurante', '["premium sobria","sin ostentación"]', '["lujo exagerado"]', 'EXECUTE', '["calidad material"]', '["seed","sampler","CFG"]', null, true),
('falta-vida-poster', 'Le falta vida.', 'póster cultural', '["vitalidad","energía"]', '[]', 'SHOW_OPTIONS', '[]', '["seed","sampler","CFG"]', null, true),
('falta-vida-musica', 'Le falta vida.', 'mezcla musical', '["energía"]', '[]', 'SHOW_OPTIONS', '[]', '["seed","sampler","CFG"]', null, true),
('tieso-personaje', 'Está muy tieso.', 'pose de personaje', '["natural","dinámico"]', '[]', 'EXECUTE', '[]', '["seed","sampler","CFG"]', null, true),
('tieso-texto', 'Está muy tieso.', 'texto para redes sociales', '["fluidez"]', '[]', 'EXECUTE', '[]', '["seed","sampler","CFG"]', null, true),
('raro-foto', 'No sé qué tiene pero está raro.', 'fotografía de producto', '["diagnosticar","causas probables"]', '[]', 'EXPLORE', '[]', '["seed","sampler","CFG"]', null, true),
('raro-ui', 'No sé qué tiene pero está raro.', 'interfaz web', '["diagnosticar","jerarquía"]', '[]', 'EXPLORE', '[]', '["seed","sampler","CFG"]', null, true),
('medio-equis', 'Está medio equis.', 'logo', '["cambio contextual"]', '[]', 'ASSUME', '[]', '["seed","sampler","CFG"]', 'Caso abierto para revisión manual.', true),
('bonito-no', 'Está bonito, pero no se siente mío.', 'identidad de marca', '["cambio contextual"]', '[]', 'ASSUME', '[]', '["seed","sampler","CFG"]', null, true),
('camiseta-negra', 'Haz la camiseta negra.', 'edición fotográfica', '["cambio contextual"]', '["cambiar el rostro","regenerar fondo"]', 'ASSUME', '["moderada"]', '["seed","sampler","CFG"]', null, true),
('solo-fondo', 'Solo quita lo del fondo.', 'edición fotográfica', '["cambio contextual"]', '["cambiar la cara","cambiar el cuerpo"]', 'ASSUME', '[]', '["seed","sampler","CFG"]', null, true),
('mas-calido', 'Un poquito más cálido.', 'fotografía', '["cambio contextual"]', '[]', 'ASSUME', '["moderada"]', '["seed","sampler","CFG"]', null, true),
('que-pegue', 'Quiero que pegue más.', 'mezcla musical', '["cambio contextual"]', '["golpear físicamente"]', 'ASSUME', '[]', '["seed","sampler","CFG"]', null, true),
('sin-perder-esencia', 'Modernízalo sin perder su esencia.', 'logo histórico', '["cambio contextual"]', '["reemplazar completamente"]', 'ASSUME', '[]', '["seed","sampler","CFG"]', null, true),
('menos-corporativo', 'Menos corporativo, más humano.', 'copy de landing page', '["cambio contextual"]', '[]', 'ASSUME', '[]', '["seed","sampler","CFG"]', null, true),
('haz-magia-bug', 'Haz magia, esto sigue tronando.', 'aplicación web con error al guardar', '["cambio contextual"]', '["magia sobrenatural"]', 'ASSUME', '[]', '["qué lenguaje usas si ya está en el contexto","seed"]', null, true)
on conflict (slug) do update set
  input = excluded.input,
  context = excluded.context,
  expected_concepts = excluded.expected_concepts,
  forbidden_interpretations = excluded.forbidden_interpretations,
  expected_interaction_mode = excluded.expected_interaction_mode,
  expected_assumptions = excluded.expected_assumptions,
  forbidden_questions = excluded.forbidden_questions,
  notes = excluded.notes,
  active = excluded.active;
