import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";

import type { FieldBetaRepository, FieldPolicyRecord } from "@/src/application/ports/outcome/field-beta-repository";
import { FieldFailureTagSchema, PreservationStrategyIdSchema, PreservationStrategyParametersSchema, StrategyRoleSchema, type FieldEvaluationJudgment, type FieldEvaluationSample, type FieldFeedback, type FieldGoldenCase, type FieldOutcome, type FieldRegressionCandidate, type FieldStrategyRun } from "@/src/domain/outcome/media/field-beta";
import { PreservationEvidenceMetricsSchema } from "@/src/domain/outcome/media/preservation";
import { StudyTaskTypeSchema, StudyTopologySchema } from "@/src/domain/outcome/media/preservation-study";
import { OutcomeBlueprintSchema, verifyOutcomeBlueprintHash } from "@/src/domain/outcome/specification/outcome-blueprint";
import { TaskSpecSchema, verifyTaskSpecHash } from "@/src/domain/outcome/specification/task-spec";

export class SupabaseFieldBetaRepository implements FieldBetaRepository {
  constructor(private readonly client: SupabaseClient, private readonly tenantId = "internal-lab") {}

  async findPolicy(policyVersion: string) { const { data, error } = await this.client.from("preservation_policy_versions").select("*").eq("tenant_id", this.tenantId).eq("policy_version", policyVersion).maybeSingle(); fail(error, "leer policy"); return data ? policyRow(data) : null; }
  async createPolicy(input: Omit<FieldPolicyRecord, "createdAt">) { const { data, error } = await this.client.from("preservation_policy_versions").insert({ tenant_id: this.tenantId, policy_version: input.policyVersion, status: input.status, definition: input.definition }).select("*").single(); fail(error, "crear policy"); return policyRow(data); }
  async createStrategyRun(input: Omit<FieldStrategyRun, "id" | "createdAt">) { this.assertTenant(input.tenantId); const { data, error } = await this.client.from("preservation_strategy_runs").insert({ tenant_id: this.tenantId, transaction_id: input.transactionId, execution_run_id: input.executionRunId, raw_candidate_id: input.rawCandidateId, candidate_id: input.candidateId, policy_version: input.policyVersion, outcome_sku: input.outcomeSku, blueprint_id: input.blueprintId, blueprint_version: input.blueprintVersion, blueprint_hash: input.blueprintHash, task_spec_id: input.taskSpecId, task_spec_version: input.taskSpecVersion, task_spec_hash: input.taskSpecHash, spec_compiler_version: input.specCompilerVersion, strategy_id: input.strategyId, parameters: input.parameters, candidate_role: input.role, machine_metrics: input.machineMetrics, preservation_latency_ms: input.preservationLatencyMs }).select("*").single(); fail(error, "crear strategy run"); return strategyRow(data); }
  async listStrategyRuns(transactionId: string) { const { data, error } = await this.client.from("preservation_strategy_runs").select("*").eq("tenant_id", this.tenantId).eq("transaction_id", transactionId).order("created_at"); fail(error, "leer strategy runs"); return (data ?? []).map(strategyRow); }
  async createOutcome(input: Omit<FieldOutcome, "id" | "createdAt">) { this.assertTenant(input.tenantId); validateSnapshots(input); const { data, error } = await this.client.from("field_outcomes").insert(outcomeInsert({ ...input, tenantId: this.tenantId })).select("*").single(); fail(error, "crear field outcome"); return outcomeRow(data); }
  async findOutcome(id: string) { const { data, error } = await this.client.from("field_outcomes").select("*").eq("tenant_id", this.tenantId).eq("id", id).maybeSingle(); fail(error, "leer field outcome"); return data ? outcomeRow(data) : null; }
  async findOutcomeByTransactionId(transactionId: string) { const { data, error } = await this.client.from("field_outcomes").select("*").eq("tenant_id", this.tenantId).eq("transaction_id", transactionId).maybeSingle(); fail(error, "leer field outcome"); return data ? outcomeRow(data) : null; }
  async listOutcomes() { const { data, error } = await this.client.from("field_outcomes").select("*").eq("tenant_id", this.tenantId).order("created_at", { ascending: false }); fail(error, "listar field outcomes"); return (data ?? []).map(outcomeRow); }
  async createFeedback(input: Omit<FieldFeedback, "id" | "createdAt">) { this.assertTenant(input.tenantId); const { data, error } = await this.client.from("field_feedback").insert({ tenant_id: this.tenantId, field_outcome_id: input.fieldOutcomeId, human_accepted: input.humanAccepted, failure_tags: input.failureTags, human_correction: input.humanCorrection, acceptance_source: input.acceptanceSource, recorded_by: input.recordedBy }).select("*").single(); fail(error, "crear field feedback"); return feedbackRow(data); }
  async findFeedbackByOutcomeId(fieldOutcomeId: string) { const { data, error } = await this.client.from("field_feedback").select("*").eq("tenant_id", this.tenantId).eq("field_outcome_id", fieldOutcomeId).maybeSingle(); fail(error, "leer field feedback"); return data ? feedbackRow(data) : null; }
  async listFeedback() { const { data, error } = await this.client.from("field_feedback").select("*").eq("tenant_id", this.tenantId).order("created_at", { ascending: false }); fail(error, "listar field feedback"); return (data ?? []).map(feedbackRow); }
  async createRegressionCandidate(input: Omit<FieldRegressionCandidate, "id" | "createdAt">) { this.assertTenant(input.tenantId); const { data, error } = await this.client.from("field_regression_candidates").insert({ tenant_id: this.tenantId, field_outcome_id: input.fieldOutcomeId, reason: input.reason }).select("*").single(); fail(error, "crear regression candidate"); return regressionRow(data); }
  async findRegressionByOutcomeId(fieldOutcomeId: string) { const { data, error } = await this.client.from("field_regression_candidates").select("*").eq("tenant_id", this.tenantId).eq("field_outcome_id", fieldOutcomeId).maybeSingle(); fail(error, "leer regression candidate"); return data ? regressionRow(data) : null; }
  async createGoldenCase(input: Omit<FieldGoldenCase, "id" | "createdAt">) { this.assertTenant(input.tenantId); const { data, error } = await this.client.from("field_golden_cases").insert({ tenant_id: this.tenantId, field_outcome_id: input.fieldOutcomeId, golden_version: input.goldenVersion, intent_expectation: input.intentExpectation, critical_preservation_expectation: input.criticalPreservationExpectation, promotion_reason: input.promotionReason, provenance: input.provenance, regression_candidate_id: input.regressionCandidateId, usage_authorization_status: input.usageAuthorizationStatus }).select("*").single(); fail(error, "crear golden case"); return goldenRow(data); }
  async findGoldenByOutcomeId(fieldOutcomeId: string) { const { data, error } = await this.client.from("field_golden_cases").select("*").eq("tenant_id", this.tenantId).eq("field_outcome_id", fieldOutcomeId).maybeSingle(); fail(error, "leer golden case"); return data ? goldenRow(data) : null; }
  async listGoldenCases() { const { data, error } = await this.client.from("field_golden_cases").select("*").eq("tenant_id", this.tenantId).order("created_at", { ascending: false }); fail(error, "listar golden cases"); return (data ?? []).map(goldenRow); }
  async createEvaluationSample(input: Omit<FieldEvaluationSample, "id" | "createdAt">) { this.assertTenant(input.tenantId); const { data, error } = await this.client.from("field_evaluation_samples").insert({ tenant_id: this.tenantId, field_outcome_id: input.fieldOutcomeId, candidate_a_id: input.candidateAId, candidate_a_strategy: input.candidateAStrategy, candidate_b_id: input.candidateBId, candidate_b_strategy: input.candidateBStrategy }).select("*").single(); fail(error, "crear evaluation sample"); return sampleRow(data); }
  async findEvaluationSampleByOutcomeId(fieldOutcomeId: string) { const { data, error } = await this.client.from("field_evaluation_samples").select("*").eq("tenant_id", this.tenantId).eq("field_outcome_id", fieldOutcomeId).maybeSingle(); fail(error, "leer evaluation sample"); return data ? sampleRow(data) : null; }
  async findEvaluationSample(id: string) { const { data, error } = await this.client.from("field_evaluation_samples").select("*").eq("tenant_id", this.tenantId).eq("id", id).maybeSingle(); fail(error, "leer evaluation sample"); return data ? sampleRow(data) : null; }
  async createEvaluationJudgment(input: Omit<FieldEvaluationJudgment, "id" | "createdAt">) { this.assertTenant(input.tenantId); const { data, error } = await this.client.from("field_evaluation_judgments").insert({ tenant_id: this.tenantId, sample_id: input.sampleId, preference: input.preference }).select("*").single(); fail(error, "crear evaluation judgment"); return judgmentRow(data); }
  async findEvaluationJudgment(sampleId: string) { const { data, error } = await this.client.from("field_evaluation_judgments").select("*").eq("tenant_id", this.tenantId).eq("sample_id", sampleId).maybeSingle(); fail(error, "leer evaluation judgment"); return data ? judgmentRow(data) : null; }

  private assertTenant(tenantId: string): void {
    if (tenantId !== this.tenantId) throw new Error("Tenant boundary violation.");
  }
}

function fail(error: { message: string } | null, action: string): void { if (error) throw new Error(`No se pudo ${action}: ${error.message}`); }
function policyRow(row: Record<string, unknown>): FieldPolicyRecord { return { policyVersion: String(row.policy_version), status: String(row.status), definition: row.definition as FieldPolicyRecord["definition"], createdAt: String(row.created_at) }; }
function strategyRow(row: Record<string, unknown>): FieldStrategyRun { return { id: String(row.id), transactionId: String(row.transaction_id), executionRunId: String(row.execution_run_id), rawCandidateId: String(row.raw_candidate_id), candidateId: String(row.candidate_id), policyVersion: String(row.policy_version), strategyId: PreservationStrategyIdSchema.parse(row.strategy_id), parameters: PreservationStrategyParametersSchema.parse(row.parameters), role: StrategyRoleSchema.parse(row.candidate_role), machineMetrics: PreservationEvidenceMetricsSchema.parse(row.machine_metrics), preservationLatencyMs: Number(row.preservation_latency_ms), createdAt: String(row.created_at), tenantId: String(row.tenant_id), outcomeSku: "precision-edit-v0", blueprintId: String(row.blueprint_id), blueprintVersion: Number(row.blueprint_version), blueprintHash: String(row.blueprint_hash), taskSpecId: String(row.task_spec_id), taskSpecVersion: Number(row.task_spec_version), taskSpecHash: String(row.task_spec_hash), specCompilerVersion: String(row.spec_compiler_version) }; }
function outcomeInsert(input: Omit<FieldOutcome, "id" | "createdAt">) { return { tenant_id: input.tenantId, transaction_id: input.transactionId, source_version_id: input.sourceVersionId, source_sha256: input.sourceSha256, instruction: input.instruction, roi: input.roi, topology: input.topology, task_type: input.taskType, provider: input.provider, model: input.model, raw_candidate_id: input.rawCandidateId, delivered_candidate_id: input.deliveredCandidateId, recommended_strategy: input.recommendedStrategy, strategy_id: input.strategyId, policy_version: input.policyVersion, outcome_sku: input.outcomeSku, blueprint_id: input.blueprintId, blueprint_version: input.blueprintVersion, blueprint_hash: input.blueprintHash, blueprint_snapshot: input.blueprintSnapshot, task_spec_id: input.taskSpecId, task_spec_version: input.taskSpecVersion, task_spec_hash: input.taskSpecHash, task_spec_snapshot: input.taskSpecSnapshot, spec_compiler_name: input.specCompilerName, spec_compiler_version: input.specCompilerVersion, machine_verification_status: input.machineVerificationStatus, same_spec_status: input.sameSpecStatus, override_reason: input.overrideReason, provider_latency_ms: input.providerLatencyMs, preservation_latency_ms: input.preservationLatencyMs, total_latency_ms: input.totalLatencyMs, provider_cost_usd: input.providerCostUsd }; }
function outcomeRow(row: Record<string, unknown>): FieldOutcome { const blueprintSnapshot = OutcomeBlueprintSchema.parse(row.blueprint_snapshot); const taskSpecSnapshot = TaskSpecSchema.parse(row.task_spec_snapshot); if (!verifyOutcomeBlueprintHash(blueprintSnapshot) || blueprintSnapshot.id !== String(row.blueprint_id) || blueprintSnapshot.version !== Number(row.blueprint_version) || blueprintSnapshot.hash !== String(row.blueprint_hash) || !verifyTaskSpecHash(taskSpecSnapshot) || taskSpecSnapshot.id !== String(row.task_spec_id) || taskSpecSnapshot.version !== Number(row.task_spec_version) || taskSpecSnapshot.hash !== String(row.task_spec_hash) || taskSpecSnapshot.blueprint.hash !== String(row.blueprint_hash)) throw new Error("Persisted Blueprint/Task Spec snapshot failed hash verification."); return { id: String(row.id), transactionId: String(row.transaction_id), sourceVersionId: String(row.source_version_id), instruction: String(row.instruction), roi: row.roi as Record<string, number>, topology: StudyTopologySchema.parse(row.topology), taskType: StudyTaskTypeSchema.parse(row.task_type), provider: String(row.provider), model: String(row.model), rawCandidateId: String(row.raw_candidate_id), deliveredCandidateId: String(row.delivered_candidate_id), recommendedStrategy: PreservationStrategyIdSchema.parse(row.recommended_strategy), strategyId: PreservationStrategyIdSchema.parse(row.strategy_id), policyVersion: String(row.policy_version), overrideReason: row.override_reason === null ? null : String(row.override_reason), providerLatencyMs: Number(row.provider_latency_ms), preservationLatencyMs: Number(row.preservation_latency_ms), totalLatencyMs: Number(row.total_latency_ms), providerCostUsd: row.provider_cost_usd === null ? null : Number(row.provider_cost_usd), createdAt: String(row.created_at), tenantId: String(row.tenant_id), outcomeSku: "precision-edit-v0", blueprintId: String(row.blueprint_id), blueprintVersion: Number(row.blueprint_version), blueprintHash: String(row.blueprint_hash), taskSpecId: String(row.task_spec_id), taskSpecVersion: Number(row.task_spec_version), taskSpecHash: String(row.task_spec_hash), specCompilerName: String(row.spec_compiler_name), specCompilerVersion: String(row.spec_compiler_version), sourceSha256: String(row.source_sha256), machineVerificationStatus: row.machine_verification_status as FieldOutcome["machineVerificationStatus"], sameSpecStatus: row.same_spec_status as FieldOutcome["sameSpecStatus"], blueprintSnapshot, taskSpecSnapshot }; }
function feedbackRow(row: Record<string, unknown>): FieldFeedback { return { id: String(row.id), tenantId: String(row.tenant_id ?? "internal-lab"), fieldOutcomeId: String(row.field_outcome_id), humanAccepted: Boolean(row.human_accepted), failureTags: FieldFailureTagSchema.array().parse(row.failure_tags), humanCorrection: row.human_correction === null ? null : String(row.human_correction), createdAt: String(row.created_at), acceptanceSource: "HUMAN_EVALUATOR", recordedBy: "internal-evaluator" }; }
function regressionRow(row: Record<string, unknown>): FieldRegressionCandidate { return { id: String(row.id), tenantId: String(row.tenant_id ?? "internal-lab"), fieldOutcomeId: String(row.field_outcome_id), reason: String(row.reason), createdAt: String(row.created_at) }; }
function goldenRow(row: Record<string, unknown>): FieldGoldenCase { return { id: String(row.id), tenantId: String(row.tenant_id ?? "internal-lab"), fieldOutcomeId: String(row.field_outcome_id), goldenVersion: String(row.golden_version), intentExpectation: String(row.intent_expectation), criticalPreservationExpectation: String(row.critical_preservation_expectation), promotionReason: String(row.promotion_reason), provenance: row.provenance as Record<string, unknown>, regressionCandidateId: row.regression_candidate_id === null ? null : String(row.regression_candidate_id), createdAt: String(row.created_at), usageAuthorizationStatus: row.usage_authorization_status as FieldGoldenCase["usageAuthorizationStatus"] }; }
function sampleRow(row: Record<string, unknown>): FieldEvaluationSample { return { id: String(row.id), tenantId: String(row.tenant_id), fieldOutcomeId: String(row.field_outcome_id), candidateAId: String(row.candidate_a_id), candidateAStrategy: PreservationStrategyIdSchema.parse(row.candidate_a_strategy), candidateBId: String(row.candidate_b_id), candidateBStrategy: PreservationStrategyIdSchema.parse(row.candidate_b_strategy), createdAt: String(row.created_at) }; }
function judgmentRow(row: Record<string, unknown>): FieldEvaluationJudgment { return { id: String(row.id), tenantId: String(row.tenant_id), sampleId: String(row.sample_id), preference: row.preference as FieldEvaluationJudgment["preference"], createdAt: String(row.created_at) }; }
function validateSnapshots(input: Omit<FieldOutcome, "id" | "createdAt">): void { const blueprint = OutcomeBlueprintSchema.parse(input.blueprintSnapshot); const taskSpec = TaskSpecSchema.parse(input.taskSpecSnapshot); if (!verifyOutcomeBlueprintHash(blueprint) || blueprint.id !== input.blueprintId || blueprint.version !== input.blueprintVersion || blueprint.hash !== input.blueprintHash || !verifyTaskSpecHash(taskSpec) || taskSpec.id !== input.taskSpecId || taskSpec.version !== input.taskSpecVersion || taskSpec.hash !== input.taskSpecHash || taskSpec.blueprint.hash !== input.blueprintHash) throw new Error("Blueprint/Task Spec snapshot does not match persisted provenance."); }
