import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cases } from "@/content/site";
type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return cases.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const item = cases.find((entry) => entry.slug === slug); return item ? { title: item.name, description: item.after } : {}; }
export default async function Page({ params }: Props) { const { slug } = await params; const item = cases.find((entry) => entry.slug === slug); if (!item) notFound(); return <main id="main-content"><section className="page-hero section"><div className="shell"><span className="tag"><span className="dot" /> Proyecto conceptual · No es un cliente real</span><p className="case-kicker">{item.sector}</p><h1 className="display">{item.name}</h1><p className="lead">Una demostración de cómo Studio, Systems y Academy podrían coordinarse para este contexto.</p></div></section><section className="section section-rule"><div className="shell case-story"><div className="case-story-visual" style={{ "--case": item.color } as React.CSSProperties}><div><small>Transformación conceptual</small><strong>{item.name}</strong><span>{item.sector} · CDMX</span></div></div><div><span className="eyebrow">El recorrido</span><h2>De una oportunidad visible a un sistema conectado.</h2><article><span>ANTES</span><p>{item.before}</p></article><article><span>DESPUÉS · ESCENARIO</span><p>{item.after}</p></article><div className="dimension-list">{item.dimensions.map((dimension) => <span key={dimension}><CheckCircle2 />{dimension}</span>)}</div><p className="micro">No se muestran métricas porque este proyecto no fue implementado. Cualquier resultado futuro requerirá línea base, periodo, fuente y limitaciones.</p><Button asChild variant="acid"><Link href={`/diagnostico?case=${item.slug}`}>Quiero explorar algo así <ArrowRight /></Link></Button></div></div></section></main>; }
