"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { FileBarChart, FileDown, LoaderCircle, ShieldCheck, Sparkles } from "lucide-react";
import { events, workspace } from "@/lib/data/seed";
import { reportBuilder, reportDefinitions } from "@/lib/services/report-builder";
import type { EnterpriseReport, ReportType } from "@/lib/types/understanding";
import { useLanguage } from "@/components/i18n/language-provider";
import { listStoredAssistantEvidence, subscribeAssistantEvents } from "@/lib/services/assistant-event-store";
import type { UnderstandingEvent } from "@/lib/types/understanding";

const spanishReportLabels: Record<ReportType, string> = {
  "meaning-loss-audit": "Reporte de auditoría de Meaning Loss", "product-delivery-understanding": "Reporte de entendimiento de entrega de producto", "ai-understanding-audit": "Auditoría de entendimiento para IA", "handoff-readiness": "Reporte de readiness de handoffs", "process-understanding": "Reporte de entendimiento de procesos", "onboarding-understanding": "Reporte de entendimiento de onboarding", "consulting-delivery": "Reporte de entrega para consultoras", "technical-documentation-understanding": "Reporte de entendimiento de documentación técnica", "executive-virro-score": "Reporte ejecutivo Virro Score",
};

const clientReportSections = [
  { number: "01", title: ["Executive summary", "Resumen ejecutivo"], detail: ["The flow loses operational meaning before QA can act without clarification.", "El flujo pierde significado operativo antes de que QA pueda actuar sin aclaraciones."] },
  { number: "02", title: ["Pain detected", "Dolor detectado"], detail: ["The handoff moves forward without a shared definition of done or enough context for QA.", "El handoff avanza sin una definición compartida de terminado ni contexto suficiente para QA."] },
  { number: "03", title: ["Reviewed events", "Eventos revisados"], detail: ["Four Understanding Events across Product Delivery and Handoff Intelligence.", "Cuatro Understanding Events entre Product Delivery y Handoff Intelligence."] },
  { number: "04", title: ["Main risks", "Riesgos principales"], detail: ["Different interpretations, late rework and decisions without an explicit owner.", "Interpretaciones distintas, retrabajo tardío y decisiones sin owner explícito."] },
  { number: "05", title: ["Missing context", "Contexto faltante"], detail: ["Receiver, acceptance evidence, exception path and final decision owner.", "Receptor, evidencia de aceptación, ruta de excepciones y owner de decisión final."] },
  { number: "06", title: ["Critical questions to validate", "Preguntas críticas para validar"], detail: ["What evidence makes the handoff acceptable and who resolves exceptions?", "¿Qué evidencia permite aceptar el handoff y quién resuelve las excepciones?"] },
  { number: "07", title: ["Estimated scores", "Scores estimados"], detail: ["DoU Score 58/100 · Meaning Loss Risk 63/100 · Handoff Readiness 41/100.", "DoU Score 58/100 · Meaning Loss Risk 63/100 · Handoff Readiness 41/100."] },
  { number: "08", title: ["Pilot recommendation", "Recomendación de piloto"], detail: ["Run a pilot focused on Handoff Intelligence / Product Delivery.", "Ejecutar un piloto enfocado en Handoff Intelligence / Product Delivery."] },
  { number: "09", title: ["Next actions", "Próximas acciones"], detail: ["Define the receiver, minimum context, decision owner and observable readiness criterion.", "Definir receptor, contexto mínimo, owner de decisión y criterio observable de readiness."] },
];

export function ReportBuilder() {
  const { locale, t } = useLanguage();
  const [type, setType] = useState<ReportType>("executive-virro-score");
  const [report, setReport] = useState<EnterpriseReport | null>(null);
  const [building, setBuilding] = useState(false);
  const [assistantEvents, setAssistantEvents] = useState<UnderstandingEvent[]>([]);
  useEffect(() => {
    const sync = () => setAssistantEvents(listStoredAssistantEvidence().map((item) => item.event));
    const timer = window.setTimeout(sync, 0);
    const unsubscribe = subscribeAssistantEvents(sync);
    return () => { window.clearTimeout(timer); unsubscribe(); };
  }, []);
  const reportEvents = useMemo(() => [...assistantEvents, ...events], [assistantEvents]);

  function generate() {
    setBuilding(true);
    window.setTimeout(() => {
      setReport(reportBuilder.buildReport(workspace.id, reportEvents, type, undefined, locale));
      setBuilding(false);
    }, 350);
  }

  return <div className="space-y-6"><section><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.16em] text-teal-300">15 · Report Builder</p><h1 className="text-2xl font-semibold tracking-[-.035em] md:text-[30px]">{t("Executive understanding reports, ready for decisions.", "Reportes ejecutivos de entendimiento, listos para decisiones.")}</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">{t("Generate a structured enterprise document from Understanding Events, risk estimates and unresolved context—not a conversational response.", "Genera un documento enterprise estructurado a partir de Understanding Events, estimaciones de riesgo y contexto sin resolver, no una respuesta conversacional.")}</p></section>
    <section className="overflow-hidden rounded-2xl border border-indigo-400/15 bg-[linear-gradient(135deg,rgba(99,102,241,.09),rgba(16,20,28,.92)_58%)] shadow-[0_28px_90px_rgba(0,0,0,.16)]"><div className="flex flex-col gap-5 border-b border-indigo-300/10 p-5 md:flex-row md:items-center md:justify-between md:p-7"><div><div className="flex flex-wrap items-center gap-2"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-indigo-300">Enterprise Understanding Audit</p><span className="rounded-full border border-indigo-300/15 bg-indigo-300/[.07] px-2 py-1 text-[8px] font-semibold uppercase tracking-[.12em] text-indigo-200">{t("Final audit deliverable · Demo", "Entregable final de auditoría · Demo")}</span></div><h2 className="mt-3 text-xl font-semibold tracking-[-.025em]">{t("Executive report example", "Ejemplo de reporte ejecutivo")}</h2><p className="mt-2 max-w-3xl text-xs leading-6 text-[var(--muted)]">{t("A client-facing decision surface built from safe signals, aggregated findings and probabilistic readiness estimates—not personal performance.", "Una superficie de decisión para cliente construida con señales seguras, hallazgos agregados y estimaciones probabilísticas de readiness, no desempeño personal.")}</p></div><Link href="/#solicitar-diagnostico" className="inline-flex h-10 shrink-0 items-center justify-center rounded-lg border border-indigo-300/20 bg-indigo-300/[.08] px-4 text-xs font-semibold text-indigo-100">{t("Request an audit", "Solicitar auditoría")}</Link></div><div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-4 md:p-7">{[
      [t("Demo client", "Cliente demo"), "Aperture Systems"], [t("Audit type", "Tipo de auditoría"), "Enterprise Understanding Audit"], [t("Analyzed flow", "Flujo analizado"), "Product Delivery / Handoff"], [t("Reviewed events", "Eventos revisados"), "4 Understanding Events"], [t("Average DoU Score", "DoU Score promedio"), t("58/100 estimated", "58/100 estimado")], ["Meaning Loss Risk", t("63/100 estimated", "63/100 estimado")], [t("Recommendation", "Recomendación"), t("Focused Handoff / Product pilot", "Piloto enfocado en Handoff / Product")],
    ].map(([label, value]) => <div key={label} className="rounded-xl border border-white/[.07] bg-black/10 p-3"><p className="text-[9px] uppercase tracking-[.1em] text-[var(--subtle)]">{label}</p><p className="mt-2 text-xs font-semibold">{value}</p></div>)}</div><div className="border-t border-indigo-300/10 px-5 py-4 md:px-6"><p className="text-[10px] leading-5 text-[var(--muted)]"><strong className="text-[var(--text)]">{t("Main risk", "Riesgo principal")}:</strong> {t("information moves forward without enough context for the next team.", "la información avanza sin contexto suficiente para el siguiente equipo.")} <strong className="ml-1 text-[var(--text)]">{t("Recommendation", "Recomendación")}:</strong> {t("run a Meaning Loss Audit or focused pilot.", "ejecutar un Meaning Loss Audit o piloto enfocado.")}</p></div></section>
    <section className="rounded-2xl border border-teal-400/15 bg-teal-400/[.04] p-5 md:p-6"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-teal-300">{t("Report structure", "Estructura del reporte")}</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{clientReportSections.map((section) => <article key={section.number} className="rounded-xl border border-white/[.07] bg-black/10 p-4"><p className="text-[9px] font-semibold text-teal-300">{section.number}</p><h3 className="mt-2 text-xs font-semibold">{t(section.title[0], section.title[1])}</h3><p className="mt-2 text-[10px] leading-5 text-[var(--muted)]">{t(section.detail[0], section.detail[1])}</p></article>)}</div><div className="mt-5 grid gap-2 border-t border-teal-300/10 pt-4 text-[10px] leading-5 text-[var(--muted)] md:grid-cols-2 xl:grid-cols-4"><p className="flex items-start gap-2"><ShieldCheck size={13} className="mt-0.5 shrink-0 text-teal-300" />{t("Virro must be more trustworthy than intelligent.", "Virro debe ser más confiable que inteligente.")}</p><p className="flex items-start gap-2"><ShieldCheck size={13} className="mt-0.5 shrink-0 text-teal-300" />{t("Virro reports do not evaluate people. They estimate interpretation risks in operational information.", "Los reportes de Virro no evalúan personas. Estiman riesgos de interpretación en información operativa.")}</p><p className="flex items-start gap-2"><ShieldCheck size={13} className="mt-0.5 shrink-0 text-teal-300" />{t("Scores are probabilistic estimates, not guarantees.", "Los scores son estimaciones probabilísticas, no garantías.")}</p><p className="flex items-start gap-2"><ShieldCheck size={13} className="mt-0.5 shrink-0 text-teal-300" />{t("Virro does not retain raw private text by default and is not designed to monitor employees.", "Virro no guarda texto privado crudo por defecto y no está diseñado para vigilar empleados.")}</p></div></section>
    <section className="grid items-start gap-4 xl:grid-cols-[.42fr_1.58fr]"><aside className="panel p-5"><div className="flex items-center gap-2"><FileBarChart size={16} className="text-teal-300" /><h2 className="text-sm font-semibold">{t("Report configuration", "Configuración del reporte")}</h2></div><label className="mt-5 block"><span className="mb-2 block text-[10px] font-medium text-[var(--muted)]">{t("Report type", "Tipo de reporte")}</span><select value={type} onChange={(event) => setType(event.target.value as ReportType)} className="field-control">{reportDefinitions.map((definition) => <option key={definition.type} value={definition.type}>{locale === "es" ? spanishReportLabels[definition.type] : definition.label}</option>)}</select></label><div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-[9px] uppercase tracking-[.1em] text-[var(--subtle)]">{t("Workspace scope", "Alcance del workspace")}</p><p className="mt-1.5 text-xs font-medium">{workspace.name}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{reportEvents.length} {t("active Understanding Events", "Understanding Events activos")}</p>{assistantEvents.length > 0 && <p className="mt-1 text-[9px] text-indigo-300">+ {assistantEvents.length} {t("from the assistant mock store", "del store mock del asistente")}</p>}</div><button onClick={generate} disabled={building} className="mt-4 inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-teal-300 px-4 text-xs font-semibold text-slate-950 disabled:opacity-60">{building ? <LoaderCircle size={14} className="animate-spin" /> : <Sparkles size={14} />}{building ? t("Building report…", "Construyendo reporte…") : t("Generate Report", "Generar reporte")}</button>{report && <button onClick={() => window.print()} className="mt-2 inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg border border-[var(--border)] text-xs font-medium"><FileDown size={14} /> {t("Print / Export", "Imprimir / Exportar")}</button>}<p className="mt-4 text-[9px] leading-4 text-[var(--subtle)]">{t("Scores in exported reports remain identified as probabilistic estimates.", "Los scores exportados permanecen identificados como estimaciones probabilísticas.")}</p></aside>
      {!report ? <article className="panel grid min-h-[720px] place-items-center p-8 text-center"><div><div className="mx-auto grid size-14 place-items-center rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] text-[var(--subtle)]"><FileBarChart size={22} /></div><h2 className="mt-4 text-sm font-semibold">{t("Executive document preview", "Vista previa del documento ejecutivo")}</h2><p className="mx-auto mt-2 max-w-sm text-xs leading-5 text-[var(--subtle)]">{t("Choose one of nine report types and generate a visual report from current workspace evidence.", "Elige uno de nueve tipos de reporte y genera un reporte visual con la evidencia del workspace.")}</p></div></article> : <ReportDocument report={report} />}
    </section>
  </div>;
}

function ReportDocument({ report }: { report: EnterpriseReport }) {
  const { locale, t } = useLanguage();
  const scores = Object.entries(report.scores).filter(([, value]) => value !== undefined).slice(0, 6);
  return <article className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--panel)] shadow-[0_25px_80px_rgba(0,0,0,.18)] print:border-0"><header className="border-b border-[var(--border)] bg-[var(--panel-soft)] px-6 py-6 md:px-8"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-teal-300">Virro Enterprise Report</p><h2 className="mt-2 text-xl font-semibold tracking-[-.03em]">{locale === "es" ? spanishReportLabels[report.reportType] : report.title}</h2><p className="mt-1 text-[10px] text-[var(--subtle)]">{report.id} · {new Date(report.createdAt).toLocaleDateString(locale)} · {workspace.name}</p></div><div className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-teal-300 to-cyan-500 text-sm font-black text-slate-950">V</div></div></header><div className="space-y-7 p-6 md:p-8"><ReportSection number="01" title={t("Executive Summary", "Resumen ejecutivo")}><p className="text-xs leading-6 text-[var(--muted)]">{report.summary}</p></ReportSection><ReportSection number="02" title={t("What was analyzed", "Qué se analizó")}><BulletList items={report.whatWasAnalyzed} /></ReportSection><ReportSection number="03" title="Scores"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{scores.map(([label, value]) => <div key={label} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[9px] capitalize text-[var(--subtle)]">{label.replace(/([A-Z])/g, " $1")}</p></div>)}</div><p className="mt-3 flex items-center gap-2 text-[9px] text-[var(--subtle)]"><ShieldCheck size={11} />{t("All scores are estimates of operational readiness and risk.", "Todos los scores son estimaciones de readiness y riesgo operativo.")}</p></ReportSection><div className="grid gap-6 lg:grid-cols-2"><ReportSection number="04" title={t("Key risks", "Riesgos clave")}><BulletList items={report.findings} /></ReportSection><ReportSection number="05" title={t("Missing context", "Contexto faltante")}><BulletList items={report.missingContext} /></ReportSection></div><div className="grid gap-6 lg:grid-cols-2"><ReportSection number="06" title={t("Critical questions to validate", "Preguntas críticas para validar")}><BulletList items={report.criticalQuestions} /></ReportSection><ReportSection number="07" title={t("Recommended actions", "Acciones recomendadas")}><BulletList items={report.recommendations} /></ReportSection></div><ReportSection number="08" title="Understanding Debt Backlog"><BulletList items={report.understandingDebtBacklog} /></ReportSection><ReportSection number="09" title={t("Suggested next pilot or expansion", "Próximo piloto o expansión sugerida")}><div className="rounded-xl border border-teal-400/15 bg-teal-400/[.045] p-4 text-xs leading-6 text-[var(--muted)]">{report.suggestedNextPilot}</div></ReportSection></div></article>;
}

function ReportSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section><div className="mb-3 flex items-center gap-2"><span className="text-[9px] font-semibold text-teal-300">{number}</span><h3 className="text-xs font-semibold uppercase tracking-[.08em]">{title}</h3></div>{children}</section>; }
function BulletList({ items }: { items: string[] }) { return <div className="space-y-2">{items.length ? items.map((item) => <div key={item} className="flex items-start gap-2 text-[10px] leading-5 text-[var(--muted)]"><span className="mt-2 size-1 shrink-0 rounded-full bg-teal-300" />{item}</div>) : <p className="text-[10px] text-emerald-300">No material finding.</p>}</div>; }
