"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { FileBarChart, FileDown, LoaderCircle, ShieldCheck, Sparkles } from "lucide-react";
import { events, workspace } from "@/lib/data/seed";
import { reportBuilder, reportDefinitions } from "@/lib/services/report-builder";
import type { EnterpriseReport, ReportType } from "@/lib/types/understanding";
import { useLanguage } from "@/components/i18n/language-provider";
import { listStoredAssistantEvidence, subscribeAssistantEvents } from "@/lib/services/assistant-event-store";
import type { UnderstandingEvent } from "@/lib/types/understanding";

const spanishReportLabels: Record<ReportType, string> = {
  "meaning-loss-audit": "Reporte de audit de Meaning Loss", "product-delivery-understanding": "Reporte de entendimiento de entrega de producto", "ai-understanding-audit": "Audit de entendimiento para IA", "handoff-readiness": "Reporte de readiness de handoffs", "process-understanding": "Reporte de entendimiento de procesos", "onboarding-understanding": "Reporte de entendimiento de onboarding", "consulting-delivery": "Reporte de entrega para consultoras", "technical-documentation-understanding": "Reporte de entendimiento de documentación técnica", "executive-virro-score": "Reporte ejecutivo Virro Score",
};

export function ReportBuilder() {
  const { locale, t } = useLanguage();
  const [type, setType] = useState<ReportType>("executive-virro-score");
  const [report, setReport] = useState<EnterpriseReport | null>(null);
  const [building, setBuilding] = useState(false);
  const [assistantEvents, setAssistantEvents] = useState<UnderstandingEvent[]>([]);
  useEffect(() => {
    const sync = () => setAssistantEvents(listStoredAssistantEvidence().map((item) => item.event));
    const timer = window.setTimeout(sync, 0);
    const unsubscribe = subscribeAssistantEvents(sync);
    return () => { window.clearTimeout(timer); unsubscribe(); };
  }, []);
  const reportEvents = useMemo(() => [...assistantEvents, ...events], [assistantEvents]);

  function generate() {
    setBuilding(true);
    window.setTimeout(() => {
      setReport(reportBuilder.buildReport(workspace.id, reportEvents, type, undefined, locale));
      setBuilding(false);
    }, 350);
  }

  return <div className="space-y-6"><section><p className="mb-2 text-[11px] font-semibold uppercase tracking-[.16em] text-teal-300">15 · Report Builder</p><h1 className="text-2xl font-semibold tracking-[-.035em] md:text-[30px]">{t("Executive understanding reports, ready for decisions.", "Reportes ejecutivos de entendimiento, listos para decisiones.")}</h1><p className="mt-2 max-w-3xl text-sm text-[var(--muted)]">{t("Generate a structured enterprise document from Understanding Events, risk estimates and unresolved context—not a conversational response.", "Genera un documento enterprise estructurado a partir de Understanding Events, estimaciones de riesgo y contexto sin resolver, no una respuesta conversacional.")}</p></section>
    <section className="flex flex-col gap-5 rounded-2xl border border-indigo-400/15 bg-indigo-400/[.045] p-5 md:flex-row md:items-center md:justify-between md:p-6"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-indigo-300">Meaning Loss Audit</p><h2 className="mt-2 text-base font-semibold">{t("Example report a client would receive", "Ejemplo de reporte que recibiría un cliente")}</h2><p className="mt-2 max-w-3xl text-xs leading-6 text-[var(--muted)]">{t("After a Meaning Loss Audit, Virro can deliver a report with the analyzed flow, reviewed events, main risks, estimated scores, critical questions, correction opportunities and a pilot recommendation.", "Después de un Meaning Loss Audit, Virro puede entregar un reporte con flujo analizado, eventos revisados, riesgos principales, scores estimados, preguntas críticas, oportunidades de corrección y recomendación de piloto.")}</p></div><Link href="/#solicitar-diagnostico" className="inline-flex h-10 shrink-0 items-center justify-center rounded-lg border border-indigo-300/20 bg-indigo-300/[.08] px-4 text-xs font-semibold text-indigo-100">{t("Request a diagnosis again", "Volver a solicitar diagnóstico")}</Link></section>
    <section className="rounded-2xl border border-teal-400/15 bg-teal-400/[.04] p-5 md:p-6"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-teal-300">{t("Executive deliverable", "Entregable ejecutivo")}</p><h2 className="mt-2 text-lg font-semibold">{t("What does Virro deliver after a diagnosis?", "¿Qué entrega Virro después de un diagnóstico?")}</h2><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[
      t("Pain detected", "Dolor detectado"), t("Flow analyzed", "Flujo analizado"), t("Understanding Events reviewed", "Understanding Events revisados"), t("Main risks", "Riesgos principales"), t("Estimated scores", "Scores estimados"), t("Critical questions", "Preguntas críticas"), t("Pilot recommendation", "Recomendación de piloto"), t("Next actions", "Próximas acciones"),
    ].map((item) => <div key={item} className="rounded-lg border border-white/[.07] bg-black/10 px-3 py-2 text-[10px] text-[var(--muted)]">{item}</div>)}</div></section>
    <section className="grid items-start gap-4 xl:grid-cols-[.42fr_1.58fr]"><aside className="panel p-5"><div className="flex items-center gap-2"><FileBarChart size={16} className="text-teal-300" /><h2 className="text-sm font-semibold">{t("Report configuration", "Configuración del reporte")}</h2></div><label className="mt-5 block"><span className="mb-2 block text-[10px] font-medium text-[var(--muted)]">{t("Report type", "Tipo de reporte")}</span><select value={type} onChange={(event) => setType(event.target.value as ReportType)} className="field-control">{reportDefinitions.map((definition) => <option key={definition.type} value={definition.type}>{locale === "es" ? spanishReportLabels[definition.type] : definition.label}</option>)}</select></label><div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-[9px] uppercase tracking-[.1em] text-[var(--subtle)]">{t("Workspace scope", "Alcance del workspace")}</p><p className="mt-1.5 text-xs font-medium">{workspace.name}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{reportEvents.length} {t("active Understanding Events", "Understanding Events activos")}</p>{assistantEvents.length > 0 && <p className="mt-1 text-[9px] text-indigo-300">+ {assistantEvents.length} {t("from the assistant mock store", "del store mock del asistente")}</p>}</div><button onClick={generate} disabled={building} className="mt-4 inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-teal-300 px-4 text-xs font-semibold text-slate-950 disabled:opacity-60">{building ? <LoaderCircle size={14} className="animate-spin" /> : <Sparkles size={14} />}{building ? t("Building report…", "Construyendo reporte…") : t("Generate Report", "Generar reporte")}</button>{report && <button onClick={() => window.print()} className="mt-2 inline-flex h-10 w-full items-center justify-center gap-2 rounded-lg border border-[var(--border)] text-xs font-medium"><FileDown size={14} /> {t("Print / Export", "Imprimir / Exportar")}</button>}<p className="mt-4 text-[9px] leading-4 text-[var(--subtle)]">{t("Scores in exported reports remain identified as probabilistic estimates.", "Los scores exportados permanecen identificados como estimaciones probabilísticas.")}</p></aside>
      {!report ? <article className="panel grid min-h-[720px] place-items-center p-8 text-center"><div><div className="mx-auto grid size-14 place-items-center rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] text-[var(--subtle)]"><FileBarChart size={22} /></div><h2 className="mt-4 text-sm font-semibold">{t("Executive document preview", "Vista previa del documento ejecutivo")}</h2><p className="mx-auto mt-2 max-w-sm text-xs leading-5 text-[var(--subtle)]">{t("Choose one of nine report types and generate a visual report from current workspace evidence.", "Elige uno de nueve tipos de reporte y genera un reporte visual con la evidencia del workspace.")}</p></div></article> : <ReportDocument report={report} />}
    </section>
  </div>;
}

function ReportDocument({ report }: { report: EnterpriseReport }) {
  const { locale, t } = useLanguage();
  const scores = Object.entries(report.scores).filter(([, value]) => value !== undefined).slice(0, 6);
  return <article className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--panel)] shadow-[0_25px_80px_rgba(0,0,0,.18)] print:border-0"><header className="border-b border-[var(--border)] bg-[var(--panel-soft)] px-6 py-6 md:px-8"><div className="flex items-start justify-between gap-4"><div><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-teal-300">Virro Enterprise Report</p><h2 className="mt-2 text-xl font-semibold tracking-[-.03em]">{locale === "es" ? spanishReportLabels[report.reportType] : report.title}</h2><p className="mt-1 text-[10px] text-[var(--subtle)]">{report.id} · {new Date(report.createdAt).toLocaleDateString(locale)} · {workspace.name}</p></div><div className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-teal-300 to-cyan-500 text-sm font-black text-slate-950">V</div></div></header><div className="space-y-7 p-6 md:p-8"><ReportSection number="01" title={t("Executive Summary", "Resumen ejecutivo")}><p className="text-xs leading-6 text-[var(--muted)]">{report.summary}</p></ReportSection><ReportSection number="02" title={t("What was analyzed", "Qué se analizó")}><BulletList items={report.whatWasAnalyzed} /></ReportSection><ReportSection number="03" title="Scores"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{scores.map(([label, value]) => <div key={label} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[9px] capitalize text-[var(--subtle)]">{label.replace(/([A-Z])/g, " $1")}</p></div>)}</div><p className="mt-3 flex items-center gap-2 text-[9px] text-[var(--subtle)]"><ShieldCheck size={11} />{t("All scores are estimates of operational readiness and risk.", "Todos los scores son estimaciones de readiness y riesgo operativo.")}</p></ReportSection><div className="grid gap-6 lg:grid-cols-2"><ReportSection number="04" title={t("Key risks", "Riesgos clave")}><BulletList items={report.findings} /></ReportSection><ReportSection number="05" title={t("Missing context", "Contexto faltante")}><BulletList items={report.missingContext} /></ReportSection></div><div className="grid gap-6 lg:grid-cols-2"><ReportSection number="06" title={t("Critical questions", "Preguntas críticas")}><BulletList items={report.criticalQuestions} /></ReportSection><ReportSection number="07" title={t("Recommended actions", "Acciones recomendadas")}><BulletList items={report.recommendations} /></ReportSection></div><ReportSection number="08" title="Understanding Debt Backlog"><BulletList items={report.understandingDebtBacklog} /></ReportSection><ReportSection number="09" title={t("Suggested next pilot or expansion", "Próximo piloto o expansión sugerida")}><div className="rounded-xl border border-teal-400/15 bg-teal-400/[.045] p-4 text-xs leading-6 text-[var(--muted)]">{report.suggestedNextPilot}</div></ReportSection></div></article>;
}

function ReportSection({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section><div className="mb-3 flex items-center gap-2"><span className="text-[9px] font-semibold text-teal-300">{number}</span><h3 className="text-xs font-semibold uppercase tracking-[.08em]">{title}</h3></div>{children}</section>; }
function BulletList({ items }: { items: string[] }) { return <div className="space-y-2">{items.length ? items.map((item) => <div key={item} className="flex items-start gap-2 text-[10px] leading-5 text-[var(--muted)]"><span className="mt-2 size-1 shrink-0 rounded-full bg-teal-300" />{item}</div>) : <p className="text-[10px] text-emerald-300">No material finding.</p>}</div>; }
