// @vitest-environment node

import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { Client } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { createDelegabilityAdmission } from "@/src/domain/outcome/delegability-admission";
import { compileSignalRequirement, createDependencySnapshot, createSignal, currentDefaultEvaluator, evaluateDelegationReadiness, evaluateSignalQualification } from "@/src/domain/outcome/signal-readiness";

const enabled = process.env.BUILD002_NATIVE_PG_C1_D3 === "true";
const databaseUrl = process.env.BUILD002_NATIVE_PG_C1_D3_URL ?? process.env.BUILD002_NATIVE_PG_URL;
const migrationsDir = resolve(process.cwd(), "supabase/migrations");
const ACTOR = "a6000000-0000-4000-8000-000000000001";
const TENANT = "b6000000-0000-4000-8000-000000000001";
const MEMBERSHIP = "b6000000-0000-4000-8000-000000000002";
const PROJECT = "c6000000-0000-4000-8000-000000000001";
const ASSET = "d6000000-0000-4000-8000-000000000001";
const VERSION = "e6000000-0000-4000-8000-000000000001";
const TRANSACTION = "f6000000-0000-4000-8000-000000000001";
const BLUEPRINT = "a7000000-0000-4000-8000-000000000001";
const PROFILE = "a7000000-0000-4000-8000-000000000002";
const SIGNAL = "a8000000-0000-4000-8000-000000000001";
const QUALIFICATION = "a9000000-0000-4000-8000-000000000001";
const READINESS = "aa000000-0000-4000-8000-000000000001";
const BLUEPRINT_HASH = "a".repeat(64);
const ASSET_HASH = "b".repeat(64);
const TRANSACTION_HASH = "c".repeat(64);
const PROFILE_HASH = "d".repeat(64);
const BINDING_HASH = "e".repeat(64);

function connection(url: string, database: string): string { const parsed = new URL(url); parsed.pathname = `/${database}`; return parsed.toString(); }

function graph() {
  const evaluatedAt = new Date(Date.now() - 30_000).toISOString();
  const signal = createSignal({ signalId: SIGNAL, ownerTenantId: TENANT, transactionId: TRANSACTION, requirementId: "signal.d3", payload: { value: "d3" }, source: { identity: "native-d3", version: "1", hash: "f".repeat(64) }, provenance: "OBSERVED", capturedAt: new Date(Date.now() - 60_000).toISOString(), validUntil: new Date(Date.now() + 3_600_000).toISOString(), dependency: { identity: "asset.version", hash: ASSET_HASH }, schemaVersion: "build002-signal-v0.2" });
  const requirement = compileSignalRequirement({ requirementId: "signal.d3", subjectKind: "OUTCOME_TRANSACTION", semanticType: "TEXT", critical: true, acceptedProvenance: ["OBSERVED"], qualificationRule: { version: "1", cardinality: "SINGLE_VALUED", humanReviewRequired: false }, dependencySelectors: [{ identity: "asset.version", required: true }, { identity: "blueprint", required: true }, { identity: "transaction.semantic", required: true }], blueprintId: BLUEPRINT, blueprintVersion: 1, blueprintHash: BLUEPRINT_HASH, policyId: null, policyHash: null, definitionSchemaVersion: "build002-signal-requirement-v0.1" }, evaluatedAt);
  const snapshot = createDependencySnapshot({ schemaVersion: "build002-dependency-snapshot-v0.2", ownerTenantId: TENANT, transactionId: TRANSACTION, requirementDefinitionHashes: [requirement.requirementDefinitionHash], signalReferences: [{ requirementId: requirement.requirementId, signalId: signal.signalId, contentHash: signal.contentHash }], dependencyBindings: [{ identity: "asset.version", hash: ASSET_HASH }, { identity: "blueprint", hash: BLUEPRINT_HASH }, { identity: "transaction.semantic", hash: TRANSACTION_HASH }], blueprintHash: BLUEPRINT_HASH, policyHash: null, taskSpecHash: null, transactionSemanticHash: TRANSACTION_HASH, sourceAssetVersionHash: ASSET_HASH, contextLensHash: null });
  const evaluator = currentDefaultEvaluator();
  const qualification = evaluateSignalQualification({ requirement, signals: [signal], currentDependencySnapshot: snapshot, evaluator, evaluationTime: evaluatedAt, idFactory: () => QUALIFICATION });
  const readiness = evaluateDelegationReadiness({ subject: { kind: "OUTCOME_TRANSACTION", ownerTenantId: TENANT, transactionId: TRANSACTION }, requirements: [requirement], qualifications: [qualification], dependencySnapshot: snapshot, evaluator, evaluationTime: evaluatedAt, idFactory: () => READINESS });
  const payload: Record<string, unknown> = { owner_tenant_id: TENANT, outcome_transaction_id: TRANSACTION, transaction: { ownerTenantId: TENANT, transactionId: TRANSACTION, projectId: PROJECT, assetId: ASSET, baseVersionId: VERSION, rawRequest: "d3 native" }, asset: { id: ASSET, ownerTenantId: TENANT, projectId: PROJECT, currentVersionId: VERSION }, sourceVersion: { id: VERSION, ownerTenantId: TENANT, assetId: ASSET, versionNumber: 1, parentVersionId: null, state: { width: 100 } }, binding: { bindingHash: BINDING_HASH, blueprintId: BLUEPRINT, blueprintVersion: 1, blueprintHash: BLUEPRINT_HASH, requirementProfileId: PROFILE, requirementProfileVersion: 1, requirementProfileHash: PROFILE_HASH }, requirements: [requirement], dependency_snapshot: snapshot, qualifications: [{ ...qualification, signalReferences: qualification.signalIds.map((id, index) => ({ signalId: id, contentHash: qualification.signalContentHashes[index] })) }], readiness };
  return { requirement, signal, snapshot, readiness, evaluator, payload };
}

describe.runIf(enabled && Boolean(databaseUrl))("BUILD002-C1-D3-R1 native PostgreSQL 17 serialized closure", () => {
  let admin: Client; let serviceA: Client; let serviceB: Client; let isolatedDatabase = ""; let value: ReturnType<typeof graph>; let authorityCommitId = "";
  beforeAll(async () => {
    isolatedDatabase = `virro_d3_r1_${process.pid}_${Date.now()}`;
    const root = new Client({ connectionString: connection(databaseUrl!, "postgres") }); await root.connect(); await root.query(`drop database if exists "${isolatedDatabase}" with (force)`); await root.query(`create database "${isolatedDatabase}"`); await root.end();
    admin = new Client({ connectionString: connection(databaseUrl!, isolatedDatabase) }); serviceA = new Client({ connectionString: connection(databaseUrl!, isolatedDatabase) }); serviceB = new Client({ connectionString: connection(databaseUrl!, isolatedDatabase) }); await admin.connect(); await serviceA.connect(); await serviceB.connect();
    await admin.query("create extension if not exists pgcrypto; do $$ begin create role anon nologin; exception when duplicate_object then null; end $$; do $$ begin create role authenticated nologin; exception when duplicate_object then null; end $$; do $$ begin create role service_role nologin bypassrls; exception when duplicate_object then null; end $$; create schema if not exists auth; create table if not exists auth.users (id uuid primary key); create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$; create schema if not exists storage; create table if not exists storage.buckets (id text primary key, name text not null unique, public boolean not null default false, file_size_limit bigint, allowed_mime_types text[]);");
    const migrations = readdirSync(migrationsDir).filter((name) => name.endsWith(".sql")).sort(); expect(migrations).toHaveLength(33); for (const name of migrations) await admin.query(readFileSync(resolve(migrationsDir, name), "utf8"));
    value = graph();
    await admin.query("insert into auth.users(id) values ($1) on conflict do nothing", [ACTOR]); await admin.query("insert into public.tenants(id, kind, status) values ($1, 'ORGANIZATION', 'ACTIVE')", [TENANT]); await admin.query("insert into public.tenant_memberships(id, tenant_id, principal_id, role, status) values ($1, $2, $3, 'OWNER', 'ACTIVE')", [MEMBERSHIP, TENANT, ACTOR]); await admin.query("insert into public.projects(id, name, owner_tenant_id) values ($1, 'D3 project', $2)", [PROJECT, TENANT]); await admin.query("insert into public.assets(id, project_id, name, owner_tenant_id) values ($1, $2, 'D3 asset', $3)", [ASSET, PROJECT, TENANT]); await admin.query("insert into public.asset_versions(id, asset_id, version_number, state, owner_tenant_id) values ($1, $2, 1, '{\"width\":100}'::jsonb, $3)", [VERSION, ASSET, TENANT]); await admin.query("update public.assets set current_version_id = $1 where id = $2", [VERSION, ASSET]); await admin.query("insert into public.outcome_transactions(id, owner_tenant_id, project_id, asset_id, base_version_id, raw_request, status) values ($1, $2, $3, $4, $5, 'd3 native', 'PREPARED')", [TRANSACTION, TENANT, PROJECT, ASSET, VERSION]);
    await admin.query("insert into public.outcome_blueprints(id, version, hash, previous_version_hash, status, published_at, definition) values ($1, 1, $2, null, 'PUBLISHED', now(), $3::jsonb)", [BLUEPRINT, BLUEPRINT_HASH, JSON.stringify({ id: BLUEPRINT, version: 1, previousVersionHash: null })]); await admin.query("insert into public.outcome_requirement_profiles(id, version, hash, previous_version_hash, blueprint_id, blueprint_version, blueprint_hash, policy_id, policy_hash, status, published_at, definition) values ($1, 1, $2, null, $3, 1, $4, null, null, 'PUBLISHED', now(), $5::jsonb)", [PROFILE, PROFILE_HASH, BLUEPRINT, BLUEPRINT_HASH, JSON.stringify({ schemaVersion: "outcome-requirement-profile-v0.1", id: PROFILE, version: 1, previousVersionHash: null, blueprint: { id: BLUEPRINT, version: 1, hash: BLUEPRINT_HASH }, policy: null, requirements: [{ requirementId: value.requirement.requirementId, semanticType: value.requirement.semanticType, critical: value.requirement.critical, acceptedProvenance: value.requirement.acceptedProvenance, qualificationRule: value.requirement.qualificationRule, dependencySelectors: value.requirement.dependencySelectors }] })]); await admin.query("insert into public.outcome_transaction_requirement_bindings(owner_tenant_id, outcome_transaction_id, blueprint_id, blueprint_version, blueprint_hash, requirement_profile_id, requirement_profile_version, requirement_profile_hash, policy_id, policy_hash, schema_version, binding_hash, bound_at) values ($1, $2, $3, 1, $4, $5, 1, $6, null, null, 'outcome-transaction-requirement-binding-v0.1', $7, now())", [TENANT, TRANSACTION, BLUEPRINT, BLUEPRINT_HASH, PROFILE, PROFILE_HASH, BINDING_HASH]);
    await serviceA.query("set role service_role"); await serviceB.query("set role service_role"); await serviceA.query("select public.build002_insert_signal_requirement($1::jsonb)", [JSON.stringify({ id: "ab000000-0000-4000-8000-000000000001", owner_tenant_id: TENANT, outcome_transaction_id: TRANSACTION, requirement_id: value.requirement.requirementId, semantic_type: value.requirement.semanticType, critical: value.requirement.critical, accepted_provenance: value.requirement.acceptedProvenance, qualification_rule: value.requirement.qualificationRule, dependency_selectors: value.requirement.dependencySelectors, blueprint_id: BLUEPRINT, blueprint_version: 1, blueprint_hash: BLUEPRINT_HASH, schema_version: value.requirement.definitionSchemaVersion, requirement_definition_hash: value.requirement.requirementDefinitionHash, created_at: value.requirement.createdAt })]); await serviceA.query("select public.build002_insert_signal($1::jsonb)", [JSON.stringify({ signal_id: value.signal.signalId, owner_tenant_id: TENANT, outcome_transaction_id: TRANSACTION, requirement_id: value.signal.requirementId, requirement_definition_hash: value.requirement.requirementDefinitionHash, payload: value.signal.payload, source: value.signal.source, provenance: value.signal.provenance, captured_at: value.signal.capturedAt, valid_until: value.signal.validUntil, dependency_identity: value.signal.dependency.identity, dependency_hash: value.signal.dependency.hash, schema_version: value.signal.schemaVersion, content_hash: value.signal.contentHash })]);
    const marker = await serviceA.query("select public.build002_commit_readiness_authority($1::uuid, $2::jsonb) as result", [ACTOR, JSON.stringify(value.payload)]); authorityCommitId = marker.rows[0].result.authority_commit_id;
  }, 120_000);
  afterAll(async () => { await admin?.end(); await serviceA?.end(); await serviceB?.end(); if (databaseUrl && isolatedDatabase) { const root = new Client({ connectionString: connection(databaseUrl, "postgres") }); await root.connect(); await root.query(`drop database if exists "${isolatedDatabase}" with (force)`); await root.end(); } });
  function material() { return { transaction: { ownerTenantId: TENANT, transactionId: TRANSACTION, projectId: PROJECT, assetId: ASSET, baseVersionId: VERSION, rawRequest: "d3 native" }, asset: { id: ASSET, projectId: PROJECT, ownerTenantId: TENANT, currentVersionId: VERSION }, sourceVersion: { id: VERSION, assetId: ASSET, ownerTenantId: TENANT, versionNumber: 1, parentVersionId: null, state: { width: 100 } }, binding: { ownerTenantId: TENANT, outcomeTransactionId: TRANSACTION, blueprint: { id: BLUEPRINT, version: 1, hash: BLUEPRINT_HASH }, requirementProfile: { id: PROFILE, version: 1, hash: PROFILE_HASH }, policy: { id: null, hash: null }, bindingHash: BINDING_HASH }, dependencySnapshot: value.snapshot, evaluator: value.evaluator }; }
  function request(revalidatedAt = new Date(Date.now() - 1_000).toISOString()) { return createDelegabilityAdmission({ ownerTenantId: TENANT, principalId: ACTOR, membershipId: MEMBERSHIP, authorityCommitId, outcomeTransactionId: TRANSACTION, readinessId: value.readiness.id, readinessContentHash: value.readiness.readinessContentHash, historicalDependencySnapshotHash: value.snapshot.dependencySnapshotHash, currentDependencySnapshotHash: value.snapshot.dependencySnapshotHash, evaluator: value.evaluator, revalidatedAt }, new Date().toISOString()); }
  async function admit(client: Client, admission = request()) { const result = await client.query("select public.build002_admit_delegability($1::uuid, $2::uuid, $3::uuid, $4::jsonb, $5::jsonb) as result", [ACTOR, MEMBERSHIP, authorityCommitId, JSON.stringify(admission), JSON.stringify(material())]); return result.rows[0].result as { admission_id: string }; }
  it("admits one READY/CURRENT fact and concurrent identical callers receive the same id", async () => { const [first, second] = await Promise.all([admit(serviceA), admit(serviceB)]); expect(first.admission_id).toBe(second.admission_id); expect((await admin.query("select count(*)::int as count from public.build002_delegability_admissions")).rows[0].count).toBe(1); });
  it("rejects stale server-owned transaction material and leaves no additional row", async () => { const stale = material(); stale.transaction.rawRequest = "tampered"; await expect(serviceA.query("select public.build002_admit_delegability($1::uuid, $2::uuid, $3::uuid, $4::jsonb, $5::jsonb)", [ACTOR, MEMBERSHIP, authorityCommitId, JSON.stringify(request()), JSON.stringify(stale)])).rejects.toThrow(/CURRENTNESS_NOT_CURRENT|SERIALIZED_RECHECK_FAILED/); expect((await admin.query("select count(*)::int as count from public.build002_delegability_admissions")).rows[0].count).toBe(1); });
  it("rejects direct service-role mutation of the immutable result", async () => { await expect(serviceA.query("delete from public.build002_delegability_admissions")).rejects.toThrow(); await expect(serviceA.query("update public.build002_delegability_admissions set scope='DELEGABILITY_ONLY'")).rejects.toThrow(); await expect(serviceA.query("insert into public.build002_delegability_admissions select * from public.build002_delegability_admissions limit 1")).rejects.toThrow(); });
});
