import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight } from "lucide-react";
import { OpportunityCalculator } from "@/components/opportunity-calculator";
import { Button } from "@/components/ui/button";
import { sectors } from "@/content/site";
type Props = { params: Promise<{ sector: string }> };
export function generateStaticParams() { return sectors.map(({ slug }) => ({ sector: slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { sector: slug } = await params; const sector = sectors.find((entry) => entry.slug === slug); return sector ? { title: `Demo ${sector.name}`, description: sector.flow } : {}; }
export default async function Page({ params }: Props) { const { sector: slug } = await params; const sector = sectors.find((entry) => entry.slug === slug); if (!sector) notFound(); return <main id="main-content"><section className="page-hero section"><div className="shell"><span className="tag"><span className="dot" /> Demo conceptual · Datos simulados</span><h1 className="display">Así podría continuar una experiencia de {sector.name.toLowerCase()}.</h1><p className="lead">{sector.flow}. La demo explica el recorrido; no representa un sistema productivo ni resultados reales.</p></div></section><section className="section section-rule"><div className="shell demo-flow"><div className="demo-flow-browser"><div className="browser-bar"><span /><span /><span /><small>demo.virro.app/{sector.slug}</small></div><div className="browser-content"><small>{sector.name} · cerca de ti</small><h2>Una experiencia clara desde el primer contacto.</h2><p>{sector.pain} deja de ser una colección de pasos aislados.</p><div className="demo-options">{sector.modules.map((module,index) => <button type="button" key={module}><span>0{index+1}</span>{module}<ArrowRight /></button>)}</div></div></div><aside><span className="eyebrow">Qué estás viendo</span><h2>Un flujo simulado, no una promesa.</h2><p>Los botones representan módulos posibles. La solución real se define después del diagnóstico, con datos, capacidad y responsables.</p><Button asChild variant="acid"><Link href={`/diagnostico?sector=${sector.slug}`}>Construir mi ruta <ArrowRight /></Link></Button></aside></div></section><section className="section section-rule"><div className="shell"><span className="eyebrow">Calculadora de oportunidades</span><h2 className="section-title">Prueba un escenario con tus variables.</h2><OpportunityCalculator /></div></section></main>; }
