"use client";

import { Bot, Braces, FileSearch, ShieldCheck } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function AIUnderstandingPack() {
  const { t } = useLanguage();
  const scenario = demoScenarios[2];
  return <div className="space-y-6"><PackHeader order="08" eyebrow="AI Understanding Pack" title={t("AI-understandable instruction grounded in operational context.", "Instrucción entendible para IA, basada en contexto operativo.")} description={t("Help the company be better understood by the AI it already uses by transforming intent, context and processes into understandable instructions and Context Packs.", "Ayuda a que la empresa sea mejor entendida por la IA que ya usa, transformando intención, contexto y procesos en instrucciones entendibles para IA y Context Packs.")} statement={t("Reduce AI Understanding Debt before generic output or unsupported assumptions become operational decisions.", "Reduce AI Understanding Debt antes de que outputs genéricos o supuestos sin soporte se conviertan en decisiones operativas.")} icon={<Bot size={15} />} />
    <section className="grid gap-4 lg:grid-cols-3"><SectionCard title="AI Instruction Bridge" subtitle="Intent → contexto operativo → bounded execution" icon={<Braces size={15} />}><p className="text-xs leading-5 text-[var(--muted)]">Transforms the source instruction into an AI-ready instruction with authoritative context, constraints and a clear receiver.</p></SectionCard><SectionCard title="AI Output Understanding Check" subtitle="Output Understanding Check" icon={<FileSearch size={15} />}><p className="text-xs leading-5 text-[var(--muted)]">Checks whether the output preserves user intent, business meaning and decision boundaries.</p></SectionCard><SectionCard title="AI Context Pack Viewer" subtitle="Recommended Context Pack" icon={<ShieldCheck size={15} />}><p className="text-xs leading-5 text-[var(--muted)]">Shows sources, vocabulary, prohibited assumptions and human review ownership.</p></SectionCard></section>
    <section className="grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><ScoreHero label="AI Understanding Debt" value={scenario.mockScores.aiUnderstandingDebt} detail="Higher debt indicates more missing context, implicit constraints and assumption risk." /><SectionCard title="Instruction understanding profile"><FactGrid facts={[{ label: "User intent", value: scenario.expectedAnalysis.probableIntent }, { label: "Target receiver", value: scenario.targetReceiver }, { label: "Business context needed", value: "Leadership decision, authoritative feedback source and customer taxonomy" }, { label: "Operational constraints", value: "Use supplied evidence only; separate observation from inference; human approval required" }]} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><LabeledList label="Missing context" items={scenario.expectedAnalysis.missingInformation} tone="rose" /><LabeledList label="What the AI should not assume" items={["That frequent feedback represents the full customer base", "That correlation implies root cause", "That leadership prefers a specific recommendation", "That missing source data can be invented"]} tone="amber" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Output Understanding Check"><div className="grid grid-cols-2 gap-3"><RiskMeter label="Risk of generic output" value={84} /><RiskMeter label="Risk of hallucination" value={68} /></div><div className="mt-4"><InsightList items={["Output purpose is broad", "No authoritative feedback source is named", "Actionable is undefined", "No review boundary is stated"]} tone="rose" /></div></SectionCard><SectionCard title="AI-ready instruction"><div className="rounded-xl border border-teal-400/15 bg-teal-400/[.045] p-4 text-xs leading-6 text-[var(--muted)]">Analyze the approved Q2 enterprise feedback dataset. Identify the three themes most relevant to retention decisions. For each theme, cite the evidence, distinguish observation from inference, and state data limitations. Do not infer customer intent beyond the supplied evidence. Produce a review draft for the Customer Operations Director.</div></SectionCard></section>
    <SectionCard title="Recommended Context Pack" subtitle="Contexto operativo supplied before execution"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{["Approved feedback sources", "Business vocabulary", "Decision to support", "Prohibited assumptions"].map((item) => <div key={item} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3 text-[10px] font-medium">{item}</div>)}</div></SectionCard>
  </div>;
}

function RiskMeter({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-[var(--muted)]">{label}</span><span className="text-xs font-semibold text-rose-300">{value}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[var(--ring-track)]"><div className="h-full rounded-full bg-rose-400" style={{ width: `${value}%` }} /></div></div>; }
