"use client";

import { Bot, Braces, FileSearch, ShieldCheck } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function AIUnderstandingPack() {
  const { locale, t } = useLanguage();
  const localized = <T,>(english: T, spanish: T) => locale === "es" ? spanish : english;
  const scenario = demoScenarios[2];
  return <div className="space-y-6"><PackHeader order="08" eyebrow="AI Understanding Pack" title={t("AI-understandable instruction grounded in operational context.", "Instrucción entendible para IA, basada en contexto operativo.")} description={t("Help the company be better understood by the AI it already uses by transforming intent, context and processes into understandable instructions and Context Packs.", "Ayuda a que la empresa sea mejor entendida por la IA que ya usa, transformando intención, contexto y procesos en instrucciones entendibles para IA y Context Packs.")} statement={t("Reduce AI Understanding Debt before generic output or unsupported assumptions become operational decisions.", "Reduce AI Understanding Debt antes de que outputs genéricos o supuestos sin soporte se conviertan en decisiones operativas.")} icon={<Bot size={15} />} />
    <section className="grid gap-4 lg:grid-cols-3"><SectionCard title={t("AI Instruction Bridge", "Puente de instrucciones entendibles para IA")} subtitle={t("Intent → operational context → bounded execution", "Intención → contexto operativo → ejecución acotada")} icon={<Braces size={15} />}><p className="text-xs leading-5 text-[var(--muted)]">{t("Prepares an AI-ready instruction with authoritative context, constraints and a clear receiver.", "Prepara una instrucción entendible para IA con contexto autorizado, restricciones y un receptor claro.")}</p></SectionCard><SectionCard title={t("AI Output Understanding Check", "Revisión de entendimiento del output")} subtitle={t("Output Understanding Check", "Control del significado recibido")} icon={<FileSearch size={15} />}><p className="text-xs leading-5 text-[var(--muted)]">{t("Checks whether the output preserves user intent, business meaning and decision boundaries.", "Valida si el output conserva la intención del usuario, el significado de negocio y los límites de decisión.")}</p></SectionCard><SectionCard title={t("AI Context Pack Viewer", "Visor del Context Pack para IA")} subtitle={t("Recommended Context Pack", "Context Pack recomendado")} icon={<ShieldCheck size={15} />}><p className="text-xs leading-5 text-[var(--muted)]">{t("Shows sources, vocabulary, prohibited assumptions and human review ownership.", "Muestra fuentes, vocabulario, supuestos prohibidos y responsabilidad de revisión humana.")}</p></SectionCard></section>
    <section className="grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><ScoreHero label="AI Understanding Debt" value={scenario.mockScores.aiUnderstandingDebt} detail={t("Higher debt indicates more missing context, implicit constraints and assumption risk.", "Una deuda mayor indica más contexto faltante, restricciones implícitas y riesgo de supuestos.")} /><SectionCard title={t("Instruction understanding profile", "Perfil de entendimiento de la instrucción")}><FactGrid facts={[{ label: t("User intent", "Intención del usuario"), value: t(scenario.expectedAnalysis.probableIntent, "Convertir feedback aprobado en evidencia útil para una decisión de retención.") }, { label: t("Target receiver", "Receptor destino"), value: t(scenario.targetReceiver, "Sistema de IA y responsable de operaciones") }, { label: t("Business context needed", "Contexto de negocio necesario"), value: t("Leadership decision, authoritative feedback source and customer taxonomy", "Decisión de liderazgo, fuente autorizada de feedback y taxonomía de clientes") }, { label: t("Operational constraints", "Restricciones operativas"), value: t("Use supplied evidence only; separate observation from inference; human approval required", "Usar solo la evidencia suministrada; separar observación de inferencia; aprobación humana obligatoria") }]} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><LabeledList label={t("Missing context", "Contexto faltante")} items={localized(scenario.expectedAnalysis.missingInformation, ["Fuente de feedback autorizada", "Decisión de negocio que debe respaldar", "Criterio para considerar un hallazgo accionable"])} tone="rose" /><LabeledList label={t("What the AI should not assume", "Lo que la IA no debe asumir")} items={localized(["That frequent feedback represents the full customer base", "That correlation implies root cause", "That leadership prefers a specific recommendation", "That missing source data can be invented"], ["Que el feedback frecuente representa a toda la base de clientes", "Que la correlación implica causa raíz", "Que liderazgo prefiere una recomendación específica", "Que los datos faltantes pueden inventarse"])} tone="amber" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title={t("Output Understanding Check", "Revisión de entendimiento del output")}><div className="grid grid-cols-2 gap-3"><RiskMeter label={t("Risk of generic output", "Riesgo de output genérico")} value={84} /><RiskMeter label={t("Risk of hallucination", "Riesgo de alucinación")} value={68} /></div><div className="mt-4"><InsightList items={localized(["Output purpose is broad", "No authoritative feedback source is named", "Actionable is undefined", "No review boundary is stated"], ["El propósito del output es amplio", "No se indica una fuente autorizada", "Accionable no está definido", "No existe un límite de revisión"])} tone="rose" /></div></SectionCard><SectionCard title={t("AI-ready instruction", "Instrucción entendible para IA")}><div className="rounded-xl border border-teal-400/15 bg-teal-400/[.045] p-4 text-xs leading-6 text-[var(--muted)]">{t("Analyze the approved Q2 enterprise feedback dataset. Identify the three themes most relevant to retention decisions. For each theme, cite the evidence, distinguish observation from inference, and state data limitations. Do not infer customer intent beyond the supplied evidence. Produce a review draft for the Customer Operations Director.", "Analiza el dataset aprobado de feedback enterprise del Q2. Identifica los tres temas más relevantes para decisiones de retención. Para cada tema, cita la evidencia, distingue observación de inferencia y declara las limitaciones de los datos. No infieras intención del cliente más allá de la evidencia suministrada. Produce un borrador para revisión del Director de Operaciones de Cliente.")}</div></SectionCard></section>
    <SectionCard title={t("Recommended Context Pack", "Context Pack recomendado")} subtitle={t("Operational context supplied before execution", "Contexto operativo suministrado antes de ejecutar")}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{localized(["Approved feedback sources", "Business vocabulary", "Decision to support", "Prohibited assumptions"], ["Fuentes de feedback aprobadas", "Vocabulario de negocio", "Decisión a respaldar", "Supuestos prohibidos"]).map((item) => <div key={item} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3 text-[10px] font-medium">{item}</div>)}</div></SectionCard>
  </div>;
}

function RiskMeter({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-[var(--muted)]">{label}</span><span className="text-xs font-semibold text-rose-300">{value}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[var(--ring-track)]"><div className="h-full rounded-full bg-rose-400" style={{ width: `${value}%` }} /></div></div>; }
