import { Boxes, BriefcaseBusiness, SearchCheck, ShieldAlert } from "lucide-react";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function ConsultingDeliveryPack() {
  const scenario = demoScenarios[5];
  return <div className="space-y-6"><PackHeader order="12" eyebrow="Consulting Delivery Pack" title="Client meaning preserved from discovery to execution." description="For consultancies, software factories, product agencies and implementation partners coordinating commercial intent, discovery and delivery." statement="Virro reduce la pérdida de entendimiento entre lo que el cliente quiso decir, lo que la consultora interpretó y lo que el equipo ejecutó." icon={<Boxes size={15} />} />
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label="Consulting Delivery Readiness Score" value={scenario.mockScores.handoffReadiness} detail="Estimated alignment between client intent, consulting interpretation and delivery execution." /><SectionCard title="Client Understanding Pack" icon={<BriefcaseBusiness size={15} />}><FactGrid facts={[{ label: "Client intent", value: scenario.expectedAnalysis.probableIntent }, { label: "Decision to support", value: "Approve a modernization path and investment scope" }, { label: "Target receiver", value: scenario.targetReceiver }, { label: "Evidence status", value: "Discovery evidence not yet attached" }]} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Scope Meaning Loss Review" icon={<SearchCheck size={15} />}><div className="space-y-3">{[{l:"Client said",v:"Modern customer portal with main integrations"},{l:"Consultancy inferred",v:"Experience redesign plus integration assessment"},{l:"Delivery may execute",v:"Full portal rebuild unless exclusions are explicit"}].map((row) => <div key={row.l} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-[9px] uppercase tracking-[.1em] text-[var(--subtle)]">{row.l}</p><p className="mt-1.5 text-xs">{row.v}</p></div>)}</div></SectionCard><SectionCard title="Delivery Handoff Readiness"><FactGrid facts={[{label:"Scope boundary",value:"Not ready"},{label:"Integration inventory",value:"Missing"},{label:"Decision owner",value:"Client sponsor assumed"},{label:"Success evidence",value:"Undefined"}]} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-3"><LabeledList label="Client Context Gaps" items={scenario.expectedAnalysis.missingInformation} tone="rose" /><LabeledList label="Delivery Risks" items={scenario.expectedAnalysis.risks} tone="amber" /><LabeledList label="Questions for Client" items={["Which decision must discovery enable?", "Which systems are in and out of scope?", "What outcome justifies investment?", "Who approves scope changes?"]} /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Consultant Onboarding Pack"><InsightList items={["Client business model and portal audience", "Commercial commitments already made", "Known integration and regulatory constraints", "Stakeholder map and decision rights", "Evidence and unresolved assumptions"]} /></SectionCard><SectionCard title="Delivery interpretation control" icon={<ShieldAlert size={15} />}><p className="text-xs leading-6 text-[var(--muted)]">Every material interpretation is linked to client evidence, marked as confirmed or assumed, and assigned to a decision owner before it becomes delivery scope.</p></SectionCard></section>
  </div>;
}
