"use client";

import { Boxes, BriefcaseBusiness, SearchCheck, ShieldAlert } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function ConsultingDeliveryPack() {
  const { locale, t } = useLanguage(); const es = locale === "es"; const scenario = demoScenarios[5];
  const scopeRows = es ? [{ l: "El cliente dijo", v: "Portal moderno para clientes con las integraciones principales" }, { l: "La consultora interpretó", v: "Rediseño de experiencia más evaluación de integraciones" }, { l: "El equipo podría ejecutar", v: "Reconstrucción completa del portal si no se explicitan exclusiones" }] : [{ l: "Client said", v: "Modern customer portal with main integrations" }, { l: "Consultancy inferred", v: "Experience redesign plus integration assessment" }, { l: "Delivery may execute", v: "Full portal rebuild unless exclusions are explicit" }];
  const questions = es ? ["¿Qué decisión debe habilitar discovery?", "¿Qué sistemas están dentro y fuera del alcance?", "¿Qué resultado justifica la inversión?", "¿Quién aprueba cambios de alcance?"] : ["Which decision must discovery enable?", "Which systems are in and out of scope?", "What outcome justifies investment?", "Who approves scope changes?"];
  const onboarding = es ? ["Modelo de negocio y audiencia del portal", "Compromisos comerciales ya adquiridos", "Restricciones conocidas de integración y regulación", "Mapa de stakeholders y derechos de decisión", "Evidencia y supuestos sin resolver"] : ["Client business model and portal audience", "Commercial commitments already made", "Known integration and regulatory constraints", "Stakeholder map and decision rights", "Evidence and unresolved assumptions"];
  return <div className="space-y-6"><PackHeader order="12" eyebrow="Consulting Delivery Pack" title={t("Client meaning preserved from discovery to project execution.", "Significado del cliente preservado desde discovery hasta la ejecución del proyecto.")} description={t("For consultancies, software factories, product agencies and implementation partners coordinating commercial intent, discovery and delivery.", "Para consultoras, software factories, agencias de producto e implementadoras que coordinan intención comercial, discovery y delivery.")} statement={t("Virro reduces meaning loss between what the client meant, what the consultancy interpreted and what the team executed.", "Virro reduce la pérdida de significado entre lo que el cliente quiso decir, lo que la consultora interpretó y lo que el equipo ejecutó.")} icon={<Boxes size={15} />} />
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label="Consulting Delivery Readiness Score" value={scenario.mockScores.handoffReadiness} detail={t("Estimated alignment between client intent, consulting interpretation and delivery execution.", "Alineación estimada entre intención del cliente, interpretación de la consultora y ejecución del equipo.")} /><SectionCard title="Client Understanding Pack" icon={<BriefcaseBusiness size={15} />}><FactGrid facts={[{ label: "Client intent", value: scenario.expectedAnalysis.probableIntent }, { label: "Decision to support", value: t("Approve a modernization path and investment scope", "Aprobar una ruta de modernización y alcance de inversión") }, { label: "Target receiver", value: scenario.targetReceiver }, { label: "Evidence status", value: t("Discovery evidence not yet attached", "La evidencia de discovery aún no está adjunta") }]} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Scope Meaning Loss Review" icon={<SearchCheck size={15} />}><div className="space-y-3">{scopeRows.map((row) => <div key={row.l} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-[9px] uppercase tracking-[.1em] text-[var(--subtle)]">{row.l}</p><p className="mt-1.5 text-xs">{row.v}</p></div>)}</div></SectionCard><SectionCard title="Delivery Handoff Readiness"><FactGrid facts={[{ label: "Scope boundary", value: "Not ready" }, { label: "Integration inventory", value: "Missing" }, { label: "Decision owner", value: "Client sponsor assumed" }, { label: "Success evidence", value: "Undefined" }]} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-3"><LabeledList label="Client Context Gaps" items={scenario.expectedAnalysis.missingInformation} tone="rose" /><LabeledList label="Delivery Risks" items={scenario.expectedAnalysis.risks} tone="amber" /><LabeledList label="Questions for Client" items={questions} /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Consultant Onboarding Pack"><InsightList items={onboarding} /></SectionCard><SectionCard title="Delivery interpretation control" icon={<ShieldAlert size={15} />}><p className="text-xs leading-6 text-[var(--muted)]">{t("Every material interpretation is linked to client evidence, marked as confirmed or assumed, and assigned to a decision owner before it becomes delivery scope.", "Cada interpretación material se vincula con evidencia del cliente, se marca como confirmada o asumida y se asigna a un responsable de decisión antes de convertirse en alcance de entrega.")}</p></SectionCard></section>
  </div>;
}
