"use client";

import { FileCheck2, Palette, Workflow } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { EvidenceSection } from "@/components/evidence/evidence-section";
import { LimitationsPanel } from "@/components/evidence/limitations-panel";
import { OutcomePanel } from "@/components/evidence/outcome-panel";
import { FactGrid, InsightList, LabeledList, PackHeader, SectionCard } from "./shared";

export function DesignDeliveryPack() {
  const { locale, t } = useLanguage();
  const es = locale === "es";
  const missing = es ? ["El copy final no tiene aprobación trazable", "La variante mobile no aparece en el inventario", "Dos comentarios describen comportamientos distintos", "No se declara cuál archivo es la versión vigente"] : ["Final copy has no traceable approval", "The mobile variant is absent from the inventory", "Two comments describe different behaviors", "The current source file is not identified"];
  const questions = es ? ["¿Qué versión debe implementar frontend?", "¿Quién aprueba copy y comportamiento?", "¿Qué variantes y estados forman parte de la entrega?", "¿Qué evidencia confirma que el handoff fue aceptado?"] : ["Which version should frontend implement?", "Who approves copy and behavior?", "Which variants and states belong to the delivery?", "What evidence confirms handoff acceptance?"];
  return <div className="space-y-6"><PackHeader order="04" eyebrow="Design Delivery" title={t("Design intent that the next receiver can implement.", "Intención de diseño que el siguiente receptor puede implementar.")} description={t("A controlled demo of how Virro structures briefs, versions, assets, restrictions and approval evidence before a design handoff.", "Una demo controlada de cómo Virro estructura briefs, versiones, assets, restricciones y evidencia de aprobación antes de un handoff de diseño.")} statement={t("Simulated surface · no productive Figma connector is claimed.", "Superficie simulada · no se afirma un conector productivo con Figma.")} icon={<Palette size={15} />} />
    <section className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><SectionCard title={t("Active design transfer", "Transferencia de diseño activa")} subtitle={t("Simulated scenario", "Escenario simulado")} icon={<Workflow size={15} />}><FactGrid facts={[{ label: t("Origin", "Origen"), value: "Product Design" }, { label: t("Receiver", "Receptor"), value: "Frontend Engineering" }, { label: t("Expected action", "Acción esperada"), value: t("Implement the approved checkout experience", "Implementar la experiencia aprobada de checkout") }, { label: t("Signal sufficiency", "Suficiencia de señal"), value: t("Needs context", "Necesita contexto") }]} /><div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--input)] p-4 text-xs leading-6 text-[var(--muted)]">{t("Use the latest checkout design. Copy is almost approved and mobile should behave like desktop. Please ship this sprint.", "Usa el último diseño de checkout. El copy está casi aprobado y mobile debe comportarse como desktop. Por favor entrégalo este sprint.")}</div></SectionCard><EvidenceSection items={[{ id: "design-brief", classification: "observed", title: t("Brief supplied", "Brief suministrado"), detail: t("One written handoff exists for the checkout change.", "Existe un handoff escrito para el cambio de checkout.") }, { id: "design-version", classification: "insufficient", title: t("Current version", "Versión vigente"), detail: t("The available input does not identify a canonical file or approved frame.", "El input disponible no identifica un archivo canónico ni un frame aprobado.") }, { id: "design-approval", classification: "inferred", title: t("Approval state", "Estado de aprobación"), detail: t("“Almost approved” suggests an unresolved decision; it is not confirmation.", "“Casi aprobado” sugiere una decisión pendiente; no es confirmación.") }]} /></section>
    <section className="grid gap-4 lg:grid-cols-2"><LabeledList label={t("Missing context", "Contexto faltante")} items={missing} tone="rose" /><SectionCard title={t("Critical questions", "Preguntas críticas")} icon={<FileCheck2 size={15} />}><InsightList items={questions} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><LimitationsPanel limitations={es ? ["No se inspeccionó un archivo Figma real.", "No hay historial de versiones ni comentarios disponible.", "El resultado es una demostración direccional, no una auditoría del cliente."] : ["No real Figma file was inspected.", "No version history or comments are available.", "The result is a directional demonstration, not a client audit."]} /><OutcomePanel outcomes={es ? ["Frontend identifica una única versión vigente.", "Variantes y estados tienen ownership explícito.", "La aceptación del handoff queda registrada por el receptor."] : ["Frontend identifies one current version.", "Variants and states have explicit ownership.", "Handoff acceptance is recorded by the receiver."]} /></section>
  </div>;
}
