"use client";

import { CalendarRange, Map, UserRoundCheck, UsersRound } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { roleCards } from "@/lib/data/seed";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function OnboardingPack() {
  const { locale, t } = useLanguage(); const es = locale === "es"; const scenario = demoScenarios[4]; const role = roleCards.find((card) => card.roleName === "Platform Architect") ?? roleCards[1];
  const phases = es ? [{ p: "Días 1–7", t: "Contexto del sistema", d: "Límites, mapa de servicios, vocabulario, accesos e historial de decisiones." }, { p: "Días 8–15", t: "Rutas operativas", d: "Observar un release, incidente y decisión de arquitectura con responsables definidos." }, { p: "Días 16–30", t: "Evidencia de readiness", d: "Entregar un cambio pequeño, explicar riesgos y completar la transferencia con revisión." }] : [{ p: "Days 1–7", t: "System context", d: "Boundaries, service map, vocabulary, access and decision history." }, { p: "Days 8–15", t: "Operational paths", d: "Observe a release, incident and architecture decision with accountable owners." }, { p: "Days 16–30", t: "Readiness evidence", d: "Deliver a small change, explain risks and complete the handoff with review." }];
  const misunderstandings = es ? ["Leer la wiki no significa entender el contexto del sistema", "Acceso al repositorio no significa readiness de entrega", "Tomar un ticket no demuestra entender los límites de decisión"] : ["Reading the wiki means system context is understood", "Repository access means delivery readiness", "Taking a ticket proves decision-boundary understanding"];
  const questions = es ? ["¿Qué decisiones puede tomar este rol de forma independiente?", "¿Qué cambio en producción es seguro como primer resultado?", "¿Qué decisiones de arquitectura no están documentadas?", "¿Quién valida readiness y con qué evidencia?"] : ["Which decisions can this role make independently?", "What production change is safe as a first outcome?", "Which architecture decisions are undocumented?", "Who validates readiness and with what evidence?"];
  const required = es ? ["Mapa del sistema y dependencias", "Ownership de servicios y rutas de escalamiento", "Flujo de desarrollo y release", "Restricciones de calidad, seguridad y confiabilidad", "Decisiones recientes y su justificación"] : ["System and dependency map", "Service ownership and escalation paths", "Development and release workflow", "Quality, security and reliability constraints", "Recent decisions and why they were made"];
  return <div className="space-y-6"><PackHeader order="11" eyebrow="Onboarding & Knowledge Transfer Pack" title={t("Operational understanding for a new member, consultant or provider.", "Entendimiento operativo para un nuevo miembro, consultora o proveedor.")} description={t("Turn dispersed internal knowledge into operational understanding for new members, consultants or providers.", "Convierte conocimiento interno disperso en entendimiento operativo para nuevos miembros, consultoras o proveedores.")} statement={t("Operational understanding transfer—not traditional training.", "Transferencia de entendimiento operativo, no capacitación tradicional.")} icon={<UsersRound size={15} />} />
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label="Onboarding Readiness Score" value={scenario.mockScores.onboardingReadiness} detail={t("Measures whether a new member can act safely—not whether content was consumed.", "Mide si un nuevo miembro puede actuar de forma segura, no si consumió contenido.")} /><SectionCard title="Role Onboarding Card" icon={<UserRoundCheck size={15} />}><FactGrid facts={[{ label: "Role", value: t("New Platform Developer", "Nuevo developer de plataforma") }, { label: "Operational outcome", value: t("Make one safe production change with review", "Realizar un cambio seguro en producción con revisión") }, { label: "Needs to understand", value: es ? "Límites del sistema, contratos de consumidores y condiciones de fallo y rollback" : role.needsToUnderstand.join(", ") }, { label: "Expected outputs", value: es ? "Mapa de entendimiento técnico y registro de decisión de migración" : role.expectedOutputs.join(", ") }]} /></SectionCard></section>
    <SectionCard title="First 30 Days Understanding Plan" icon={<CalendarRange size={15} />}><div className="grid gap-3 md:grid-cols-3">{phases.map((phase) => <div key={phase.p} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.1em] text-teal-300">{phase.p}</p><p className="mt-2 text-xs font-medium">{phase.t}</p><p className="mt-2 text-[10px] leading-4 text-[var(--muted)]">{phase.d}</p></div>)}</div></SectionCard>
    <section className="grid gap-4 lg:grid-cols-2"><LabeledList label="Knowledge Transfer Gaps" items={scenario.expectedAnalysis.missingInformation} tone="rose" /><LabeledList label="Common Misunderstandings" items={misunderstandings} tone="amber" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Critical Questions Map" icon={<Map size={15} />}><InsightList items={questions} /></SectionCard><SectionCard title="Required Context"><InsightList items={required} /></SectionCard></section>
    <SectionCard title="AI Context Pack for New Member"><div className="rounded-xl border border-teal-400/15 bg-teal-400/[.045] p-4"><p className="text-xs font-medium">{t("Platform role companion context", "Contexto complementario del rol de plataforma")}</p><p className="mt-2 text-[11px] leading-5 text-[var(--muted)]">{t("Approved system vocabulary, architecture boundaries, owner directory, decision records, runbook links and explicit instruction that the AI must not infer production access or approval authority.", "Vocabulario aprobado, límites de arquitectura, directorio de responsables, registros de decisión, runbooks y una instrucción explícita para que la IA no infiera acceso a producción ni autoridad de aprobación.")}</p></div></SectionCard>
  </div>;
}
