"use client";

import { CalendarRange, Map, UserRoundCheck, UsersRound } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { roleCards } from "@/lib/data/seed";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function OnboardingPack() {
  const { t } = useLanguage();
  const scenario = demoScenarios[4];
  const role = roleCards.find((card) => card.roleName === "Platform Architect") ?? roleCards[1];
  return <div className="space-y-6"><PackHeader order="11" eyebrow="Onboarding & Knowledge Transfer Pack" title={t("Operational understanding for a new member, consultant or provider.", "Entendimiento operativo para un nuevo miembro, consultora o proveedor.")} description={t("Turn dispersed internal knowledge into operational understanding for new members, consultants or providers.", "Convierte conocimiento interno disperso en entendimiento operativo para nuevos miembros, consultoras o proveedores.")} statement={t("Operational understanding transfer—not traditional training.", "Transferencia de entendimiento operativo, no capacitación tradicional.")} icon={<UsersRound size={15} />} />
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label="Onboarding Readiness Score" value={scenario.mockScores.onboardingReadiness} detail="Measures whether a new member can act safely—not whether content was consumed." /><SectionCard title="Role Onboarding Card" icon={<UserRoundCheck size={15} />}><FactGrid facts={[{ label: "Role", value: "New Platform Developer" }, { label: "Operational outcome", value: "Make one safe production change with review" }, { label: "Needs to understand", value: role.needsToUnderstand.join(", ") }, { label: "Expected outputs", value: role.expectedOutputs.join(", ") }]} /></SectionCard></section>
    <SectionCard title="First 30 Days Understanding Plan" icon={<CalendarRange size={15} />}><div className="grid gap-3 md:grid-cols-3">{[{p:"Days 1–7",t:"System context",d:"Boundaries, service map, vocabulary, access and decision history."},{p:"Days 8–15",t:"Operational paths",d:"Observe a release, incident and architecture decision with accountable owners."},{p:"Days 16–30",t:"Readiness evidence",d:"Deliver a small change, explain risks and complete the handoff with review."}].map((phase) => <div key={phase.p} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.1em] text-teal-300">{phase.p}</p><p className="mt-2 text-xs font-medium">{phase.t}</p><p className="mt-2 text-[10px] leading-4 text-[var(--muted)]">{phase.d}</p></div>)}</div></SectionCard>
    <section className="grid gap-4 lg:grid-cols-2"><LabeledList label="Knowledge Transfer Gaps" items={scenario.expectedAnalysis.missingInformation} tone="rose" /><LabeledList label="Common Misunderstandings" items={["Reading the wiki means system context is understood", "Repository access means delivery readiness", "Taking a ticket proves decision-boundary understanding"]} tone="amber" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Critical Questions Map" icon={<Map size={15} />}><InsightList items={["Which decisions can this role make independently?", "What production change is safe as a first outcome?", "Which architecture decisions are undocumented?", "Who validates readiness and with what evidence?"]} /></SectionCard><SectionCard title="Required Context"><InsightList items={["System and dependency map", "Service ownership and escalation paths", "Development and release workflow", "Quality, security and reliability constraints", "Recent decisions and why they were made"]} /></SectionCard></section>
    <SectionCard title="AI Context Pack for New Member"><div className="rounded-xl border border-teal-400/15 bg-teal-400/[.045] p-4"><p className="text-xs font-medium">Platform role companion context</p><p className="mt-2 text-[11px] leading-5 text-[var(--muted)]">Approved system vocabulary, architecture boundaries, owner directory, decision records, runbook links and explicit instruction that the AI must not infer production access or approval authority.</p></div></SectionCard>
  </div>;
}
