"use client";

import { ArrowRight, GitBranch, Network, Repeat2 } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function ProcessUnderstandingPack() {
  const { locale, t } = useLanguage(); const es = locale === "es"; const scenario = demoScenarios[3];
  const steps = es ? ["Problema grave detectado", "Decisión de severidad", "Responsable del servicio acepta", "Respuesta al cliente", "Evidencia de cierre"] : ["Severe issue detected", "Severity decision", "Service owner accepts", "Customer response", "Closure evidence"];
  const decisions = es ? ["¿El problema cumple criterios de severidad uno?", "¿Qué equipo debe aceptar ownership?", "¿Cuándo inicia la comunicación a liderazgo?"] : ["Does the issue meet severity-one criteria?", "Which service team must accept ownership?", "When does leadership communication begin?"];
  const exceptions = es ? ["Escalamiento fuera de horario", "Múltiples servicios afectados", "Ningún responsable responde", "Impacto al cliente incierto"] : ["After-hours escalation", "Multiple services affected", "No service owner responds", "Customer impact is uncertain"];
  const rules = es ? ["Un solo Incident Commander a la vez", "Las decisiones de severidad incluyen evidencia", "La aceptación de ownership queda registrada", "El cierre requiere seguimiento al cliente"] : ["One incident commander at a time", "Severity decisions include evidence", "Ownership acceptance is recorded", "Closure requires customer follow-up"];
  return <div className="space-y-6"><PackHeader order="10" eyebrow="Process Understanding Pack" title={t("Internal process as transferable operational understanding.", "Proceso interno como entendimiento operativo transferible.")} description={t("Turn internal processes into guides that other areas, clients, providers, consultants or AI systems can understand.", "Convierte procesos internos en guías entendibles para otras áreas, clientes, proveedores, consultoras o sistemas de IA.")} statement={t("This is operational understanding transfer—not generic process documentation.", "Esto es transferencia de entendimiento operativo, no documentación genérica de procesos.")} icon={<Network size={15} />} />
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label="Process Understanding Readiness" value={scenario.mockScores.automationReadiness} detail={t("Readiness is limited by unclear trigger, decision authority and exception routing.", "El readiness está limitado por un disparador ambiguo, autoridad de decisión y ruta de excepciones.")} /><SectionCard title="Process operating model"><FactGrid facts={[{ label: "Process objective", value: t("Escalate severe customer issues consistently and visibly", "Escalar problemas graves de clientes de forma consistente y visible") }, { label: "Trigger", value: t("Customer issue meets severity criteria — criteria currently missing", "El problema cumple criterios de severidad — los criterios aún faltan") }, { label: "Owner", value: "Support Operations Lead" }, { label: "Receiver", value: t("Incident Commander and responsible service team", "Incident Commander y equipo responsable del servicio") }, { label: "Inputs", value: t("Customer evidence, severity signals, affected service", "Evidencia del cliente, señales de severidad y servicio afectado") }, { label: "Outputs", value: t("Accepted incident, customer response and closure record", "Incidente aceptado, respuesta al cliente y registro de cierre") }]} /></SectionCard></section>
    <SectionCard title="Process map" subtitle="Operational meaning across the standard path" icon={<Repeat2 size={15} />}><div className="overflow-x-auto"><div className="flex min-w-[760px] items-center gap-2">{steps.map((step, index) => <div key={step} className="contents"><div className={`flex-1 rounded-xl border p-3 ${index === 1 ? "border-amber-400/25 bg-amber-400/[.06]" : "border-[var(--border)] bg-[var(--panel-soft)]"}`}><p className="text-[9px] text-[var(--subtle)]">0{index + 1}</p><p className="mt-1 text-[10px] font-medium">{step}</p>{index === 1 && <p className="mt-1 text-[9px] text-amber-300">{t("Decision gap", "Brecha de decisión")}</p>}</div>{index < steps.length - 1 && <ArrowRight size={14} className="shrink-0 text-[var(--subtle)]" />}</div>)}</div></div></SectionCard>
    <section className="grid gap-4 lg:grid-cols-3"><LabeledList label="Decisions" items={decisions} /><LabeledList label="Exceptions" items={exceptions} tone="amber" /><LabeledList label="Operational rules" items={rules} /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Risks" icon={<GitBranch size={15} />}><InsightList items={scenario.expectedAnalysis.risks} tone="rose" /></SectionCard><SectionCard title="Missing process context"><InsightList items={scenario.expectedAnalysis.missingInformation} tone="amber" /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Version for another team"><p className="text-xs leading-6 text-[var(--muted)]">{t("When a customer issue matches the approved severity criteria, Support opens the incident record and names the Incident Commander. The responsible service team must accept or redirect ownership within 15 minutes. Customer Operations owns the response cadence until closure.", "Cuando un problema cumple los criterios aprobados de severidad, Soporte abre el incidente y nombra al Incident Commander. El equipo responsable debe aceptar o redirigir ownership en 15 minutos. Operaciones de Cliente controla la cadencia de respuesta hasta el cierre.")}</p></SectionCard><SectionCard title="Version for AI"><p className="text-xs leading-6 text-[var(--muted)]">{t("Classify only against the supplied severity matrix. Recommend the service owner from the service catalog. Do not declare severity or assign ownership autonomously. Escalate ambiguous cases to the Support Operations Lead.", "Clasifica únicamente contra la matriz de severidad suministrada. Recomienda responsable desde el catálogo de servicios. No declares severidad ni asignes ownership de forma autónoma. Escala casos ambiguos al líder de Operaciones de Soporte.")}</p></SectionCard></section>
  </div>;
}
