import { ArrowRight, GitBranch, Network, Repeat2 } from "lucide-react";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function ProcessUnderstandingPack() {
  const scenario = demoScenarios[3];
  const steps = ["Severe issue detected", "Severity decision", "Service owner accepts", "Customer response", "Closure evidence"];
  return <div className="space-y-6"><PackHeader order="10" eyebrow="Process Understanding Pack" title="Internal process as transferable operational understanding." description="Expose the conditions, decisions and handoffs another team or AI needs to execute the process consistently." statement="This is transferencia de entendimiento operativo—not generic process documentation." icon={<Network size={15} />} />
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label="Process Understanding Readiness" value={scenario.mockScores.automationReadiness} detail="Readiness is limited by unclear trigger, decision authority and exception routing." /><SectionCard title="Process operating model"><FactGrid facts={[{ label: "Process objective", value: "Escalate severe customer issues consistently and visibly" }, { label: "Trigger", value: "Customer issue meets severity criteria — criteria currently missing" }, { label: "Owner", value: "Support Operations Lead" }, { label: "Receiver", value: "Incident Commander and responsible service team" }, { label: "Inputs", value: "Customer evidence, severity signals, affected service" }, { label: "Outputs", value: "Accepted incident, customer response and closure record" }]} /></SectionCard></section>
    <SectionCard title="Process map" subtitle="Operational meaning across the standard path" icon={<Repeat2 size={15} />}><div className="overflow-x-auto"><div className="flex min-w-[760px] items-center gap-2">{steps.map((step, index) => <div key={step} className="contents"><div className={`flex-1 rounded-xl border p-3 ${index === 1 ? "border-amber-400/25 bg-amber-400/[.06]" : "border-[var(--border)] bg-[var(--panel-soft)]"}`}><p className="text-[9px] text-[var(--subtle)]">0{index + 1}</p><p className="mt-1 text-[10px] font-medium">{step}</p>{index === 1 && <p className="mt-1 text-[9px] text-amber-300">Decision gap</p>}</div>{index < steps.length - 1 && <ArrowRight size={14} className="shrink-0 text-[var(--subtle)]" />}</div>)}</div></div></SectionCard>
    <section className="grid gap-4 lg:grid-cols-3"><LabeledList label="Decisions" items={["Does the issue meet severity-one criteria?", "Which service team must accept ownership?", "When does leadership communication begin?"]} /><LabeledList label="Exceptions" items={["After-hours escalation", "Multiple services affected", "No service owner responds", "Customer impact is uncertain"]} tone="amber" /><LabeledList label="Operational rules" items={["One incident commander at a time", "Severity decisions include evidence", "Ownership acceptance is recorded", "Closure requires customer follow-up"]} /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Risks" icon={<GitBranch size={15} />}><InsightList items={scenario.expectedAnalysis.risks} tone="rose" /></SectionCard><SectionCard title="Missing process context"><InsightList items={scenario.expectedAnalysis.missingInformation} tone="amber" /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Version for another team"><p className="text-xs leading-6 text-[var(--muted)]">When a customer issue matches the approved severity criteria, Support opens the incident record and names the Incident Commander. The responsible service team must accept or redirect ownership within 15 minutes. Customer Operations owns the response cadence until closure.</p></SectionCard><SectionCard title="Version for AI"><p className="text-xs leading-6 text-[var(--muted)]">Classify only against the supplied severity matrix. Recommend the service owner from the service catalog. Do not declare severity or assign ownership autonomously. Escalate ambiguous cases to the Support Operations Lead.</p></SectionCard></section>
  </div>;
}
