"use client";

import { CircleCheckBig, PackageCheck, ShieldAlert, Sparkles } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { events } from "@/lib/data/seed";
import { FactGrid, InsightList, LabeledList, OutputChips, PackHeader, ScoreHero, SectionCard } from "./shared";

export function ProductDeliveryPack() {
  const { t } = useLanguage();
  const story = demoScenarios[0];
  const productEvent = events.find((event) => event.packType === "product-delivery")!;
  const productRisks = ["Enterprise buyer is not defined", "“Better checkout” has no measurable boundary"];
  const developmentRisks = ["Scope may expand during implementation", "Session and payment-state dependencies are implicit"];
  const qaRisks = ["Completion cannot be tested objectively", "Error and recovery paths are absent"];
  return <div className="space-y-6"><PackHeader order="07" eyebrow="Product Delivery Pack" title={t("Product intent that engineering and QA can execute.", "Intención de producto que desarrollo y QA pueden ejecutar.")} description={t("Turn ambiguous information into stories, criteria, QA matrices, bugs, recaps and handoffs for product, design, development, QA and scrum.", "Convierte información ambigua en historias, criterios, matrices QA, bugs, recaps y handoffs claros para producto, diseño, desarrollo, QA y scrum.")} statement={t("Convert ambiguous information into operational understanding for execution.", "Convertir información ambigua en entendimiento operativo para ejecución.")} icon={<PackageCheck size={15} />} />
    <SectionCard title="Product Understanding Events" subtitle="Operational intake across the delivery lifecycle"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-6">{[["User Stories","3","2 at risk"],["Bugs","4","1 blocked"],["QA","2","Context gap"],["Acceptance Criteria","5","3 ready"],["Scrum","3","1 decision"],["Product Handoffs","2","1 at risk"]].map(([type,count,state]) => <div key={type} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-lg font-semibold">{count}</p><p className="mt-1 text-[10px] font-medium">{type}</p><p className="mt-1 text-[9px] text-[var(--subtle)]">{state}</p></div>)}</div></SectionCard>
    <section className="grid gap-4 xl:grid-cols-[.72fr_1.28fr]"><div className="space-y-4"><ScoreHero label="Product Delivery Readiness" value={story.mockScores.handoffReadiness} detail="Low readiness is driven by missing actor, acceptance boundaries and failure behavior." /><ScoreHero label="DoU Score" value={story.mockScores.degreeOfUnderstanding} detail="Estimated degree of shared understanding across Product, Development and QA." /></div><SectionCard title="Active Product Understanding Event" subtitle={`${story.title} · ${story.id}`} icon={<Sparkles size={15} />}><FactGrid facts={[{ label: "Probable intent", value: story.expectedAnalysis.probableIntent }, { label: "Expected receiver", value: story.targetReceiver }, { label: "Scrum decision", value: "Not ready for sprint commitment" }, { label: "Recommended output", value: story.generatedOutput.title }]} /><div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--input)] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[var(--subtle)]">Ambiguous source</p><p className="mt-2 text-xs leading-6 text-[var(--muted)]">{story.rawInput}</p></div></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-3"><LabeledList label="Product risks" items={productRisks} tone="rose" /><LabeledList label="Development risks" items={developmentRisks} tone="amber" /><LabeledList label="QA risks" items={qaRisks} tone="amber" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Missing acceptance criteria" icon={<ShieldAlert size={15} />}><InsightList items={["Eligible enterprise buyer and account state", "Observable successful checkout outcome", "Behavior when payment authorization fails", "Session recovery and duplicate submission rules"]} tone="rose" /></SectionCard><SectionCard title="Critical questions" icon={<CircleCheckBig size={15} />}><InsightList items={["Which enterprise role initiates checkout?", "What metric proves checkout is easier?", "Which failure must preserve the cart?", "What is explicitly outside this release?"]} /></SectionCard></section>
    <SectionCard title="Generated operational outputs" subtitle="Operational artifacts available from this Understanding Event"><OutputChips outputs={["User Story", "Acceptance Criteria", "Test Cases", "Bug Report", "QA Notes"]} /><div className="mt-4 rounded-xl border border-teal-400/15 bg-teal-400/[.045] p-4"><p className="text-xs font-medium">Reference ready event</p><p className="mt-1 text-[10px] text-[var(--muted)]">{productEvent.title} · DoU {productEvent.scores.degreeOfUnderstanding} · Product Delivery Readiness {productEvent.scores.handoffReadiness}</p></div></SectionCard>
  </div>;
}
