"use client";

import { CircleCheckBig, PackageCheck, ShieldAlert, Sparkles } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { EvidenceSection } from "@/components/evidence/evidence-section";
import { LimitationsPanel } from "@/components/evidence/limitations-panel";
import { OutcomePanel } from "@/components/evidence/outcome-panel";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { events } from "@/lib/data/seed";
import { FactGrid, InsightList, LabeledList, OutputChips, PackHeader, ScoreHero, SectionCard } from "./shared";

export function ProductDeliveryPack() {
  const { locale, t } = useLanguage();
  const localized = <T,>(english: T, spanish: T) => locale === "es" ? spanish : english;
  const story = demoScenarios[0];
  const productEvent = events.find((event) => event.packType === "product-delivery")!;
  const eventTypes = localized(
    [["User Stories", "3", "2 at risk"], ["Bugs", "4", "1 blocked"], ["QA", "2", "Context gap"], ["Acceptance Criteria", "5", "3 ready"], ["Scrum", "3", "1 decision"], ["Product Handoffs", "2", "1 at risk"]],
    [["Historias de usuario", "3", "2 en riesgo"], ["Incidencias", "4", "1 bloqueada"], ["QA", "2", "Brecha de contexto"], ["Criterios de aceptación", "5", "3 listos"], ["Scrum", "3", "1 decisión"], ["Transferencias de producto", "2", "1 en riesgo"]],
  );
  const productRisks = localized(["Enterprise buyer is not defined", "“Better checkout” has no measurable boundary"], ["El comprador enterprise no está definido", "“Mejor checkout” no tiene un límite medible"]);
  const developmentRisks = localized(["Scope may expand during implementation", "Session and payment-state dependencies are implicit"], ["El alcance puede crecer durante la implementación", "Las dependencias de sesión y estado de pago son implícitas"]);
  const qaRisks = localized(["Completion cannot be tested objectively", "Error and recovery paths are absent"], ["La finalización no puede probarse objetivamente", "Faltan rutas de error y recuperación"]);
  const missingCriteria = localized(["Eligible enterprise buyer and account state", "Observable successful checkout outcome", "Behavior when payment authorization fails", "Session recovery and duplicate submission rules"], ["Comprador enterprise elegible y estado de cuenta", "Resultado observable de checkout exitoso", "Comportamiento cuando falla la autorización de pago", "Reglas de recuperación de sesión y envío duplicado"]);
  const questions = localized(["Which enterprise role initiates checkout?", "What metric proves checkout is easier?", "Which failure must preserve the cart?", "What is explicitly outside this release?"], ["¿Qué rol enterprise inicia el checkout?", "¿Qué métrica demuestra que el checkout es más sencillo?", "¿Qué fallo debe preservar el carrito?", "¿Qué queda explícitamente fuera de este release?"]);

  return <div className="space-y-6"><PackHeader order="07" eyebrow="Product Delivery Pack" title={t("Product intent that engineering and QA can execute.", "Intención de producto que desarrollo y QA pueden ejecutar.")} description={t("Structures ambiguous information as stories, criteria, QA matrices, bugs, recaps and handoffs for product, design, development, QA and scrum.", "Estructura información ambigua como historias, criterios, matrices QA, incidencias, recaps y transferencias claras para producto, diseño, desarrollo, QA y scrum.")} statement={t("Validate ambiguous information before execution.", "Validar información ambigua antes de la ejecución.")} icon={<PackageCheck size={15} />} />
    <SectionCard title="Product Understanding Events" subtitle="Operational intake across the delivery lifecycle"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-6">{eventTypes.map(([type, count, state]) => <div key={type} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-lg font-semibold">{count}</p><p className="mt-1 text-[10px] font-medium">{type}</p><p className="mt-1 text-[9px] text-[var(--subtle)]">{state}</p></div>)}</div></SectionCard>
    <section className="grid gap-4 xl:grid-cols-[.72fr_1.28fr]"><div className="space-y-4"><ScoreHero label="Product Delivery Readiness" value={story.mockScores.handoffReadiness} detail={t("Low readiness is driven by missing actor, acceptance boundaries and failure behavior.", "El readiness bajo se explica por actor faltante, límites de aceptación y comportamiento ante fallos.")} /><ScoreHero label="DoU Score" value={story.mockScores.degreeOfUnderstanding} detail={t("Estimated degree of shared understanding across Product, Development and QA.", "Grado estimado de entendimiento compartido entre Producto, Desarrollo y QA.")} /></div><SectionCard title="Active Product Understanding Event" subtitle={`${story.title} · ${story.id}`} icon={<Sparkles size={15} />}><FactGrid facts={[{ label: "Probable intent", value: story.expectedAnalysis.probableIntent }, { label: "Expected receiver", value: story.targetReceiver }, { label: "Scrum decision", value: t("Not ready for sprint commitment", "No está listo para compromiso de sprint") }, { label: "Recommended output", value: story.generatedOutput.title }]} /><div className="mt-4 rounded-xl border border-[var(--border)] bg-[var(--input)] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-[var(--subtle)]">{t("Ambiguous source", "Fuente ambigua")}</p><p className="mt-2 text-xs leading-6 text-[var(--muted)]">{story.rawInput}</p></div></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-3"><LabeledList label="Product risks" items={productRisks} tone="rose" /><LabeledList label="Development risks" items={developmentRisks} tone="amber" /><LabeledList label="QA risks" items={qaRisks} tone="amber" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Missing acceptance criteria" icon={<ShieldAlert size={15} />}><InsightList items={missingCriteria} tone="rose" /></SectionCard><SectionCard title="Critical questions to validate" icon={<CircleCheckBig size={15} />}><InsightList items={questions} /></SectionCard></section>
    <SectionCard title="Generated operational deliverables" subtitle="Operational artifacts available from this Understanding Event"><OutputChips outputs={["User Story", "Acceptance Criteria", "Test Cases", "Bug Report", "QA Notes"]} /><div className="mt-4 rounded-xl border border-teal-400/15 bg-teal-400/[.045] p-4"><p className="text-xs font-medium">{t("Reference event", "Evento de referencia")}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{productEvent.title} · {t("Simulated evidence · needs human confirmation", "Evidencia simulada · necesita confirmación humana")}</p></div></SectionCard>
    <section className="grid gap-4 lg:grid-cols-3"><EvidenceSection items={[{ id: "product-story", classification: "observed", title: t("Story text", "Texto de la historia"), detail: t("The supplied story names a broad checkout change.", "La historia suministrada nombra un cambio amplio de checkout.") }, { id: "product-intent", classification: "inferred", title: t("Probable intent", "Intención probable"), detail: story.expectedAnalysis.probableIntent }, { id: "product-acceptance", classification: "insufficient", title: t("Acceptance boundary", "Límite de aceptación"), detail: t("No measurable success or failure behavior is available.", "No hay éxito medible ni comportamiento ante fallos disponible.") }]} /><LimitationsPanel limitations={localized(["One simulated story was reviewed.", "No Jira history, design source or QA evidence is available.", "Readiness remains directional until the receiver confirms it."], ["Se revisó una historia simulada.", "No hay historial de Jira, fuente de diseño ni evidencia QA disponible.", "El readiness sigue siendo direccional hasta que el receptor lo confirme."])} /><OutcomePanel outcomes={localized(["Engineering can identify the actor and boundary.", "QA can test success and failure behavior.", "Scope changes propagate to criteria and evidence."], ["Desarrollo identifica actor y límite.", "QA puede probar éxito y comportamiento ante fallos.", "Los cambios de alcance se propagan a criterios y evidencia."])} /></section>
  </div>;
}
