"use client";

import Link from "next/link";
import { ArrowRight, BriefcaseBusiness, CircleAlert, ClipboardCheck, UserRoundSearch, UsersRound } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { InsightList, OutputChips, PackHeader, ScoreHero, SectionCard } from "./shared";

export function TalentStaffingPack() {
  const { t } = useLanguage();
  const scenarios = demoScenarios.filter((scenario) => scenario.packType === "talent-staffing");
  return <div className="space-y-6">
    <PackHeader order="13" eyebrow="Talent & Staffing Understanding" title={t("Understand the role before turning it into search, screening or candidate presentation.", "Entender la necesidad del rol antes de convertirla en búsqueda, filtro o presentación de candidatos.")} description={t("For staffing agencies, technical recruiting, outsourcing and talent providers that need to preserve operational meaning from client need to receiver decision.", "Para consultoras de talento, reclutamiento técnico, outsourcing y proveedores que necesitan preservar el significado operativo desde la necesidad del cliente hasta la decisión del equipo receptor.")} statement={t("Virro reduces meaning loss between what the company needs, what the consultant interprets, what the candidate communicates and what the receiving team expects.", "Virro reduce la pérdida de entendimiento entre lo que la empresa necesita, lo que la consultora interpreta, lo que el candidato comunica y lo que el equipo receptor espera.")} icon={<UsersRound size={15} />} />
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label={t("Role Understanding Score", "Role Understanding Score")} value={43} detail={t("Estimated readiness of the client need before activating search.", "Readiness estimado de la necesidad del cliente antes de activar la búsqueda.")} /><SectionCard title={t("Central question", "Pregunta central")} icon={<CircleAlert size={15} />}><p className="text-sm leading-6 text-[var(--muted)]">{t("Is the client need sufficiently understood before it becomes search, screening, interview or candidate presentation?", "¿La necesidad del cliente está suficientemente entendida antes de convertirla en búsqueda, filtro, entrevista o presentación de candidatos?")}</p></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-3"><SectionCard title={t("Client requirement gaps", "Brechas del requerimiento cliente")} icon={<BriefcaseBusiness size={15} />}><InsightList items={t("Role outcomes|Autonomy and ownership|Real technical scope|Communication context", "Resultados esperados del rol|Autonomía y ownership|Alcance técnico real|Contexto de comunicación").split("|")} tone="rose" /></SectionCard><SectionCard title={t("Screening risks", "Riesgos de screening")} icon={<UserRoundSearch size={15} />}><InsightList items={t("Filtering only by tool keywords|Unvalidated seniority expectation|Interview criteria differ from the hiring manager", "Filtrar solo por keywords de herramientas|Seniority esperado no validado|Criterios de entrevista distintos al hiring manager").split("|")} tone="amber" /></SectionCard><SectionCard title={t("Candidate handoff readiness", "Readiness del handoff de candidato")} icon={<ClipboardCheck size={15} />}><InsightList items={t("Project context is explicit|Autonomy evidence is attached|Limitations are visible|Receiver questions are anticipated", "Contexto de proyectos explícito|Evidencia de autonomía adjunta|Limitaciones visibles|Preguntas del receptor anticipadas").split("|")} /></SectionCard></section>
    <SectionCard title={t("Operational outputs", "Outputs operativos")}><OutputChips outputs={["Role Understanding Pack", "Screening Readiness Score", "Candidate Fit Understanding", "Client Requirement Gaps", "Interview Guide", "Candidate Handoff Pack", "Candidate Presentation Readiness"]} /></SectionCard>
    <SectionCard title={t("Talent & Staffing demo scenarios", "Escenarios demo de Talent & Staffing")} subtitle={t("Separate from Consulting Delivery project execution", "Separado de la ejecución de proyectos de Consulting Delivery")}><div className="grid gap-3 md:grid-cols-2">{scenarios.map((scenario) => <article key={scenario.id} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-4"><p className="text-xs font-semibold">{scenario.title}</p><p className="mt-2 text-[10px] leading-5 text-[var(--muted)]">{scenario.context}</p><Link href="/demo-scenarios" className="mt-3 inline-flex items-center gap-2 text-[10px] font-semibold text-teal-300">{t("Run scenario", "Ejecutar escenario")} <ArrowRight size={12} /></Link></article>)}</div></SectionCard>
    <section className="rounded-xl border border-indigo-400/15 bg-indigo-400/[.04] p-5"><p className="text-[9px] font-semibold uppercase tracking-[.12em] text-indigo-300">{t("Recommended audit", "Audit recomendado")}</p><h2 className="mt-2 text-sm font-semibold">Talent & Staffing Understanding Audit</h2><p className="mt-2 text-xs leading-5 text-[var(--muted)]">{t("Review real role requirements and candidate handoffs to find where screening criteria and receiver expectations diverge.", "Revisar requerimientos reales y handoffs de candidatos para detectar dónde divergen los criterios de filtro y las expectativas del receptor.")}</p></section>
  </div>;
}
