import { Boxes, FileCode2, GitBranch, ListTodo, Network } from "lucide-react";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

const sources = ["Confluence", "ADRs", "API documentation", "Architecture diagrams", "Runbooks", "Deployment guides", "Microservice docs", "Integration docs"];

export function TechnicalDocumentationPack() {
  const scenario = demoScenarios[6];
  return <div className="space-y-6"><PackHeader order="13" eyebrow="Architecture & Technical Documentation Understanding Pack" title="Tu arquitectura puede estar documentada y aun así no estar entendida." description="Analyze whether technical knowledge supports safe action across engineering, QA, DevOps, consultants and AI." statement="Validar si la documentación técnica permite que otro equipo entienda, ejecute, mantenga, pruebe o modifique un sistema." icon={<FileCode2 size={15} />} />
    <div className="flex flex-wrap gap-2">{sources.map((source) => <span key={source} className="rounded-lg border border-[var(--border)] bg-[var(--panel-soft)] px-3 py-2 text-[9px] text-[var(--muted)]">{source}</span>)}</div>
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label="Technical Understanding Readiness Score" value={scenario.mockScores.technicalReadiness} detail="Measures whether another technical role can safely act from the available documentation." /><SectionCard title="Architecture Understanding Map" icon={<Network size={15} />}><div className="grid gap-2 sm:grid-cols-4">{[{l:"Billing API v3",s:"Documented"},{l:"Event pipeline",s:"Partial"},{l:"Consumers",s:"Unknown"},{l:"Rollback path",s:"Unclear"}].map((node) => <div key={node.l} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3 text-center"><Boxes size={14} className="mx-auto text-teal-300" /><p className="mt-2 text-[10px] font-medium">{node.l}</p><p className={`mt-1 text-[9px] ${node.s === "Documented" ? "text-emerald-300" : "text-amber-300"}`}>{node.s}</p></div>)}</div></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-3"><LabeledList label="Missing Technical Context" items={scenario.expectedAnalysis.missingInformation} tone="rose" /><LabeledList label="Unclear Dependencies" items={["Legacy invoice consumer", "Partner reconciliation export", "Fraud decision webhook", "Operations replay tooling"]} tone="amber" /><LabeledList label="Undocumented Decisions" items={["Why v3 requires the new event pipeline", "Why compatibility mode was rejected", "Who owns the rollback decision"]} tone="amber" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="QA Understanding Notes"><InsightList items={["Contract compatibility matrix is missing", "Failure and replay behavior cannot be derived", "Test data version ownership is unclear"]} /></SectionCard><SectionCard title="DevOps Understanding Notes"><InsightList items={["Rollback trigger has no measurable threshold", "Event replay runbook is not linked", "Monitoring ownership after migration is unclear"]} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title="Consultant Technical Handoff Pack" icon={<GitBranch size={15} />}><FactGrid facts={[{label:"System boundary",value:"Billing API v3 and event pipeline"},{label:"Decision history",value:"2 ADRs missing rationale"},{label:"Access required",value:"Architecture, consumer inventory and runbooks"},{label:"Blocking question",value:"Which consumer cannot accept the new contract?"}]} /></SectionCard><SectionCard title="AI Technical Context Pack"><InsightList items={["Approved architecture boundary", "API contracts and version rules", "Consumer dependency inventory", "Quality and security constraints", "Explicit prohibition on inventing recovery behavior"]} /></SectionCard></section>
    <SectionCard title="Documentation Debt Backlog" icon={<ListTodo size={15} />}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="text-[9px] uppercase tracking-[.1em] text-[var(--subtle)]"><th className="pb-3 font-medium">Debt item</th><th className="pb-3 font-medium">Operational impact</th><th className="pb-3 font-medium">Priority</th><th className="pb-3 font-medium">Owner</th></tr></thead><tbody>{[["Consumer dependency map","Unsafe migration scope","Critical","Platform Architect"],["Rollback decision rule","Delayed recovery","Critical","Migration Lead"],["ADR rationale","Future change rework","High","Architecture Council"],["QA replay notes","Incomplete failure coverage","High","QA Lead"]].map((row) => <tr key={row[0]} className="border-t border-[var(--border)]"><td className="py-3 text-xs font-medium">{row[0]}</td><td className="py-3 text-[10px] text-[var(--muted)]">{row[1]}</td><td className="py-3 text-[10px] text-rose-300">{row[2]}</td><td className="py-3 text-[10px] text-[var(--muted)]">{row[3]}</td></tr>)}</tbody></table></div></SectionCard>
  </div>;
}
