"use client";

import { Boxes, FileCode2, GitBranch, ListTodo, Network } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { demoScenarios } from "@/lib/data/demo-scenarios";
import { FactGrid, InsightList, LabeledList, PackHeader, ScoreHero, SectionCard } from "./shared";

export function TechnicalDocumentationPack() {
  const { locale, t } = useLanguage();
  const localized = <T,>(english: T, spanish: T) => locale === "es" ? spanish : english;
  const sources = localized(
    ["Confluence", "ADRs", "API documentation", "Architecture diagrams", "Runbooks", "Deployment guides", "Microservice docs", "Integration docs"],
    ["Confluence", "ADRs", "Documentación de APIs", "Diagramas de arquitectura", "Runbooks", "Guías de despliegue", "Documentación de microservicios", "Documentación de integraciones"],
  );
  const scenario = demoScenarios[6];
  return <div className="space-y-6"><PackHeader order="14" eyebrow={t("Architecture & Technical Documentation Understanding", "Entendimiento de arquitectura y documentación técnica")} title={t("Your architecture can be documented and still not be understood.", "Tu arquitectura puede estar documentada y aun así no estar entendida.")} description={t("Validate whether Confluence, ADRs, APIs, diagrams or runbooks allow engineering, QA, DevOps, support, consultants or AI to act.", "Valida si Confluence, ADRs, APIs, diagramas o runbooks permiten que desarrollo, QA, DevOps, soporte, consultoras o IA puedan actuar.")} statement={t("Validate whether technical documentation allows another team to understand, execute, maintain, test or modify a system.", "Validar si la documentación técnica permite que otro equipo entienda, ejecute, mantenga, pruebe o modifique un sistema.")} icon={<FileCode2 size={15} />} />
    <div className="flex flex-wrap gap-2">{sources.map((source) => <span key={source} className="rounded-lg border border-[var(--border)] bg-[var(--panel-soft)] px-3 py-2 text-[9px] text-[var(--muted)]">{source}</span>)}</div>
    <section className="grid gap-4 xl:grid-cols-[.68fr_1.32fr]"><ScoreHero label={t("Technical Understanding Readiness Score", "Readiness de entendimiento técnico")} value={scenario.mockScores.technicalReadiness} detail={t("Measures whether another technical role can safely act from the available documentation.", "Estima si otro rol técnico puede actuar con suficiente claridad a partir de la documentación disponible.")} /><SectionCard title={t("Architecture Understanding Map", "Mapa de entendimiento de arquitectura")} icon={<Network size={15} />}><div className="grid gap-2 sm:grid-cols-4">{localized([{l:"Billing API v3",s:"Documented"},{l:"Event pipeline",s:"Partial"},{l:"Consumers",s:"Unknown"},{l:"Rollback path",s:"Unclear"}], [{l:"Billing API v3",s:"Documentada"},{l:"Pipeline de eventos",s:"Parcial"},{l:"Consumidores",s:"Desconocidos"},{l:"Ruta de rollback",s:"Poco clara"}]).map((node, index) => <div key={node.l} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3 text-center"><Boxes size={14} className="mx-auto text-teal-300" /><p className="mt-2 text-[10px] font-medium">{node.l}</p><p className={`mt-1 text-[9px] ${index === 0 ? "text-emerald-300" : "text-amber-300"}`}>{node.s}</p></div>)}</div></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-3"><LabeledList label={t("Missing Technical Context", "Contexto técnico faltante")} items={scenario.expectedAnalysis.missingInformation} tone="rose" /><LabeledList label={t("Unclear Dependencies", "Dependencias poco claras")} items={localized(["Legacy invoice consumer", "Partner reconciliation export", "Fraud decision webhook", "Operations replay tooling"], ["Consumidor legacy de facturación", "Exportación de conciliación de partners", "Webhook de decisión de fraude", "Herramientas operativas de replay"])} tone="amber" /><LabeledList label={t("Undocumented Decisions", "Decisiones no documentadas")} items={localized(["Why v3 requires the new event pipeline", "Why compatibility mode was rejected", "Who owns the rollback decision"], ["Por qué v3 requiere el nuevo pipeline de eventos", "Por qué se rechazó el modo de compatibilidad", "Quién es responsable de la decisión de rollback"])} tone="amber" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title={t("QA Understanding Notes", "Notas de entendimiento para QA")}><InsightList items={localized(["Contract compatibility matrix is missing", "Failure and replay behavior cannot be derived", "Test data version ownership is unclear"], ["Falta la matriz de compatibilidad de contratos", "No puede deducirse el comportamiento ante fallos y replay", "El ownership de versiones de datos de prueba no está claro"])} /></SectionCard><SectionCard title={t("DevOps Understanding Notes", "Notas de entendimiento para DevOps")}><InsightList items={localized(["Rollback trigger has no measurable threshold", "Event replay runbook is not linked", "Monitoring ownership after migration is unclear"], ["El disparador de rollback no tiene un umbral medible", "El runbook de replay de eventos no está vinculado", "El ownership de monitoreo posterior a la migración no está claro"])} /></SectionCard></section>
    <section className="grid gap-4 lg:grid-cols-2"><SectionCard title={t("Consultant Technical Handoff Pack", "Pack de handoff técnico para consultoras")} icon={<GitBranch size={15} />}><FactGrid facts={localized([{label:"System boundary",value:"Billing API v3 and event pipeline"},{label:"Decision history",value:"2 ADRs missing rationale"},{label:"Access required",value:"Architecture, consumer inventory and runbooks"},{label:"Blocking question",value:"Which consumer cannot accept the new contract?"}], [{label:"Límite del sistema",value:"Billing API v3 y pipeline de eventos"},{label:"Historial de decisiones",value:"2 ADRs sin justificación"},{label:"Acceso requerido",value:"Arquitectura, inventario de consumidores y runbooks"},{label:"Pregunta bloqueante",value:"¿Qué consumidor no puede aceptar el nuevo contrato?"}])} /></SectionCard><SectionCard title={t("AI Technical Context Pack", "Context Pack técnico para IA")}><InsightList items={localized(["Approved architecture boundary", "API contracts and version rules", "Consumer dependency inventory", "Quality and security constraints", "Explicit prohibition on inventing recovery behavior"], ["Límite de arquitectura aprobado", "Contratos de API y reglas de versionado", "Inventario de dependencias de consumidores", "Restricciones de calidad y seguridad", "Prohibición explícita de inventar comportamientos de recuperación"])} /></SectionCard></section>
    <SectionCard title={t("Documentation Debt Backlog", "Backlog de deuda de documentación")} icon={<ListTodo size={15} />}><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="text-[9px] uppercase tracking-[.1em] text-[var(--subtle)]"><th className="pb-3 font-medium">{t("Debt item", "Deuda de contexto")}</th><th className="pb-3 font-medium">{t("Operational impact", "Impacto operativo")}</th><th className="pb-3 font-medium">{t("Priority", "Prioridad")}</th><th className="pb-3 font-medium">Owner</th></tr></thead><tbody>{localized([["Consumer dependency map","Unsafe migration scope","Critical","Platform Architect"],["Rollback decision rule","Delayed recovery","Critical","Migration Lead"],["ADR rationale","Future change rework","High","Architecture Council"],["QA replay notes","Incomplete failure coverage","High","QA Lead"]], [["Mapa de dependencias de consumidores","Alcance de migración inseguro","Crítica","Platform Architect"],["Regla de decisión de rollback","Recuperación tardía","Crítica","Migration Lead"],["Justificación de ADRs","Retrabajo en cambios futuros","Alta","Architecture Council"],["Notas de replay para QA","Cobertura de fallos incompleta","Alta","QA Lead"]]).map((row) => <tr key={row[0]} className="border-t border-[var(--border)]"><td className="py-3 text-xs font-medium">{row[0]}</td><td className="py-3 text-[10px] text-[var(--muted)]">{row[1]}</td><td className="py-3 text-[10px] text-rose-300">{row[2]}</td><td className="py-3 text-[10px] text-[var(--muted)]">{row[3]}</td></tr>)}</tbody></table></div></SectionCard>
  </div>;
}
