import type { Locale } from "./locale";

const es: Record<string, string> = {
  "Handoff Intelligence Pack": "Pack de inteligencia de handoffs", "Process Understanding Pack": "Pack de entendimiento de procesos", "Onboarding & Knowledge Transfer Pack": "Pack de onboarding y transferencia de entendimiento", "Consulting Delivery Pack": "Pack de entrega para consultoras", "Talent & Staffing Understanding": "Entendimiento de talento y staffing",
  "Product Delivery Pack": "Pack de entrega de producto", "Product Understanding Events": "Eventos de entendimiento de producto", "Operational intake across the delivery lifecycle": "Ingreso operativo a lo largo del ciclo de entrega", "Product Delivery Readiness": "Readiness de entrega de producto", "Active Product Understanding Event": "Understanding Event de producto activo", "Probable intent": "Intención probable", "Expected receiver": "Receptor esperado", "Scrum decision": "Decisión de Scrum", "Recommended output": "Entregable recomendado", "Product risks": "Riesgos de producto", "Development risks": "Riesgos de desarrollo", "QA risks": "Riesgos de QA", "Missing acceptance criteria": "Criterios de aceptación faltantes", "Critical questions to validate": "Preguntas críticas para validar", "Critical Questions Map": "Mapa de preguntas críticas para validar", "Questions for Client": "Preguntas para validar con el cliente", "Generated operational deliverables": "Entregables operativos generados", "Operational artifacts available from this Understanding Event": "Artefactos operativos disponibles a partir de este Understanding Event", "Reference ready event": "Evento de referencia listo", "User Story": "Historia de usuario", "Acceptance Criteria": "Criterios de aceptación", "Test Cases": "Casos de prueba", "Bug Report": "Reporte de bug", "QA Notes": "Notas de QA",
  "Handoff Readiness Score": "Score de readiness del handoff", "Supported handoff paths": "Rutas de handoff soportadas", "What is clear": "Qué está claro", "What is missing": "Qué falta", "Blockers": "Bloqueadores", "Rework risks": "Riesgos de retrabajo", "Pre-handoff checklist": "Checklist previo al handoff", "Handoff-ready version": "Versión lista para handoff", "Current handoff profile": "Perfil actual del handoff", "Source → Target": "Origen → destino",
  "Process Understanding Readiness": "Readiness de entendimiento del proceso", "Process operating model": "Modelo operativo del proceso", "Process objective": "Objetivo del proceso", Trigger: "Disparador", Owner: "Responsable", Receiver: "Receptor", Inputs: "Entradas", Outputs: "Resultados", "Process map": "Mapa del proceso", "Operational meaning across the standard path": "Significado operativo a lo largo de la ruta estándar", "Decision gap": "Brecha de decisión", Decisions: "Decisiones", Exceptions: "Excepciones", "Operational rules": "Reglas operativas", Risks: "Riesgos", "Missing process context": "Contexto faltante del proceso", "Version for another team": "Versión para otro equipo", "Version for AI": "Versión para IA",
  "Onboarding Readiness Score": "Score de readiness de onboarding", "Role Onboarding Card": "Role Onboarding Card", Role: "Rol", "Operational outcome": "Resultado operativo", "Needs to understand": "Necesita entender", "Expected outputs": "Entregables esperados", "First 30 Days Understanding Plan": "Plan de entendimiento de los primeros 30 días", "Knowledge Transfer Gaps": "Brechas de transferencia de entendimiento", "Common Misunderstandings": "Malentendidos frecuentes", "Required Context": "Contexto requerido", "AI Context Pack for New Member": "Context Pack para IA del nuevo miembro",
  "Consulting Delivery Readiness Score": "Score de readiness de entrega para consultoras", "Client Understanding Pack": "Pack de entendimiento del cliente", "Client intent": "Intención del cliente", "Decision to support": "Decisión que debe respaldar", "Target receiver": "Receptor destino", "Evidence status": "Estado de la evidencia", "Scope Meaning Loss Review": "Revisión de Meaning Loss del alcance", "Client said": "El cliente dijo", "Consultancy inferred": "La consultora interpretó", "Delivery may execute": "El equipo podría ejecutar", "Delivery Handoff Readiness": "Readiness del handoff de entrega", "Scope boundary": "Límite de alcance", "Integration inventory": "Inventario de integraciones", "Decision owner": "Responsable de decisión", "Success evidence": "Evidencia de éxito", "Not ready": "No listo", Missing: "Faltante", "Client sponsor assumed": "Sponsor del cliente asumido", Undefined: "No definido", "Client Context Gaps": "Brechas de contexto del cliente", "Delivery Risks": "Riesgos de entrega", "Consultant Onboarding Pack": "Pack de onboarding de consultora", "Delivery interpretation control": "Control de interpretación de entrega", "Operational deliverables": "Entregables operativos",
  "Documentation Debt Backlog": "Backlog de deuda de documentación", "Output Understanding Check": "Revisión de entendimiento del resultado", "Role Understanding Pack": "Pack de entendimiento del rol", "Screening Readiness Score": "Score de readiness del screening", "Candidate Fit Understanding": "Entendimiento del fit del candidato", "Client Requirement Gaps": "Brechas del requerimiento del cliente", "Interview Guide": "Guía de entrevista", "Candidate Handoff Pack": "Pack de handoff del candidato", "Candidate Presentation Readiness": "Readiness de presentación del candidato",
};

export function packUiText(locale: Locale, value: string) { return locale === "es" ? (es[value] ?? value) : value; }
