// @vitest-environment node

import { readdirSync, readFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { resolve } from "node:path";

import { Client } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import type { AuthorityContext, TenantMembershipRecord, TenantRecord } from "@/src/domain/auth/authority";
import type { TenantMembershipRepository } from "@/src/application/ports/auth/authority-repositories";
import { TenantAuthorityService } from "@/src/application/auth/tenant-authority-service";
import type { OutcomeTransactionRecord, OutcomeTransactionRepository } from "@/src/application/ports/repositories";
import type { RequirementCatalogRepository } from "@/src/application/ports/outcome/requirement-catalog-repository";
import type { OutcomeTransactionRequirementBindingRepository } from "@/src/application/ports/outcome/transaction-requirement-binding-repository";
import { OutcomeRequirementAuthorityResolver } from "@/src/application/outcome/resolve-outcome-requirement-authority";
import { createPrecisionEditBlueprintDefinition } from "@/src/application/outcome/specification/precision-edit-blueprint";
import { OutcomeBlueprintSchema, publishOutcomeBlueprint, type OutcomeBlueprint } from "@/src/domain/outcome/specification/outcome-blueprint";
import { OutcomeRequirementProfileSchema, publishOutcomeRequirementProfile, type OutcomeRequirementProfile } from "@/src/domain/outcome/specification/outcome-requirement-profile";
import { OutcomeTransactionRequirementBindingSchema, createOutcomeTransactionRequirementBinding, verifyOutcomeTransactionRequirementBindingHash, type OutcomeTransactionRequirementBinding } from "@/src/domain/outcome/specification/outcome-transaction-requirement-binding";

const enabled = process.env.BUILD002_NATIVE_PG_C0_E_INDEPENDENT === "true";
const databaseUrl = process.env.BUILD002_NATIVE_PG_URL;
const migrationsDir = resolve(process.cwd(), "supabase/migrations");
const A = { principal: "11000000-0000-4000-8000-000000000001", tenant: "21000000-0000-4000-8000-000000000001", membership: "31000000-0000-4000-8000-000000000001", tx: "41000000-0000-4000-8000-000000000001", project: "51000000-0000-4000-8000-000000000001", asset: "61000000-0000-4000-8000-000000000001", version: "71000000-0000-4000-8000-000000000001" } as const;
const B = { principal: "11000000-0000-4000-8000-000000000002", tenant: "21000000-0000-4000-8000-000000000002", membership: "31000000-0000-4000-8000-000000000002", tx: "41000000-0000-4000-8000-000000000002", project: "51000000-0000-4000-8000-000000000002", asset: "61000000-0000-4000-8000-000000000002", version: "71000000-0000-4000-8000-000000000002" } as const;
const NO_BINDING = "41000000-0000-4000-8000-000000000003";
const NO_MEMBERSHIP_PRINCIPAL = "11000000-0000-4000-8000-000000000099";
type Row = Record<string, unknown>;

function db(url: string, name: string): string { const parsed = new URL(url); parsed.pathname = `/${name}`; return parsed.toString(); }
function instant(value: unknown): string { return value instanceof Date ? value.toISOString() : new Date(String(value)).toISOString(); }
function principal(id: string) { return { principalId: id, sessionId: `independent-${id}`, authenticationAssurance: "independent", authenticatedAt: "2026-08-20T12:00:00.000Z" }; }
function blueprintPayload(value: OutcomeBlueprint): Row { const { hash, status, publishedAt, ...definition } = value; void hash; void status; return { ...value, publishedAt, definition }; }
function profilePayload(value: OutcomeRequirementProfile): Row { const { hash, status, publishedAt, ...definition } = value; void hash; void status; return { ...value, publishedAt, definition }; }
function bindingPayload(value: OutcomeTransactionRequirementBinding): Row { return { schema_version: value.schemaVersion, owner_tenant_id: value.ownerTenantId, outcome_transaction_id: value.outcomeTransactionId, blueprint_id: value.blueprint.id, blueprint_version: value.blueprint.version, blueprint_hash: value.blueprint.hash, requirement_profile_id: value.requirementProfile.id, requirement_profile_version: value.requirementProfile.version, requirement_profile_hash: value.requirementProfile.hash, policy_id: null, policy_hash: null, binding_hash: value.bindingHash, bound_at: value.boundAt }; }
function transaction(row: Row): OutcomeTransactionRecord { return { id: String(row.id), ownerTenantId: row.owner_tenant_id ? String(row.owner_tenant_id) : null, projectId: String(row.project_id), assetId: String(row.asset_id), baseVersionId: String(row.base_version_id), status: row.status as OutcomeTransactionRecord["status"], rawRequest: String(row.raw_request), createdAt: instant(row.created_at), updatedAt: instant(row.updated_at), completedAt: row.completed_at ? instant(row.completed_at) : null, abortReason: row.abort_reason ? String(row.abort_reason) : null }; }
function blueprint(row: Row): OutcomeBlueprint { return OutcomeBlueprintSchema.parse({ ...(row.definition as Row), hash: String(row.hash), status: String(row.status), publishedAt: instant(row.published_at) }); }
function profile(row: Row): OutcomeRequirementProfile { return OutcomeRequirementProfileSchema.parse({ ...(row.definition as Row), hash: String(row.hash), status: String(row.status), publishedAt: instant(row.published_at) }); }
function binding(row: Row): OutcomeTransactionRequirementBinding { return OutcomeTransactionRequirementBindingSchema.parse({ schemaVersion: String(row.schema_version), ownerTenantId: String(row.owner_tenant_id), outcomeTransactionId: String(row.outcome_transaction_id), blueprint: { id: String(row.blueprint_id), version: Number(row.blueprint_version), hash: String(row.blueprint_hash) }, requirementProfile: { id: String(row.requirement_profile_id), version: Number(row.requirement_profile_version), hash: String(row.requirement_profile_hash) }, policy: { id: null, hash: null }, bindingHash: String(row.binding_hash), boundAt: instant(row.bound_at) }); }

class Memberships implements TenantMembershipRepository {
  constructor(private readonly client: Client) {}
  async listActiveMemberships(principalId: string): Promise<TenantMembershipRecord[]> { const result = await this.client.query("select id,tenant_id,principal_id,role,status,created_at,revoked_at from public.tenant_memberships where principal_id=$1 and status='ACTIVE' order by tenant_id", [principalId]); return result.rows.map((row) => ({ id: String(row.id), tenantId: String(row.tenant_id), principalId: String(row.principal_id), role: row.role as TenantMembershipRecord["role"], status: "ACTIVE", createdAt: instant(row.created_at), revokedAt: row.revoked_at ? instant(row.revoked_at) : null })); }
  async findTenant(tenantId: string): Promise<TenantRecord | null> { const result = await this.client.query("select id,kind,status,created_at,updated_at from public.tenants where id=$1", [tenantId]); const row = result.rows[0]; return row ? { id: String(row.id), kind: row.kind as TenantRecord["kind"], status: row.status as TenantRecord["status"], createdAt: instant(row.created_at), updatedAt: instant(row.updated_at) } : null; }
  async findActiveMembership(principalId: string, tenantId: string): Promise<TenantMembershipRecord | null> { const result = await this.client.query("select id,tenant_id,principal_id,role,status,created_at,revoked_at from public.tenant_memberships where principal_id=$1 and tenant_id=$2 and status='ACTIVE'", [principalId, tenantId]); const row = result.rows[0]; return row ? { id: String(row.id), tenantId: String(row.tenant_id), principalId: String(row.principal_id), role: row.role as TenantMembershipRecord["role"], status: "ACTIVE", createdAt: instant(row.created_at), revokedAt: row.revoked_at ? instant(row.revoked_at) : null } : null; }
}

class Transactions implements OutcomeTransactionRepository {
  constructor(private readonly client: Client, private readonly tenant: string) {}
  async findById(id: string): Promise<OutcomeTransactionRecord | null> { const result = await this.client.query("select * from public.outcome_transactions where owner_tenant_id=$1 and id=$2", [this.tenant, id]); return result.rows[0] ? transaction(result.rows[0]) : null; }
  async create(): Promise<OutcomeTransactionRecord> { throw new Error("read-only"); }
  async findByAssetId(): Promise<OutcomeTransactionRecord[]> { throw new Error("read-only"); }
  async updateStatus(): Promise<OutcomeTransactionRecord> { throw new Error("read-only"); }
}

class Catalog implements RequirementCatalogRepository {
  constructor(private readonly client: Client, private readonly overrides: { blueprint?: () => Promise<OutcomeBlueprint | null>; profile?: () => Promise<OutcomeRequirementProfile | null> } = {}) {}
  async getBlueprint(id: string, version: number): Promise<OutcomeBlueprint | null> { if (this.overrides.blueprint) return this.overrides.blueprint(); const result = await this.client.query("select * from public.outcome_blueprints where id=$1 and version=$2", [id, version]); return result.rows[0] ? blueprint(result.rows[0]) : null; }
  async getRequirementProfile(id: string, version: number): Promise<OutcomeRequirementProfile | null> { if (this.overrides.profile) return this.overrides.profile(); const result = await this.client.query("select * from public.outcome_requirement_profiles where id=$1 and version=$2", [id, version]); return result.rows[0] ? profile(result.rows[0]) : null; }
  async publishBlueprint(): Promise<OutcomeBlueprint> { throw new Error("read-only"); }
  async publishRequirementProfile(): Promise<OutcomeRequirementProfile> { throw new Error("read-only"); }
}

class Bindings implements OutcomeTransactionRequirementBindingRepository {
  constructor(private readonly client: Client, private readonly tenant: string, private readonly override?: () => Promise<OutcomeTransactionRequirementBinding | null>) {}
  async get(id: string): Promise<OutcomeTransactionRequirementBinding | null> { if (this.override) return this.override(); const result = await this.client.query("select * from public.outcome_transaction_requirement_bindings where owner_tenant_id=$1 and outcome_transaction_id=$2", [this.tenant, id]); if (!result.rows[0]) return null; const value = binding(result.rows[0]); if (!verifyOutcomeTransactionRequirementBindingHash(value)) throw new Error("binding tamper"); return value; }
  async publish(): Promise<OutcomeTransactionRequirementBinding> { throw new Error("read-only"); }
}

function resolver(client: Client, tenant: string, options: { binding?: () => Promise<OutcomeTransactionRequirementBinding | null>; blueprint?: () => Promise<OutcomeBlueprint | null>; profile?: () => Promise<OutcomeRequirementProfile | null>; clock?: string } = {}): OutcomeRequirementAuthorityResolver {
  return new OutcomeRequirementAuthorityResolver({ transactions: new Transactions(client, tenant), bindings: new Bindings(client, tenant, options.binding), catalog: new Catalog(client, { blueprint: options.blueprint, profile: options.profile }), clock: { now: () => options.clock ?? "2026-08-20T12:00:00.000Z" } });
}

async function fails(promise: Promise<unknown>, code?: string): Promise<void> { await expect(promise).rejects.toMatchObject(code ? { code } : { code: expect.any(String) }); }

type Snapshot = Record<string, number | string>;
async function snapshot(client: Client): Promise<Snapshot> { const result = await client.query(`select (select count(*)::int from public.build002_signal_requirements) as requirements,(select count(*)::int from public.build002_signals) as signals,(select count(*)::int from public.build002_dependency_snapshots) as dependencies,(select count(*)::int from public.build002_signal_qualifications) as qualifications,(select count(*)::int from public.build002_delegation_readiness) as readiness,(select count(*)::int from public.execution_runs) as executions,(select count(*)::int from public.mutation_leases) as leases,(select count(*)::int from public.state_commits) as commits,(select status::text from public.outcome_transactions where id=$1) as tx_status,(select current_version_id::text from public.assets where id=$2) as current_version`, [A.tx, A.asset]); const row = result.rows[0] as Row; return { requirements: Number(row.requirements), signals: Number(row.signals), dependencies: Number(row.dependencies), qualifications: Number(row.qualifications), readiness: Number(row.readiness), executions: Number(row.executions), leases: Number(row.leases), commits: Number(row.commits), tx_status: String(row.tx_status), current_version: String(row.current_version) }; }

describe.runIf(enabled && Boolean(databaseUrl))("BUILD 002-C0-E independent composed authority verification", () => {
  let admin: Client; let isolatedDatabase: string; let blueprintA: OutcomeBlueprint; let blueprintB: OutcomeBlueprint; let profileA: OutcomeRequirementProfile; let profileB: OutcomeRequirementProfile; let bindingA: OutcomeTransactionRequirementBinding; let bindingB: OutcomeTransactionRequirementBinding; let authorityA: AuthorityContext; let authorityB: AuthorityContext;

  beforeAll(async () => {
    isolatedDatabase = `virro_c0_e_independent_${process.pid}_${Date.now()}`;
    const root = new Client({ connectionString: db(databaseUrl!, "postgres") }); await root.connect(); await root.query(`drop database if exists "${isolatedDatabase}" with (force)`); await root.query(`create database "${isolatedDatabase}"`); await root.end();
    admin = new Client({ connectionString: db(databaseUrl!, isolatedDatabase) }); await admin.connect();
    await admin.query(`create extension if not exists pgcrypto; do $$ begin create role anon nologin; exception when duplicate_object then null; end $$; do $$ begin create role authenticated nologin; exception when duplicate_object then null; end $$; do $$ begin create role service_role nologin bypassrls; exception when duplicate_object then null; end $$; create schema if not exists auth; create table if not exists auth.users(id uuid primary key); create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$; create schema if not exists storage; create table if not exists storage.buckets(id text primary key,name text not null unique,public boolean not null default false,file_size_limit bigint,allowed_mime_types text[]);`);
    for (const migration of readdirSync(migrationsDir).filter((name) => name.endsWith(".sql")).sort()) await admin.query(readFileSync(resolve(migrationsDir, migration), "utf8"));
    await admin.query("insert into auth.users(id) values($1),($2) on conflict do nothing", [A.principal, B.principal]);
    await admin.query("insert into public.tenants(id,kind,status) values($1,'ORGANIZATION','ACTIVE'),($2,'ORGANIZATION','ACTIVE')", [A.tenant, B.tenant]);
    await admin.query("insert into public.tenant_memberships(id,tenant_id,principal_id,role,status) values($1,$2,$3,'OWNER','ACTIVE'),($4,$5,$6,'OWNER','ACTIVE')", [A.membership, A.tenant, A.principal, B.membership, B.tenant, B.principal]);
    await admin.query("insert into public.projects(id,owner_tenant_id,name) values($1,$2,'A'),($3,$4,'B')", [A.project, A.tenant, B.project, B.tenant]);
    await admin.query("insert into public.assets(id,owner_tenant_id,project_id,name) values($1,$2,$3,'A'),($4,$5,$6,'B')", [A.asset, A.tenant, A.project, B.asset, B.tenant, B.project]);
    await admin.query("insert into public.asset_versions(id,owner_tenant_id,asset_id,version_number,state) values($1,$2,$3,1,'{}'),($4,$5,$6,1,'{}')", [A.version, A.tenant, A.asset, B.version, B.tenant, B.asset]);
    await admin.query("update public.assets set current_version_id=$1 where id=$2", [A.version, A.asset]); await admin.query("update public.assets set current_version_id=$1 where id=$2", [B.version, B.asset]);
    const forged = JSON.stringify({ tenantId: B.tenant, blueprint: { forged: true }, profile: { forged: true }, requirements: [{ requirementId: "forged" }], acceptedProvenance: ["OBSERVED"], requirementDefinitionHash: "f".repeat(64), inputRequirements: [{ requirementId: "forged" }], readiness: "READY" });
    await admin.query("insert into public.outcome_transactions(id,owner_tenant_id,project_id,asset_id,base_version_id,raw_request) values($1,$2,$3,$4,$5,'{}'),($6,$7,$8,$9,$10,'{}'),($11,$12,$13,$14,$15,$16)", [A.tx,A.tenant,A.project,A.asset,A.version,B.tx,B.tenant,B.project,B.asset,B.version,NO_BINDING,A.tenant,A.project,A.asset,A.version,forged]);

    blueprintA = publishOutcomeBlueprint(createPrecisionEditBlueprintDefinition(), "2026-08-20T12:00:00.000Z");
    blueprintB = publishOutcomeBlueprint(createPrecisionEditBlueprintDefinition({ id: "50000000-0000-4000-8000-000000000002", outcomeType: "OTHER_OUTCOME" }), "2026-08-20T12:00:00.000Z");
    profileA = publishOutcomeRequirementProfile({ schemaVersion:"outcome-requirement-profile-v0.1",id:randomUUID(),version:1,previousVersionHash:null,blueprint:{id:blueprintA.id,version:blueprintA.version,hash:blueprintA.hash},policy:null,requirements:[{requirementId:"independent.minimum",semanticType:"text",critical:true,acceptedProvenance:["OBSERVED"],qualificationRule:{version:"1",cardinality:"SINGLE_VALUED",humanReviewRequired:false},dependencySelectors:[{identity:"asset.version",required:true}]},{requirementId:"independent.secondary",semanticType:"number",critical:false,acceptedProvenance:["SYSTEM_DERIVED"],qualificationRule:{version:"1",cardinality:"SINGLE_VALUED",humanReviewRequired:false},dependencySelectors:[]}] },"2026-08-20T12:00:00.000Z",blueprintA);
    profileB = publishOutcomeRequirementProfile({ schemaVersion:"outcome-requirement-profile-v0.1",id:randomUUID(),version:1,previousVersionHash:null,blueprint:{id:blueprintB.id,version:blueprintB.version,hash:blueprintB.hash},policy:null,requirements:[{requirementId:"independent.other",semanticType:"number",critical:true,acceptedProvenance:["OBSERVED"],qualificationRule:{version:"1",cardinality:"SINGLE_VALUED",humanReviewRequired:false},dependencySelectors:[]}]},"2026-08-20T12:00:00.000Z",blueprintB);
    const service = new Client({ connectionString: db(databaseUrl!, isolatedDatabase) }); await service.connect(); await service.query("set role service_role");
    for (const value of [blueprintA, blueprintB]) await service.query("select public.build002_publish_outcome_blueprint($1::jsonb)",[JSON.stringify(blueprintPayload(value))]);
    for (const value of [profileA, profileB]) await service.query("select public.build002_publish_outcome_requirement_profile($1::jsonb)",[JSON.stringify(profilePayload(value))]);
    bindingA = createOutcomeTransactionRequirementBinding({ownerTenantId:A.tenant,outcomeTransactionId:A.tx,blueprint:blueprintA,requirementProfile:profileA,boundAt:"2026-08-20T12:00:00.000Z"}); bindingB = createOutcomeTransactionRequirementBinding({ownerTenantId:B.tenant,outcomeTransactionId:B.tx,blueprint:blueprintB,requirementProfile:profileB,boundAt:"2026-08-20T12:00:00.000Z"});
    await service.query("select public.build002_bind_outcome_transaction_requirements($1::jsonb)",[JSON.stringify(bindingPayload(bindingA))]); await service.query("select public.build002_bind_outcome_transaction_requirements($1::jsonb)",[JSON.stringify(bindingPayload(bindingB))]); await service.end();
    const auth = new TenantAuthorityService(new Memberships(admin)); authorityA = await auth.resolveAuthority({principal:principal(A.principal)}); authorityB = await auth.resolveAuthority({principal:principal(B.principal)});
  }, 120_000);

  afterAll(async () => { await admin?.end(); if (databaseUrl && isolatedDatabase) { const root = new Client({connectionString:db(databaseUrl,"postgres")}); await root.connect(); await root.query(`drop database if exists "${isolatedDatabase}" with (force)`); await root.end(); } });

  it("observes a fresh PG17 migration chain and resolves exactly two persisted requirements", async () => {
    const version = await admin.query<{version:string}>("select version() as version"); expect(version.rows[0].version).toMatch(/PostgreSQL 17/i); const migrations = readdirSync(migrationsDir).filter((name) => name.endsWith(".sql")).sort(); expect(migrations).toHaveLength(29); expect(migrations[0]).toBe("20260809110000_intent_lab_build_001.sql"); expect(migrations.at(-1)).toBe("20260819150000_build_002_c0_c_transaction_requirement_binding.sql");
    const client = new Client({connectionString:db(databaseUrl!,isolatedDatabase)}); await client.connect(); await client.query("set role service_role"); const result = await resolver(client,A.tenant).resolve({authority:authorityA,outcomeTransactionId:A.tx}); expect(result.signalRequirements).toHaveLength(2); expect(result.binding.bindingHash).toBe(bindingA.bindingHash); expect(result.blueprint.hash).toBe(blueprintA.hash); expect(result.requirementProfile.hash).toBe(profileA.hash);
    for (const output of result.signalRequirements) { const source = profileA.requirements.find((item) => item.requirementId === output.requirementId); expect(source).toBeDefined(); expect(output.subjectKind).toBe("OUTCOME_TRANSACTION"); expect(output.blueprintId).toBe(blueprintA.id); expect(output.blueprintVersion).toBe(blueprintA.version); expect(output.blueprintHash).toBe(blueprintA.hash); expect(output.policyId).toBeNull(); expect(output.policyHash).toBeNull(); expect({requirementId:output.requirementId,semanticType:output.semanticType,critical:output.critical,acceptedProvenance:output.acceptedProvenance,qualificationRule:output.qualificationRule,dependencySelectors:output.dependencySelectors}).toEqual(source); }
    await client.end();
  });

  it("keeps requirement hashes stable across trusted timestamps", async () => { const client = new Client({connectionString:db(databaseUrl!,isolatedDatabase)}); await client.connect(); await client.query("set role service_role"); const [one,two] = await Promise.all([resolver(client,A.tenant,{clock:"2026-08-20T12:00:00.000Z"}).resolve({authority:authorityA,outcomeTransactionId:A.tx}),resolver(client,A.tenant,{clock:"2026-08-20T13:00:00.000Z"}).resolve({authority:authorityA,outcomeTransactionId:A.tx})]); expect(one.resolvedAt).not.toBe(two.resolvedAt); expect(one.signalRequirements.map((item)=>[item.requirementId,item.requirementDefinitionHash])).toEqual(two.signalRequirements.map((item)=>[item.requirementId,item.requirementDefinitionHash])); await client.end(); });

  it("fails closed for persisted membership and tenant authority states", async () => { const auth = new TenantAuthorityService(new Memberships(admin)); await fails(auth.resolveAuthority({principal:principal(NO_MEMBERSHIP_PRINCIPAL)}),"TENANT_MEMBERSHIP_REQUIRED"); await admin.query("update public.tenant_memberships set status='REVOKED',revoked_at=now() where id=$1",[A.membership]); await fails(auth.resolveAuthority({principal:principal(A.principal)}),"TENANT_MEMBERSHIP_REQUIRED"); await admin.query("update public.tenant_memberships set status='ACTIVE',revoked_at=null where id=$1",[A.membership]); await admin.query("update public.tenants set status='SUSPENDED' where id=$1",[A.tenant]); await fails(auth.resolveAuthority({principal:principal(A.principal)}),"TENANT_MEMBERSHIP_INACTIVE"); await admin.query("update public.tenants set status='REVOKED' where id=$1",[A.tenant]); await fails(auth.resolveAuthority({principal:principal(A.principal)}),"TENANT_MEMBERSHIP_INACTIVE"); await admin.query("update public.tenants set status='ACTIVE' where id=$1",[A.tenant]); await admin.query("insert into public.tenant_memberships(id,tenant_id,principal_id,role,status) values($1,$2,$3,'OWNER','ACTIVE')",["31000000-0000-4000-8000-000000000099",B.tenant,A.principal]); await fails(auth.resolveAuthority({principal:principal(A.principal)}),"TENANT_NOT_SELECTED"); await admin.query("delete from public.tenant_memberships where id=$1",["31000000-0000-4000-8000-000000000099"]); });

  it("rejects foreign, missing, and independently tampered authority", async () => {
    const client = new Client({connectionString:db(databaseUrl!,isolatedDatabase)}); await client.connect(); await client.query("set role service_role"); const before = await snapshot(admin);
    await fails(resolver(client,A.tenant).resolve({authority:authorityA,outcomeTransactionId:B.tx})); await fails(resolver(client,A.tenant).resolve({authority:authorityA,outcomeTransactionId:NO_BINDING}));
    await fails(resolver(client,A.tenant,{binding:async()=>({...bindingA,ownerTenantId:B.tenant})}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); await fails(resolver(client,A.tenant,{binding:async()=>({...bindingA,outcomeTransactionId:B.tx})}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); await fails(resolver(client,A.tenant,{binding:async()=>({...bindingA,bindingHash:"a".repeat(64)})}).resolve({authority:authorityA,outcomeTransactionId:A.tx}));
    await fails(resolver(client,A.tenant,{blueprint:async()=>null}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); await fails(resolver(client,A.tenant,{blueprint:async()=>({...blueprintA,outcomeType:"TAMPERED_OUTCOME"})}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); await fails(resolver(client,A.tenant,{profile:async()=>null}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); await fails(resolver(client,A.tenant,{profile:async()=>({...profileA,requirements:[{...profileA.requirements[0],semanticType:"tampered"},profileA.requirements[1]]})}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); await fails(resolver(client,A.tenant,{profile:async()=>profileB}).resolve({authority:authorityA,outcomeTransactionId:A.tx}));
    await expect(client.query("select public.build002_bind_outcome_transaction_requirements($1::jsonb)",[JSON.stringify({...bindingPayload(bindingA),owner_tenant_id:B.tenant})])).rejects.toThrow(); await fails(resolver(client,A.tenant).resolve({authority:authorityA,outcomeTransactionId:NO_BINDING})); expect(await snapshot(admin)).toEqual(before); await client.end();
  });

  it("proves four-session same-authority and tenant-isolated concurrency", async () => { const clients: Client[]=[]; try { for(let i=0;i<4;i+=1){const client=new Client({connectionString:db(databaseUrl!,isolatedDatabase)}); await client.connect(); await client.query("set role service_role"); clients.push(client);} const results=await Promise.all(clients.map((client)=>resolver(client,A.tenant).resolve({authority:authorityA,outcomeTransactionId:A.tx}))); expect(results.every((result)=>result.signalRequirements.length===2)).toBe(true); expect(results.map((result)=>result.signalRequirements.map((item)=>[item.requirementId,item.requirementDefinitionHash]))).toEqual(Array.from({length:4},()=>results[0].signalRequirements.map((item)=>[item.requirementId,item.requirementDefinitionHash]))); const [resultA,resultB]=await Promise.all([resolver(clients[0],A.tenant).resolve({authority:authorityA,outcomeTransactionId:A.tx}),resolver(clients[1],B.tenant).resolve({authority:authorityB,outcomeTransactionId:B.tx})]); expect(resultA.ownerTenantId).toBe(A.tenant); expect(resultB.ownerTenantId).toBe(B.tenant); expect(resultA.binding.blueprint.id).toBe(blueprintA.id); expect(resultB.binding.blueprint.id).toBe(blueprintB.id); } finally { await Promise.all(clients.map((client)=>client.end())); } });

  it("keeps success and failure resolution read-only and introduces no later-phase surface", async () => { const before=await snapshot(admin); const client=new Client({connectionString:db(databaseUrl!,isolatedDatabase)}); await client.connect(); await client.query("set role service_role"); await resolver(client,A.tenant).resolve({authority:authorityA,outcomeTransactionId:A.tx}); await fails(resolver(client,A.tenant).resolve({authority:authorityA,outcomeTransactionId:B.tx})); await fails(resolver(client,A.tenant,{binding:async()=>({...bindingA,bindingHash:"b".repeat(64)})}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); await fails(resolver(client,A.tenant,{blueprint:async()=>({...blueprintA,outcomeType:"TAMPERED_OUTCOME"})}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); await fails(resolver(client,A.tenant,{profile:async()=>({...profileA,requirements:[{...profileA.requirements[0],semanticType:"tampered"},profileA.requirements[1]]})}).resolve({authority:authorityA,outcomeTransactionId:A.tx})); expect(await snapshot(admin)).toEqual(before); await client.end(); const source=readFileSync(resolve(process.cwd(),"src/application/outcome/resolve-outcome-requirement-authority.ts"),"utf8"); expect(source).not.toMatch(/evaluateReadiness|qualifySignal|canDelegate|ExecutionAuthority|MutationLease|executor\.execute|StateCommit/); expect(readFileSync(resolve(process.cwd(),"docs/builds/build-002/002-C0-E/00_COMPOSED_AUTHORITY_PROOF.md"),"utf8")).toContain("CURRENT_REQUEST_AUTHORITY_SNAPSHOT"); expect(readdirSync(resolve(process.cwd(),"supabase/migrations")).filter((name)=>name.endsWith(".sql"))).toHaveLength(29); });
});
