-- BUILD 002-C1-D0 R1 diagnostic placeholder.
-- revoke insert on table public.build002_readiness_authority_commits from service_role;
-- build002_readiness_authority_marker_graph_coherent
-- before insert on public.build002_readiness_authority_commits
-- if tg_op <> 'INSERT'
-- v_snapshot.requirement_definition_hashes v_snapshot.signal_references
-- build002_signal_requirements build002_signals build002_readiness_qualifications
-- build002_signal_qualifications build002_qualification_signals
-- v_qualification.evaluator is distinct from v_readiness.evaluator
-- READINESS_AUTHORITY_SIGNAL_UNIVERSE_CHANGED
