from typing import Protocol
class PrivacyPolicyGuard(Protocol):
    def allow_external_processing(self, privacy_mode:str, raw_content:bool)->bool: ...
class SafePromptBuilder(Protocol):
    def build(self, masked_content:str, context:dict)->str: ...
class LLMProviderAdapter(Protocol):
    def analyze(self, safe_prompt:str)->dict: ...
# v0 uses deterministic heuristics. Future adapters MUST receive masked content only in safe mode.
