"use client";

import { ArrowRight, Bot, Boxes, CheckCircle2, CircleAlert, Eye, Layers3, LockKeyhole, Network, Sparkles } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { RevealOnScroll, StaggerGroup } from "@/components/landing/motion/motion-primitives";
import { DiagnosisRequestForm } from "@/components/landing/diagnosis-request-form";

export function ProblemSection() {
  const { t } = useLanguage();
  const pains = [t("Rework from incomplete information", "Retrabajo por información incompleta"), t("Weak handoffs between teams", "Handoffs débiles entre áreas"), t("Misinterpreted decisions", "Decisiones mal interpretadas"), t("AI and automation with poor context", "IA y automatización con contexto pobre")];
  return <section id="problema" className="problem-stage border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><RevealOnScroll><p className="section-kicker section-kicker-coral">{t("The failure before execution", "La falla antes de la ejecución")}</p><h2 className="section-display max-w-5xl">{t("Work does not always fail during execution. Often, it fails before.", "El trabajo no siempre falla en la ejecución. Muchas veces falla antes.")}</h2><p className="section-lead mt-6 max-w-3xl">{t("Losses begin when a company advances with information that is incomplete, ambiguous or disconnected from the next receiver. Virro makes that risk visible before it becomes work.", "Las pérdidas empiezan cuando una empresa avanza con información incompleta, ambigua o desconectada del siguiente receptor. Virro hace visible ese riesgo antes de que se convierta en trabajo.")}</p></RevealOnScroll><StaggerGroup className="pain-signal-grid mt-14">{pains.map((pain, index) => <article key={pain}><span>{String(index + 1).padStart(2, "0")}</span><p>{pain}</p><i /></article>)}</StaggerGroup></div></section>;
}

export function CategoryLayerSection() {
  const { t } = useLanguage();
  const tools = ["Chat", "Docs", "Tickets", "Design", "CRM", "BI", "Support", "Automation", "AI"];
  return <section id="categoria" className="category-layer-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="grid gap-8 lg:grid-cols-[.82fr_1.18fr] lg:items-end"><div><p className="section-kicker">{t("A new enterprise layer", "Una nueva capa empresarial")}</p><h2 className="section-display">{t("A layer to validate whether information is ready to advance.", "Una capa para validar si la información está lista para avanzar.")}</h2></div><p className="section-lead lg:justify-self-end">{t("Traditional tools communicate, store, design, report or execute information. Virro reviews whether that information has enough context, criteria and clarity for the next receiver to act.", "Las herramientas tradicionales comunican, almacenan, diseñan, reportan o ejecutan información. Virro revisa si esa información tiene suficiente contexto, criterio y claridad para que el siguiente receptor pueda actuar.")}</p></div><div className="category-layer-visual mt-14"><div className="category-tools"><p>{t("Before · scattered information", "Antes · información dispersa")}</p>{tools.map((tool) => <span key={tool}>{tool}</span>)}</div><div className="category-connector"><i /><ArrowRight size={16} /></div><div className="category-virro"><div><Layers3 size={22} /><strong>Virro</strong><span>Operating Understanding Layer</span></div><ul><li>{t("Context", "Contexto")}</li><li>{t("Criteria", "Criterio")}</li><li>{t("Clarity", "Claridad")}</li><li>{t("Receiver", "Receptor")}</li><li>{t("Readiness", "Readiness")}</li></ul></div><div className="category-connector"><i /><ArrowRight size={16} /></div><div className="category-result"><p>{t("After · operational signals", "Después · señales operativas")}</p><strong>{t("Readiness and receiver-specific deliverables", "Readiness y entregables por receptor")}</strong><div><span>{t("Better handoffs", "Mejores handoffs")}</span><span>{t("Fewer errors", "Menos errores")}</span><span>{t("Stronger decisions", "Mejores decisiones")}</span></div></div></div></div></section>;
}

export function HowItWorksSection() {
  const { t } = useLanguage();
  const steps = [
    ["Capture", t("Captures relevant operating information from real work.", "Captura información operativa relevante desde el trabajo real."), Boxes],
    ["Privacy Shield", t("Applies minimization and masking before analysis.", "Aplica minimización y máscara antes del análisis."), LockKeyhole],
    ["Readiness Gate", t("Estimates whether information can advance or still needs validation.", "Estima si la información puede avanzar o todavía necesita validación."), Eye],
    ["Pack Engine", t("Selects the right review pack for the receiver and operating flow.", "Selecciona el pack de revisión adecuado para el receptor y flujo operativo."), Layers3],
    ["Executive Report", t("Structures patterns and readiness as priorities for leadership.", "Estructura patrones y readiness como prioridades para dirección."), Sparkles],
  ] as const;
  return <section id="como-funciona" className="how-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="max-w-4xl"><p className="section-kicker">{t("How it works", "Cómo funciona")}</p><h2 className="section-display">{t("From real work to readiness, risks and actionable deliverables.", "Del trabajo real a readiness, riesgos y entregables accionables.")}</h2></div><StaggerGroup className="how-steps mt-14">{steps.map(([title, detail, Icon], index) => <article key={title}><div><span>0{index + 1}</span><Icon size={18} /></div><h3>{title}</h3><p>{detail}</p>{index < steps.length - 1 && <ArrowRight size={15} className="how-step-arrow" />}</article>)}</StaggerGroup></div></section>;
}

export function AuditPilotSection() {
  const { t } = useLanguage();
  const stages = [["Audit", t("Review one real flow with data protection.", "Revisamos un flujo real con protección de datos.")], ["Map", t("Deliver risks, readiness, patterns and quick wins.", "Entregamos riesgos, readiness, patrones y quick wins.")], ["Recommendation", t("Recommend the pack with the highest expected value.", "Recomendamos el pack con mayor valor esperado.")], ["Pilot", t("Activate one pack or a tailored bundle.", "Activamos un pack o bundle personalizado.")], ["Expansion", t("Scale to more areas and the enterprise layer.", "Escalamos hacia más áreas y la capa enterprise.")]];
  return <section id="auditoria" className="audit-pilot-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px] overflow-hidden rounded-[28px] border border-[var(--border)] bg-[var(--panel)] shadow-[0_45px_150px_rgba(0,0,0,.22)]"><div className="grid lg:grid-cols-[.7fr_1.3fr]"><div className="audit-pilot-offer p-7 md:p-12 lg:p-14"><p className="section-kicker">{t("Enterprise audit and pilot", "Auditoría y piloto enterprise")}</p><h2>{t("Start with an operational understanding audit.", "Empieza con una auditoría de entendimiento operativo.")}</h2><p>{t("Select a critical flow. Virro reviews real examples with data minimization, generates an Enterprise Understanding Map and recommends the pack or pilot with the highest expected value.", "Selecciona un flujo crítico. Virro revisa ejemplos reales con minimización de datos, genera un Enterprise Understanding Map y recomienda el pack o piloto con mayor valor esperado.")}</p><div className="audit-duration"><CheckCircle2 size={14} />{t("Initial audit · estimated 1–2 weeks", "Auditoría inicial · estimada de 1–2 semanas")}</div><div className="audit-pilot-actions mt-7"><a href="#solicitar-diagnostico" className="brand-primary-button">{t("Request an audit", "Solicitar auditoría")} <ArrowRight size={14} /></a><a href="#solicitar-diagnostico" className="brand-secondary-button">{t("Explore a pilot", "Explorar piloto")}</a></div></div><div className="audit-pilot-stages p-6 md:p-10 lg:p-14"><p>{t("Audit → Map → Recommendation → Pilot → Expansion", "Auditoría → Mapa → Recomendación → Piloto → Expansión")}</p>{stages.map(([title, detail], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{detail}</p></div>{index < stages.length - 1 && <i />}</article>)}</div></div><div className="audit-pilot-footer"><span>{t("Start with one flow", "Inicia con un flujo")}</span><span>{t("Combine capability blocks", "Combina bloques")}</span><span>{t("Tailored bundle", "Bundle personalizado")}</span><span>{t("Design partner path", "Ruta design partner")}</span></div><div className="audit-pilot-form-wrap p-6 md:p-10 lg:p-14"><DiagnosisRequestForm /></div></div></section>;
}

export function AIUnderstandingSection() {
  const { t } = useLanguage();
  const checks = [t("Intent", "Intención"), t("Relevant context", "Contexto relevante"), t("Rules and constraints", "Reglas y restricciones"), t("Expected format", "Formato esperado"), t("What not to assume", "Qué no debe asumir"), t("When to ask", "Cuándo debe preguntar")];
  return <section id="ai-understanding" className="ai-stage scroll-mt-24 border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto grid max-w-[1380px] gap-12 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div><p className="section-kicker">AI Understanding</p><h2 className="section-display">{t("Help AI understand your company better on the first attempt.", "Haz que la IA entienda mejor a tu empresa desde el primer intento.")}</h2><p className="section-lead mt-6">{t("The problem is not always the model. Often, AI receives vague instructions, oversized documents, repeated context or incomplete operating rules.", "El problema no siempre está en el modelo. Muchas veces la IA recibe instrucciones vagas, documentos enormes, contexto repetido o reglas operativas incompletas.")}</p><p className="ai-strong-line">{t("Virro prevents the company from paying AI to guess context that was never prepared.", "Virro evita que la empresa pague a la IA para adivinar contexto que nunca fue preparado.")}</p></div><div className="ai-context-visual visual-dark"><div className="ai-context-head"><Bot size={20} /><div><span>AI Input Readiness</span><strong>Context Pack · 64/100</strong></div><b>{t("Estimated", "Estimado")}</b></div><div className="ai-context-body"><div><p>{t("Virro reviews", "Virro revisa")}</p>{checks.map((item, index) => <span key={item}><i className={index < 4 ? "is-ready" : "is-gap"} />{item}</span>)}</div><div><p>{t("Operational deliverables", "Entregables operativos")}</p>{["AI Context Pack", "Instruction Bridge", "AI Output Check", "Safe Context Mode", "Token Waste Risk", "AI Understanding Debt"].map((item) => <span key={item}>{item}</span>)}</div></div><div className="ai-context-footer"><CircleAlert size={13} /><span>{t("High token waste risk: audience and evidence boundaries are missing.", "Riesgo alto de desperdicio de tokens: faltan audiencia y límites de evidencia.")}</span></div></div></div></section>;
}

export function PackagingSection() {
  const { t } = useLanguage(); const models = [["Understanding Audit", t("Discover where information is breaking.", "Descubre dónde se está rompiendo la información."), t("Map, readiness, risks, quick wins and recommended pack.", "Mapa, readiness, riesgos, quick wins y pack recomendado.")], ["Department Pack", t("Address one specific operating area.", "Ataca un área operativa específica."), t("One pack, one flow and receiver-specific deliverables.", "Un pack, un flujo y entregables por receptor.")], ["Multi-Pack Pilot", t("Connect several transfers across teams.", "Conecta varias transferencias entre áreas."), t("Combined packs, shared score model and executive map.", "Packs combinados, modelo de scores y mapa ejecutivo.")], ["Enterprise Understanding Layer", t("Operate Virro as transversal infrastructure.", "Opera Virro como infraestructura transversal."), t("Phased adoption, governance and enterprise visibility.", "Adopción por etapas, gobernanza y visibilidad enterprise.")]];
  return <section id="modelos" className="packaging-section px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="section-kicker">{t("Adoption models", "Modelos de adopción")}</p><h2 className="section-display">{t("Start with one flow. Scale into a shared layer.", "Empieza por un flujo. Escala hacia una capa común.")}</h2></div><p className="section-lead lg:justify-self-end">{t("Tailored packages, volume bundles and staged adoption keep the first engagement focused while preserving an enterprise path.", "Paquetes personalizados, bundles por volumen y adopción por etapas mantienen el primer engagement enfocado sin perder una ruta enterprise.")}</p></div><StaggerGroup className="packaging-grid mt-14">{models.map(([name, audience, deliverable], index) => <article key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{audience}</p><div><Sparkles size={13} />{deliverable}</div></article>)}</StaggerGroup></div></section>;
}

export function WhyNowSection() {
  const { t } = useLanguage(); return <section className="why-now-section px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="why-now-line"><Network size={21} /><span>{t("Chats · tickets · documents · meetings · CRM · BI · automation · AI", "Chats · tickets · documentos · juntas · CRM · BI · automatización · IA")}</span></div><h2>{t("Digital information already moves the entire company. Clarity is not guaranteed by adding more tools.", "La información digital ya mueve toda la empresa. La claridad no está garantizada por usar más herramientas.")}</h2><p>{t("The more teams and systems participate, the more important it becomes to validate whether information is ready to be understood. Virro creates that layer.", "Mientras más equipos y sistemas participan, más importante es validar si la información está lista para ser entendida. Virro crea esa capa.")}</p></div></section>;
}
