"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { PublicNavbar } from "@/components/landing/public-navbar";
import { DiagnosisRequestForm } from "@/components/landing/diagnosis-request-form";
import { AuditDeliverablesSection } from "@/components/landing/audit-deliverables-section";
import { CapabilityStatusBadge } from "@/components/ui/capability-status-badge";
import type { CapabilityStatus } from "@/lib/config/capability-registry";

export function CommercialSeoPage({ eyebrow, title, description, sections, cta = "Analizar un flujo", showAuditDeliverables = false, capabilityStatus }: { eyebrow: string; title: string; description: string; sections: Array<{ title: string; copy: string; points: string[] }>; cta?: string; showAuditDeliverables?: boolean; capabilityStatus?: CapabilityStatus }) {
  return <div className="public-landing min-h-screen overflow-hidden bg-[var(--app-bg)] text-[var(--text)]"><a href="#main-content" className="skip-link">Saltar al contenido principal</a><PublicNavbar /><main id="main-content"><section className="landing-hero relative min-h-[650px] px-5 pb-24 pt-40 md:px-8 md:pt-48"><div className="mx-auto max-w-[1380px]"><div className="flex flex-wrap items-center gap-3"><p className="section-kicker">{eyebrow}</p>{capabilityStatus && <CapabilityStatusBadge status={capabilityStatus} />}</div><h1 className="hero-headline mt-7 max-w-5xl text-5xl font-semibold leading-[1] tracking-[-.06em] md:text-7xl">{title}</h1><p className="hero-primary-copy mt-7 max-w-3xl text-lg leading-8">{description}</p><a href="#solicitar-auditoria" className="brand-primary-button mt-9">{cta} <ArrowRight aria-hidden="true" size={14} /></a></div></section><section className="px-5 py-24 md:px-8 md:py-32"><div className="mx-auto grid max-w-[1380px] gap-4 lg:grid-cols-3">{sections.map((section) => <article key={section.title} className="rounded-[24px] border border-[var(--border)] bg-[var(--panel)] p-7"><h2 className="text-2xl font-semibold tracking-[-.035em]">{section.title}</h2><p className="mt-4 text-xs leading-6 text-[var(--muted)]">{section.copy}</p><ul className="mt-6 space-y-3">{section.points.map((point) => <li key={point} className="flex gap-2 text-[10px] leading-5"><CheckCircle2 aria-hidden="true" size={13} className="mt-0.5 shrink-0 text-teal-300" />{point}</li>)}</ul></article>)}</div></section>{showAuditDeliverables && <AuditDeliverablesSection />}<section className="px-5 py-28 md:px-8"><div className="mx-auto max-w-[900px]"><DiagnosisRequestForm /></div></section></main><footer className="border-t border-[var(--border)] px-5 py-8 text-[10px] text-[var(--subtle)] md:px-8"><div className="mx-auto flex max-w-[1380px] items-center justify-between gap-4"><Link href="/" className="flex items-center gap-2 font-semibold text-[var(--text)]"><Image src="/brand/virro-icon.svg" alt="" width={24} height={20} />Virro</Link><span>Enterprise Understanding Layer · Evaluación probabilística</span></div></footer></div>;
}
