"use client";

import { ArrowRight, Bot, Boxes, CheckCircle2, CircleAlert, Eye, FileSearch, Layers3, LockKeyhole, Map, Network, PackageCheck, ShieldCheck, Sparkles } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { RevealOnScroll, StaggerGroup } from "@/components/landing/motion/motion-primitives";

export function ProblemSection() {
  const { t } = useLanguage();
  const pains = [t("Rework from incomplete information", "Retrabajo por información incompleta"), t("Errors from ambiguous criteria", "Errores por criterios ambiguos"), t("Weak handoffs between teams", "Handoffs débiles entre áreas"), t("Misinterpreted decisions", "Decisiones mal interpretadas"), t("Processes that are hard to transfer", "Procesos difíciles de transferir"), t("Generic AI output and wasted tokens", "IA genérica y tokens desperdiciados"), t("Operational knowledge that leaves with the team", "Conocimiento operativo que se pierde con el equipo")];
  return <section id="problema" className="problem-stage border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><RevealOnScroll><p className="section-kicker section-kicker-coral">{t("The failure before execution", "La falla antes de la ejecución")}</p><h2 className="section-display max-w-5xl">{t("Work does not always fail during execution. Often, it fails before.", "El trabajo no siempre falla en la ejecución. Muchas veces falla antes.")}</h2><p className="section-lead mt-6 max-w-3xl">{t("Losses begin when a company advances with information that is incomplete, ambiguous or disconnected from the next receiver. Virro makes that risk visible before it becomes work.", "Las pérdidas empiezan cuando una empresa avanza con información incompleta, ambigua o desconectada del siguiente receptor. Virro hace visible ese riesgo antes de que se convierta en trabajo.")}</p></RevealOnScroll><StaggerGroup className="pain-signal-grid mt-14">{pains.map((pain, index) => <article key={pain}><span>{String(index + 1).padStart(2, "0")}</span><p>{pain}</p><i /></article>)}</StaggerGroup></div></section>;
}

export function CategoryLayerSection() {
  const { t } = useLanguage();
  const tools = ["Chat", "Docs", "Tickets", "Design", "CRM", "BI", "Support", "Automation", "AI"];
  return <section id="categoria" className="category-layer-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="grid gap-8 lg:grid-cols-[.82fr_1.18fr] lg:items-end"><div><p className="section-kicker">{t("A new enterprise layer", "Una nueva capa empresarial")}</p><h2 className="section-display">{t("A new layer for the information that moves your company.", "Una nueva capa para la información que mueve tu empresa.")}</h2></div><p className="section-lead lg:justify-self-end">{t("Traditional tools communicate, store, design, report or execute information. Virro validates whether that information has enough context, criteria and clarity to move forward.", "Las herramientas tradicionales comunican, almacenan, diseñan, reportan o ejecutan información. Virro valida si esa información tiene suficiente contexto, criterio y claridad para avanzar.")}</p></div><div className="category-layer-visual mt-14"><div className="category-tools"><p>{t("Existing operating stack", "Stack operativo existente")}</p>{tools.map((tool) => <span key={tool}>{tool}</span>)}</div><div className="category-connector"><i /><ArrowRight size={16} /></div><div className="category-virro"><div><Layers3 size={22} /><strong>Virro</strong><span>Operating Understanding Layer</span></div><ul><li>{t("Context", "Contexto")}</li><li>{t("Criteria", "Criterio")}</li><li>{t("Clarity", "Claridad")}</li><li>{t("Receiver", "Receptor")}</li><li>{t("Readiness", "Readiness")}</li></ul></div><div className="category-connector"><i /><ArrowRight size={16} /></div><div className="category-result"><p>{t("Operational result", "Resultado operativo")}</p><strong>{t("Information ready to move forward", "Información lista para avanzar")}</strong><div><span>{t("Better handoffs", "Mejores handoffs")}</span><span>{t("Fewer errors", "Menos errores")}</span><span>{t("Stronger decisions", "Mejores decisiones")}</span></div></div></div></div></section>;
}

export function HowItWorksSection() {
  const { t } = useLanguage();
  const steps = [
    ["Understanding Capture", t("Meeting, screen, ticket, document, call, design, process or system signal.", "Junta, pantalla, ticket, documento, call, diseño, proceso o señal de sistema."), Boxes],
    ["Understanding Event", t("Creates a traceable unit around receiver, intent, context and expected action.", "Crea una unidad trazable alrededor de receptor, intención, contexto y acción esperada."), FileSearch],
    ["Readiness Gate", t("Estimates whether information can advance or still needs validation.", "Estima si la información puede avanzar o todavía necesita validación."), Eye],
    ["Output Bundle", t("Packages questions, checklist, handoff, Context Pack or brief for the receiver.", "Empaqueta preguntas, checklist, handoff, Context Pack o brief para el receptor."), PackageCheck],
    ["Living Understanding Map", t("Keeps flows, decisions, risks, tools and continuity connected.", "Mantiene conectados flujos, decisiones, riesgos, herramientas y continuidad."), Map],
    ["Executive Report", t("Turns patterns and readiness into priorities for leadership.", "Convierte patrones y readiness en prioridades para dirección."), Sparkles],
  ] as const;
  return <section id="como-funciona" className="how-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="max-w-4xl"><p className="section-kicker">{t("How it works", "Cómo funciona")}</p><h2 className="section-display">{t("From real work to a living understanding layer.", "Del trabajo real a una capa viva de entendimiento.")}</h2></div><StaggerGroup className="how-steps mt-14">{steps.map(([title, detail, Icon], index) => <article key={title}><div><span>0{index + 1}</span><Icon size={18} /></div><h3>{title}</h3><p>{detail}</p>{index < steps.length - 1 && <ArrowRight size={15} className="how-step-arrow" />}</article>)}</StaggerGroup></div></section>;
}

export function AuditPilotSection() {
  const { t } = useLanguage();
  const stages = [["Audit", t("Review one real flow with data protection.", "Revisamos un flujo real con protección de datos.")], ["Map", t("Deliver risks, readiness, patterns and quick wins.", "Entregamos riesgos, readiness, patrones y quick wins.")], ["Recommendation", t("Recommend the pack with the highest expected value.", "Recomendamos el pack con mayor valor esperado.")], ["Pilot", t("Activate one pack or a tailored bundle.", "Activamos un pack o bundle personalizado.")], ["Expansion", t("Scale to more areas and the enterprise layer.", "Escalamos hacia más áreas y la capa enterprise.")]];
  return <section id="auditoria" className="audit-pilot-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px] overflow-hidden rounded-[36px] border border-[var(--border)] bg-[var(--panel)] shadow-[0_45px_150px_rgba(0,0,0,.22)]"><div className="grid lg:grid-cols-[.7fr_1.3fr]"><div className="audit-pilot-offer p-7 md:p-12 lg:p-14"><p className="section-kicker">{t("Audit and pilot configurator", "Configurador de auditoría y piloto")}</p><h2>{t("Start with the flow where clarity is costing the most.", "Empieza por el flujo donde hoy cuesta más la claridad.")}</h2><p>{t("A focused audit reviews real examples, minimizes sensitive data and delivers a Living Understanding Map, quick wins and the recommended pack or combined bundle.", "Una auditoría enfocada revisa ejemplos reales, minimiza datos sensibles y entrega un Living Understanding Map, quick wins y el pack o bundle combinado recomendado.")}</p><div className="audit-duration"><CheckCircle2 size={14} />{t("Initial diagnosis · estimated 1–2 weeks", "Diagnóstico inicial · estimado de 1–2 semanas")}</div><a href="#solicitar-diagnostico" className="brand-primary-button">{t("Configure a critical-flow audit", "Configurar auditoría de flujo crítico")} <ArrowRight size={14} /></a></div><div className="audit-pilot-stages p-6 md:p-10 lg:p-14"><p>{t("Audit → Enterprise Understanding Map → Recommended Pack → Pilot → Enterprise Layer", "Audit → Enterprise Understanding Map → Pack recomendado → Piloto → Capa enterprise")}</p>{stages.map(([title, detail], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{detail}</p></div>{index < stages.length - 1 && <i />}</article>)}</div></div><div className="audit-pilot-footer"><span>{t("Start with one flow", "Inicia con un flujo")}</span><span>{t("Combine capability blocks", "Combina bloques")}</span><span>{t("Tailored bundle", "Bundle personalizado")}</span><span>{t("Design partner path", "Ruta design partner")}</span></div></div></section>;
}

export function AIUnderstandingSection() {
  const { t } = useLanguage();
  const checks = [t("Intent", "Intención"), t("Relevant context", "Contexto relevante"), t("Rules and constraints", "Reglas y restricciones"), t("Expected format", "Formato esperado"), t("What not to assume", "Qué no debe asumir"), t("When to ask", "Cuándo debe preguntar")];
  return <section id="ai-understanding" className="ai-stage scroll-mt-24 border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto grid max-w-[1380px] gap-12 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div><p className="section-kicker">AI Understanding</p><h2 className="section-display">{t("Help AI understand your company better on the first attempt.", "Haz que la IA entienda mejor a tu empresa desde el primer intento.")}</h2><p className="section-lead mt-6">{t("The problem is not always the model. Often, AI receives vague instructions, oversized documents, repeated context or incomplete operating rules.", "El problema no siempre está en el modelo. Muchas veces la IA recibe instrucciones vagas, documentos enormes, contexto repetido o reglas operativas incompletas.")}</p><p className="ai-strong-line">{t("Virro prevents the company from paying AI to guess context that was never prepared.", "Virro evita que la empresa pague a la IA para adivinar contexto que nunca fue preparado.")}</p></div><div className="ai-context-visual visual-dark"><div className="ai-context-head"><Bot size={20} /><div><span>AI Input Readiness</span><strong>Context Pack · 64/100</strong></div><b>{t("Estimated", "Estimado")}</b></div><div className="ai-context-body"><div><p>{t("Virro reviews", "Virro revisa")}</p>{checks.map((item, index) => <span key={item}><i className={index < 4 ? "is-ready" : "is-gap"} />{item}</span>)}</div><div><p>{t("Operational deliverables", "Entregables operativos")}</p>{["AI Context Pack", "Instruction Bridge", "AI Output Check", "Safe Context Mode", "Token Waste Risk", "AI Understanding Debt"].map((item) => <span key={item}>{item}</span>)}</div></div><div className="ai-context-footer"><CircleAlert size={13} /><span>{t("High token waste risk: audience and evidence boundaries are missing.", "Riesgo alto de desperdicio de tokens: faltan audiencia y límites de evidencia.")}</span></div></div></div></section>;
}

export function PrivacyShieldSection() {
  const { t } = useLanguage(); const points = [t("No raw data by default", "No raw data por defecto"), t("Pattern-first storage", "Almacenamiento pattern-first"), t("Anonymized Understanding Mode", "Anonymized Understanding Mode"), t("Pilot & Audit Safe Mode", "Pilot & Audit Safe Mode"), t("Customer-controlled scope", "Alcance bajo control del cliente"), t("Sensitive information masking", "Máscara de información sensible"), t("Reports without unnecessary identities", "Reportes sin identidades innecesarias")];
  return <section id="confianza" className="privacy-shield-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="privacy-shield-shell"><div className="privacy-shield-copy"><span className="privacy-icon"><LockKeyhole size={22} /></span><p className="section-kicker">Privacy Shield</p><h2>{t("Value without accumulating unnecessary sensitive information.", "Valor sin acumular información sensible innecesaria.")}</h2><p>{t("Virro reviews operational understanding patterns without becoming a repository of raw conversations. Minimization, masking and anonymization reduce exposure from the first pilot.", "Virro revisa patrones de entendimiento operativo sin convertirse en repositorio de conversaciones crudas. Minimización, máscara y anonimización reducen exposición desde el primer piloto.")}</p><strong>{t("Virro analyzes operational understanding, not people's identities.", "Virro analiza el entendimiento operativo, no la identidad de las personas.")}</strong></div><div className="privacy-points">{points.map((point, index) => <div key={point}><span>0{index + 1}</span><ShieldCheck size={15} /><p>{point}</p></div>)}</div></div><p className="privacy-footnote">{t("Less sensitive data accumulated. Smaller exposure surface. More confidence to analyze real flows. No system can promise zero risk; controls and scope are defined before real evidence is reviewed.", "Menos datos sensibles acumulados. Menor superficie de exposición. Más confianza para analizar flujos reales. Ningún sistema puede prometer riesgo cero; controles y alcance se definen antes de revisar evidencia real.")}</p></div></section>;
}

export function PackagingSection() {
  const { t } = useLanguage(); const models = [["Understanding Audit", t("Discover where information is breaking.", "Descubre dónde se está rompiendo la información."), t("Map, readiness, risks, quick wins and recommended pack.", "Mapa, readiness, riesgos, quick wins y pack recomendado.")], ["Department Pack", t("Address one specific operating area.", "Ataca un área operativa específica."), t("One pack, one flow and receiver-specific deliverables.", "Un pack, un flujo y entregables por receptor.")], ["Multi-Pack Pilot", t("Connect several transfers across teams.", "Conecta varias transferencias entre áreas."), t("Combined packs, shared score model and executive map.", "Packs combinados, modelo de scores y mapa ejecutivo.")], ["Enterprise Understanding Layer", t("Operate Virro as transversal infrastructure.", "Opera Virro como infraestructura transversal."), t("Phased adoption, governance and enterprise visibility.", "Adopción por etapas, gobernanza y visibilidad enterprise.")]];
  return <section id="modelos" className="packaging-section px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="section-kicker">{t("Adoption models", "Modelos de adopción")}</p><h2 className="section-display">{t("Start with one flow. Scale into a shared layer.", "Empieza por un flujo. Escala hacia una capa común.")}</h2></div><p className="section-lead lg:justify-self-end">{t("Tailored packages, volume bundles and staged adoption keep the first engagement focused while preserving an enterprise path.", "Paquetes personalizados, bundles por volumen y adopción por etapas mantienen el primer engagement enfocado sin perder una ruta enterprise.")}</p></div><StaggerGroup className="packaging-grid mt-14">{models.map(([name, audience, deliverable], index) => <article key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{audience}</p><div><Sparkles size={13} />{deliverable}</div></article>)}</StaggerGroup></div></section>;
}

export function WhyNowSection() {
  const { t } = useLanguage(); return <section className="why-now-section px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="why-now-line"><Network size={21} /><span>{t("Chats · tickets · documents · meetings · CRM · BI · automation · AI", "Chats · tickets · documentos · juntas · CRM · BI · automatización · IA")}</span></div><h2>{t("Digital information already moves the entire company. Clarity is not guaranteed by adding more tools.", "La información digital ya mueve toda la empresa. La claridad no está garantizada por usar más herramientas.")}</h2><p>{t("The more teams and systems participate, the more important it becomes to validate whether information is ready to be understood. Virro creates that layer.", "Mientras más equipos y sistemas participan, más importante es validar si la información está lista para ser entendida. Virro crea esa capa.")}</p></div></section>;
}
