"use client";

import Link from "next/link";
import { ArrowRight, Eye, FileCheck2, Inbox, LayoutDashboard, Palette, PackageCheck, Workflow } from "lucide-react";
import { PublicNavbar } from "@/components/landing/public-navbar";
import { useLanguage } from "@/components/i18n/language-provider";

const areas = [
  { href: "/app", icon: LayoutDashboard, en: "Overview", es: "Vista general", enCopy: "A simulated workspace view with directional evidence and limitations.", esCopy: "Una vista simulada del workspace con evidencia direccional y limitaciones.", status: "demo" },
  { href: "/app/inbox", icon: Inbox, en: "Understanding Inbox", es: "Bandeja de entendimiento", enCopy: "Structure one input as an auditable event without retaining it in this public demo.", esCopy: "Estructura un input como evento auditable sin retenerlo en esta demo pública.", status: "demo" },
  { href: "/app/product-delivery", icon: PackageCheck, en: "Product Delivery", es: "Product Delivery", enCopy: "Follow product intent through development and QA evidence.", esCopy: "Sigue la intención de producto a través de evidencia de desarrollo y QA.", status: "demo" },
  { href: "/app/design-delivery", icon: Palette, en: "Design Delivery", es: "Design Delivery", enCopy: "Review brief, version, assets and approval evidence at a design handoff.", esCopy: "Revisa brief, versión, assets y evidencia de aprobación en un handoff de diseño.", status: "demo" },
  { href: "/app/handoff-intelligence", icon: Workflow, en: "Operational Handoff", es: "Operational Handoff", enCopy: "See what the receiver still needs before accepting a transfer.", esCopy: "Muestra lo que el receptor todavía necesita antes de aceptar una transferencia.", status: "demo" },
  { href: "/app/privacy-trust", icon: Eye, en: "Evidence & Trust", es: "Evidencia y confianza", enCopy: "Inspect the policy preview, evidence boundaries and human-review rules.", esCopy: "Inspecciona la vista de política, límites de evidencia y reglas de revisión humana.", status: "preview" },
] as const;

export function DemoHub() {
  const { locale, t } = useLanguage();
  return <div className="public-landing min-h-screen bg-[var(--app-bg)] text-[var(--text)]"><a href="#demo-main" className="skip-link">{t("Skip to demo areas", "Saltar a las áreas de demo")}</a><PublicNavbar /><main id="demo-main" className="px-5 pb-28 pt-40 md:px-8 md:pt-48"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">Virro Enterprise Demo</p><h1 className="section-display mt-6 max-w-5xl">{t("Six areas. One operational understanding flow.", "Seis áreas. Un solo flujo de entendimiento operativo.")}</h1><p className="section-lead mt-6 max-w-4xl">{t("Every area uses simulated data. It demonstrates the product model without claiming a productive connector, client result or automated verdict.", "Todas las áreas usan datos simulados. Demuestran el modelo de producto sin afirmar un conector productivo, un resultado de cliente ni un veredicto automatizado.")}</p><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{areas.map(({ href, icon: Icon, en, es, enCopy, esCopy, status }, index) => <article key={href} className="flex min-h-64 flex-col rounded-[24px] border border-[var(--border)] bg-[var(--panel)] p-6"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-[var(--panel-soft)] text-[var(--brand-blue)]"><Icon aria-hidden="true" size={19} /></span><span className="rounded-full border border-sky-300/20 bg-sky-300/[.06] px-2.5 py-1 text-[8px] font-semibold uppercase tracking-[.08em] text-sky-200">{status === "demo" ? t("Simulated demo", "Demo simulada") : t("Policy preview", "Vista de política")}</span></div><p className="mt-6 text-[9px] text-[var(--subtle)]">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-2 text-xl font-semibold">{locale === "es" ? es : en}</h2><p className="mt-3 flex-1 text-xs leading-6 text-[var(--muted)]">{locale === "es" ? esCopy : enCopy}</p><Link href={href} className="brand-secondary-button mt-6 self-start">{t("Open area", "Abrir área")} <ArrowRight aria-hidden="true" size={13} /></Link></article>)}</div><div className="mt-10 flex flex-col gap-3 rounded-2xl border border-amber-300/20 bg-amber-300/[.04] p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><FileCheck2 aria-hidden="true" className="mt-0.5 shrink-0 text-amber-200" size={17} /><p className="max-w-3xl text-[10px] leading-5 text-[var(--muted)]">{t("Need evidence from a real workflow? The assisted Flow Understanding Audit is a separate engagement with agreed scope, privacy and deletion terms.", "¿Necesitas evidencia de un flujo real? Flow Understanding Audit es un engagement asistido separado, con alcance, privacidad y eliminación acordados.")}</p></div><Link href="/flow-audit" className="brand-primary-button shrink-0">Flow Understanding Audit</Link></div></div></main></div>;
}
