"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, LockKeyhole, ShieldCheck } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";

const missingContext = ["Alcance mínimo aceptable", "Dependencias técnicas", "Criterios de seguridad", "Responsables", "Impacto en QA", "Plan de release"];
const affectedTeams = ["Producto", "Arquitectura", "Desarrollo", "QA", "DevOps", "Soporte"];
const affectedArtifacts = ["Historia de usuario", "Criterios de aceptación", "Casos de prueba", "Plan de release", "Documentación", "Contexto para IA"];
const criticalQuestions = [
  "¿Qué capacidades de autenticación Enterprise son obligatorias para este release?",
  "¿Qué dependencias técnicas o de seguridad modifican la fecha?",
  "¿Quién puede aprobar una reducción de alcance si el impacto no cabe en el calendario actual?",
];

export function UnderstandingEventDemo() {
  const { t } = useLanguage();
  return <section id="demo" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]">
    <header className="max-w-4xl"><p className="section-kicker">Understanding Event · {t("Simulated demo", "Demo simulada")}</p><h2 className="section-display">{t("Follow one operational change from signal to action.", "Sigue un cambio operativo desde la señal hasta la acción.")}</h2><p className="section-lead mt-6">{t("A complete, simulated example of how Virro structures an event without presenting the score as an absolute truth.", "Un ejemplo completo y simulado de cómo Virro estructura un evento sin presentar el score como una verdad absoluta.")}</p></header>
    <div className="mt-12 grid gap-4 lg:grid-cols-[.82fr_1.18fr]">
      <article className="rounded-[26px] border border-[var(--border)] bg-[var(--panel)] p-6 md:p-8"><span className="rounded-full border border-sky-400/20 bg-sky-400/[.08] px-3 py-1 text-[9px] font-semibold uppercase tracking-[.12em] text-sky-300">{t("Simulated input", "Entrada simulada")}</span><blockquote className="mt-6 text-xl font-semibold leading-8 tracking-[-.025em]">“{t("The priority changed. The launch must now include enterprise authentication, but the agreed date must remain unchanged.", "La prioridad cambió. El lanzamiento ahora debe incluir autenticación empresarial, pero la fecha acordada debe mantenerse.")}”</blockquote><dl className="mt-8 grid gap-4 text-xs sm:grid-cols-2"><Info term={t("Event type", "Tipo de evento")} value={t("Critical scope change", "Cambio crítico de alcance")} /><Info term={t("Recommended pack", "Pack recomendado")} value="Change Understanding + Product Delivery" /><Info term={t("Estimated readiness", "Readiness estimado")} value="54/100" /><Info term={t("Confidence", "Confianza")} value={t("Medium", "Media")} /></dl><div className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/[.06] p-4"><span className="text-[9px] uppercase tracking-[.12em] text-rose-300">{t("Main risk", "Riesgo principal")}</span><p className="mt-2 text-xs leading-5">{t("Keeping the date without recalculating technical, QA and security impact.", "Mantener la fecha sin recalcular impacto técnico, QA y seguridad.")}</p></div></article>
      <article className="rounded-[26px] border border-[var(--border)] bg-[var(--panel-soft)] p-6 md:p-8"><div className="grid gap-6 md:grid-cols-3"><List title={t("Missing context", "Contexto faltante")} items={missingContext} /><List title={t("Affected teams", "Equipos afectados")} items={affectedTeams} /><List title={t("Affected artifacts", "Artefactos afectados")} items={affectedArtifacts} /></div><div className="mt-7 rounded-2xl border border-teal-400/20 bg-teal-400/[.06] p-5"><span className="text-[9px] uppercase tracking-[.12em] text-teal-300">{t("Next action", "Siguiente acción")}</span><p className="mt-2 text-sm font-semibold leading-6">{t("Validate minimum scope, dependencies and the decision owner before keeping the launch date.", "Validar alcance mínimo, dependencias y propietario de la decisión antes de mantener la fecha de lanzamiento.")}</p></div><div className="mt-7"><h3 className="text-xs font-semibold">{t("Critical questions", "Preguntas críticas")}</h3><ol className="mt-3 grid gap-2">{criticalQuestions.map((question, index) => <li key={question} className="flex gap-3 rounded-xl border border-[var(--border)] bg-[var(--panel)] p-4 text-[11px] leading-5"><span className="font-semibold text-[var(--brand-blue)]">{String(index + 1).padStart(2, "0")}</span><span>{question}</span></li>)}</ol></div></article>
    </div><p className="mt-4 flex flex-wrap items-center gap-2 text-[10px] text-[var(--subtle)]"><ShieldCheck aria-hidden="true" size={13} />{t("Simulated data · Probabilistic scores · Human review required", "Datos simulados · Scores probabilísticos · Revisión humana requerida")}</p>
  </div></section>;
}

export function ClientOutcomesSection() {
  const { t } = useLanguage();
  const outcomes = ["Enterprise Understanding Map", "Mapa de flujos críticos", "Baseline de Meaning Loss", "Readiness por evento", "Contexto faltante", "Riesgos de interpretación", "Mapas de impacto ante cambios", "Estándares de handoff", "Contexto operativo para IA", "Reportes ejecutivos", "Siguientes acciones por equipo"];
  return <section id="resultados" className="border-y border-[var(--border)] bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">{t("Client outcomes", "Resultados para el cliente")}</p><h2 className="section-display max-w-5xl">{t("What Virro turns into operational understanding", "Lo que Virro convierte en entendimiento operativo")}</h2><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{outcomes.map((item) => <div key={item} className="flex min-h-16 items-center gap-3 rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-4 text-xs font-semibold"><CheckCircle2 aria-hidden="true" size={15} className="shrink-0 text-teal-300" />{item}</div>)}</div><p className="mt-10 max-w-3xl border-l-2 border-[var(--brand-coral)] pl-5 text-lg font-semibold leading-8">{t("A point tool solves one task. Virro keeps the whole operation understandable.", "Una herramienta puntual resuelve una tarea. Virro mantiene entendible la operación completa.")}</p></div></section>;
}

export function EnterprisePrivacySection() {
  const { t } = useLanguage();
  const principles = ["Enmascaramiento de información delicada", "Procesamiento transitorio", "No almacenamiento de contenido crudo por defecto", "Conservación de señales de entendimiento", "Aislamiento por empresa", "Revisión humana", "Sin vigilancia de empleados"];
  const flow = ["Recibir", "Enmascarar", "Analizar", "Descartar contenido crudo", "Conservar señales seguras", "Generar reporte"];
  return <section id="privacidad" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px] rounded-[30px] border border-[var(--border)] bg-[var(--panel)] p-6 md:p-12"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><LockKeyhole aria-hidden="true" className="text-[var(--brand-blue)]" /><p className="section-kicker mt-5">Privacy Shield</p><h2 className="section-display text-[2.4rem]">{t("Understanding without becoming another repository of private information", "Entendimiento sin convertirte en otro repositorio de información privada")}</h2><p className="section-lead mt-6">{t("Virro is designed to analyze operational information without storing private conversations or raw enterprise content by default.", "Virro está diseñado para analizar información operativa sin almacenar conversaciones privadas ni contenido empresarial crudo por defecto.")}</p><div className="mt-7 space-y-2 rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-5 font-mono text-[11px]"><p>████████ → [PERSON_1]</p><p>████████ → [CLIENT_1]</p><p>████████ → [EMAIL_1]</p></div></div><div><ol className="flex flex-wrap gap-2" aria-label={t("Privacy processing flow", "Flujo de privacidad")}>{flow.map((step, index) => <li key={step} className="flex items-center gap-2 rounded-full border border-[var(--border)] px-3 py-2 text-[9px] font-semibold"><span className="text-[var(--brand-blue)]">{index + 1}</span>{step}{index < flow.length - 1 && <ArrowRight aria-hidden="true" size={11} />}</li>)}</ol><ul className="mt-8 grid gap-3 sm:grid-cols-2">{principles.map((item) => <li key={item} className="flex gap-3 rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-4 text-[11px] leading-5"><ShieldCheck aria-hidden="true" size={14} className="mt-0.5 shrink-0 text-teal-300" />{item}</li>)}</ul><p className="mt-6 text-[10px] text-[var(--subtle)]">{t("Implementation status is documented in the Trust Center; no unverified certification is claimed.", "El estado de implementación se documenta en el Trust Center; no se afirma ninguna certificación no verificada.")}</p></div></div></div></section>;
}

export function EnterprisePilotSection() {
  const { t } = useLanguage();
  return <section id="piloto" className="px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px] rounded-[28px] border border-[var(--border)] bg-[var(--panel-soft)] p-7 md:p-12"><p className="section-kicker">{t("Enterprise pilot", "Piloto Enterprise")}</p><h2 className="section-display max-w-4xl">{t("Demonstrate impact inside a real workflow", "Demuestra el impacto dentro de un flujo real")}</h2><p className="section-lead mt-6 max-w-4xl">{t("The Virro pilot runs on one critical flow for six to eight weeks. It configures standards, analyzes events, measures readiness and compares results before and after.", "El piloto de Virro se ejecuta sobre un flujo crítico durante seis a ocho semanas. Configura estándares, analiza eventos, mide readiness y compara resultados antes y después.")}</p><a href="#solicitar-auditoria" data-analytics-event="pilot_cta_click" className="brand-secondary-button mt-8">{t("Explore Enterprise pilot", "Explorar piloto Enterprise")} <ArrowRight aria-hidden="true" size={14} /></a><p className="mt-4 text-[10px] text-[var(--subtle)]">{t("Expected impact is evaluated with probabilistic evidence; results are not guaranteed.", "El impacto esperado se evalúa con evidencia probabilística; no se garantizan resultados.")}</p></div></section>;
}

export function FinalEnterpriseCta() {
  const { t } = useLanguage();
  return <section className="px-5 pb-24 pt-10 md:px-8 md:pb-36"><div className="mx-auto max-w-[1380px] rounded-[30px] border border-[var(--border)] bg-[linear-gradient(135deg,color-mix(in_srgb,var(--panel)_88%,var(--brand-blue)_12%),var(--panel))] p-7 md:p-14"><h2 className="section-display max-w-5xl">{t("What does it cost when every team understands a different version?", "¿Cuánto cuesta que cada equipo entienda una versión distinta?")}</h2><p className="section-lead mt-6 max-w-4xl">{t("Select one critical flow. Virro can help identify where context is lost, what is slowing execution and what should be corrected before scaling.", "Selecciona un flujo crítico. Virro puede ayudarte a identificar dónde se pierde contexto, qué está frenando la ejecución y qué convendría corregir antes de escalar.")}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#solicitar-auditoria" className="brand-primary-button">{t("Request an audit", "Solicitar auditoría")} <ArrowRight aria-hidden="true" size={14} /></a><Link href="/app" className="brand-secondary-button">{t("View Enterprise demo", "Ver demo Enterprise")}</Link></div></div></section>;
}

function Info({ term, value }: { term: string; value: string }) { return <div><dt className="text-[9px] uppercase tracking-[.12em] text-[var(--subtle)]">{term}</dt><dd className="mt-1.5 font-semibold">{value}</dd></div>; }
function List({ title, items }: { title: string; items: string[] }) { return <div><h3 className="text-[10px] font-semibold uppercase tracking-[.1em] text-[var(--subtle)]">{title}</h3><ul className="mt-3 space-y-2">{items.map((item) => <li key={item} className="flex gap-2 text-[10px] leading-4"><CheckCircle2 aria-hidden="true" size={11} className="mt-0.5 shrink-0 text-[var(--brand-blue)]" />{item}</li>)}</ul></div>; }
