"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, LockKeyhole, ShieldCheck } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { DiagnosisRequestForm } from "@/components/landing/diagnosis-request-form";
import { EntryModeCard } from "@/components/landing/entry-mode-card";
import { UseCaseCard } from "@/components/landing/use-case-card";
import { entryModeRegistry, useCaseRegistry } from "@/lib/config/capability-registry";
import { PrivacyRuntimeCard } from "@/components/privacy/privacy-runtime-card";

export function CentralFailuresSection() {
  const { t } = useLanguage();
  const failures = [
    ["Readiness Failure", t("Work tries to start without enough evidence that the receiver can execute it.", "El trabajo intenta comenzar sin evidencia suficiente de que el receptor pueda ejecutarlo.")],
    ["Change Integrity Failure", t("Priority, scope or a decision changes, but stories, tests, documentation and dependent teams are not updated at the same time.", "La prioridad, alcance o decisión cambia, pero historias, pruebas, documentación y equipos dependientes no se actualizan al mismo tiempo.")],
  ];
  return <section id="fallos" className="border-y border-[var(--border)] bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">{t("Two central failures", "Dos fallos centrales")}</p><div className="mt-10 grid gap-4 lg:grid-cols-2">{failures.map(([title, copy], index) => <article key={title} className="rounded-[26px] border border-[var(--border)] bg-[var(--panel)] p-7 md:p-9"><span className="text-[10px] font-semibold text-[var(--brand-coral)]">0{index + 1}</span><h2 className="mt-5 text-3xl font-semibold tracking-[-.04em]">{title}</h2><p className="section-lead mt-5">{copy}</p></article>)}</div></div></section>;
}

export function InitialProductSection() {
  const { t } = useLanguage();
  return <section id="formas-entrada" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">{t("Ways to begin", "Formas de entrada")}</p><h2 className="section-display max-w-5xl">{t("Start from the workflow, not from a required tool.", "Empieza desde el flujo, no desde una herramienta obligatoria.")}</h2><p className="section-lead mt-6 max-w-4xl">{t("Audit, controlled import, connectors and API are different entry modes. Their status is shown explicitly.", "Auditoría, importación controlada, conectores y API son formas de entrada distintas. Su estado se muestra explícitamente.")}</p><div className="mt-12 grid gap-4 md:grid-cols-2">{entryModeRegistry.map(entry => <EntryModeCard key={entry.id} entry={entry} />)}</div></div></section>;
}

export function ShadowScanSection() {
  const { t } = useLanguage();
  const steps = [t("Connect Jira", "Conecta Jira"), t("Select one project", "Selecciona un proyecto"), t("Virro observes", "Virro observa"), t("Evaluate signal sufficiency", "Evalúa suficiencia de señal"), t("Identify readiness and changes", "Identifica readiness y cambios"), t("Deliver a private report", "Entrega un reporte privado"), t("Activate Advisory in the same flow", "Activa Advisory dentro del mismo flujo")];
  const trust = [t("Read only", "Solo lectura"), t("One project", "Un proyecto"), t("Revocable", "Revocable"), t("No comments", "Sin comentarios"), t("No blocking", "Sin bloqueo"), t("No raw content stored by default", "Sin contenido crudo almacenado por defecto")];
  return <section id="shadow-scan" className="scroll-mt-24 border-y border-[var(--border)] bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">Shadow Scan</p><h2 className="section-display max-w-5xl">{t("Observe before adding a gate.", "Observa antes de agregar un gate.")}</h2><ol className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{steps.map((step, index) => <li key={step} className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-5"><span className="text-[10px] font-semibold text-[var(--brand-blue)]">{String(index + 1).padStart(2, "0")}</span><p className="mt-3 text-xs font-semibold leading-5">{step}</p></li>)}</ol><div className="mt-8 flex flex-wrap gap-2">{trust.map((item) => <span key={item} className="rounded-full border border-[var(--border)] bg-[var(--panel)] px-3 py-2 text-[9px] font-semibold"><ShieldCheck aria-hidden="true" className="mr-2 inline text-teal-300" size={12} />{item}</span>)}</div><div className="mt-12 rounded-[26px] border border-amber-300/20 bg-amber-300/[.05] p-7 md:p-9"><div className="flex gap-4"><CircleAlert aria-hidden="true" className="shrink-0 text-amber-300" /><div><p className="section-kicker text-amber-300">Signal Sufficiency</p><h3 className="mt-3 text-3xl font-semibold tracking-[-.04em]">{t("Virro also knows when it should not offer an opinion.", "Virro también sabe cuándo no debería opinar.")}</h3><p className="section-lead mt-5">{t("When a ticket is too unstructured, depends on an unavailable meeting or references sources without access, Virro does not force a score.", "Cuando un ticket es demasiado desestructurado, depende de una reunión no disponible o referencia fuentes sin acceso, Virro no fuerza un score.")}</p><p className="mt-6 inline-flex rounded-full border border-amber-300/25 px-3 py-2 text-[10px] font-semibold text-amber-200">{t("Insufficient signal", "Señal insuficiente")}</p><p className="mt-3 text-xs leading-5 text-[var(--muted)]">{t("The available information does not make it possible to determine reliably whether the work was ready.", "La información disponible no permite determinar de forma confiable si el trabajo estaba listo.")}</p></div></div></div></div></section>;
}

export function UnderstandingEventDemo() {
  const { t } = useLanguage();
  const checks = ["Brief e intención", "Formatos y assets", "Versiones vigentes", "Restricciones", "Criterios de aprobación"];
  return <section id="design-delivery" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">Design Delivery · {t("Simulated scenario", "Escenario simulado")}</p><h2 className="section-display max-w-5xl">{t("When the deliverable is design, understanding can also be lost.", "Cuando la entrega es diseño, el entendimiento también puede perderse.")}</h2><p className="section-lead mt-6 max-w-4xl">{t("Virro validates whether the brief, intent, formats, versions, assets, restrictions and approval criteria are sufficiently clear before delivery or production.", "Virro valida si el brief, la intención, los formatos, las versiones, los assets, las restricciones y los criterios de aprobación están suficientemente claros antes de entregar o producir.")}</p><div className="mt-12 grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><article className="rounded-[26px] border border-[var(--border)] bg-[var(--panel)] p-7"><span className="text-[9px] uppercase tracking-[.12em] text-[var(--subtle)]">{t("Situation", "Situación")}</span><blockquote className="mt-5 text-xl font-semibold leading-8">{t("A design may look finished and still not be ready because copy is unapproved, a variant is missing, feedback conflicts or the delivered version is not current.", "Un diseño puede verse terminado y aun así no estar listo porque el copy no está aprobado, falta una variante, el feedback está contradicho o la versión enviada no es la vigente.")}</blockquote><p className="mt-7 inline-flex rounded-full border border-amber-300/20 bg-amber-300/[.05] px-3 py-2 text-[10px] font-semibold text-amber-200">{t("Handoff requires clarification", "Handoff requiere aclaración")}</p></article><article className="rounded-[26px] border border-[var(--border)] bg-[var(--panel-soft)] p-7"><h3 className="text-xs font-semibold">{t("Evidence Virro reviews", "Evidencia que Virro revisa")}</h3><ul className="mt-4 grid gap-2 sm:grid-cols-2">{checks.map((item) => <li key={item} className="flex gap-2 rounded-xl border border-[var(--border)] bg-[var(--panel)] p-3 text-[10px]"><CheckCircle2 aria-hidden="true" size={12} className="shrink-0 text-[var(--brand-blue)]" />{item}</li>)}</ul><a href="#solicitar-auditoria" className="brand-secondary-button mt-7">{t("Analyze a design workflow", "Analizar un flujo de diseño")} <ArrowRight aria-hidden="true" size={14} /></a><p className="mt-4 text-[9px] text-[var(--subtle)]">{t("No productive Figma integration is claimed.", "No se afirma una integración productiva con Figma.")}</p></article></div></div></section>;
}

export function GradualitySection() {
  const { t } = useLanguage(); const stages = [["Shadow Mode", "Disponible"], ["Advisory Gate", "Disponible"], ["Confirmation Gate", "Planeado"], ["Policy Gate", "Visión futura"], ["Handoff Acceptance SLA", "Visión futura"]];
  return <section id="change-integrity" className="scroll-mt-24 border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">Change Integrity</p><h2 className="section-display max-w-5xl">{t("Add control gradually, after observing the real workflow.", "Agrega control gradualmente, después de observar el flujo real.")}</h2><div className="mt-12 grid gap-3 lg:grid-cols-5">{stages.map(([name, state], index) => <article key={name} className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-5"><span className="text-[9px] text-[var(--subtle)]">0{index + 1}</span><h3 className="mt-4 text-sm font-semibold">{name}</h3><p className={`mt-5 text-[9px] font-semibold uppercase tracking-[.1em] ${state === "Disponible" ? "text-teal-300" : "text-[var(--subtle)]"}`}>{state}</p></article>)}</div><p className="mt-6 text-[10px] text-[var(--subtle)]">{t("Confirmation is planned. Policy and SLA are future capabilities subject to calibration.", "Confirmation está planeado. Policy y SLA son capacidades futuras sujetas a calibración.")}</p></div></section>;
}

export function FutureApplicationsSection() {
  const { t } = useLanguage();
  return <section id="casos-uso" className="scroll-mt-24 bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">{t("Universal use cases", "Casos de uso universales")}</p><h2 className="section-display max-w-5xl">{t("Understanding follows the work, regardless of department.", "El entendimiento sigue al trabajo, sin importar el área.")}</h2><p className="section-lead mt-6 max-w-4xl">{t("Each case separates what Virro looks for from the outcome that must later be confirmed.", "Cada caso separa lo que Virro busca del outcome que después debe confirmarse.")}</p><div className="mt-12 grid gap-3 lg:grid-cols-2 xl:grid-cols-3">{useCaseRegistry.map(useCase => <UseCaseCard key={useCase.id} useCase={useCase} />)}</div><p className="mt-6 text-[10px] text-[var(--subtle)]">{t("A status describes the current delivery model; it does not imply that every connector or automated capability is available.", "El estado describe el modelo actual de entrega; no implica que todos los conectores o capacidades automatizadas estén disponibles.")}</p></div></section>;
}

export function EnterprisePrivacySection() {
  const { t } = useLanguage(); const flow = ["Receive", "Mask", "Analyze", "Discard raw content", "Store safe signals", "Report"]; const principles = ["Acceso mínimo", "Procesamiento limitado", "No entrenamiento cruzado entre clientes", "Eliminación", "Aislamiento", "Revisión humana", "Sin vigilancia"];
  const runtimes = [
    { title: t("Public lead form", "Formulario público"), status: "available" as const, receives: t("Contact and workflow description fields; no files.", "Campos de contacto y descripción del flujo; sin archivos."), rawRetention: t("Delivered to the configured lead channel; governed by the privacy notice.", "Enviado al canal de leads configurado; sujeto al aviso de privacidad."), safeSignals: t("No analysis signals are generated in this surface.", "Esta superficie no genera señales de análisis."), limitation: t("This form is not the Virro Core analysis runtime.", "Este formulario no es el runtime de análisis de Virro Core.") },
    { title: t("Assisted audit", "Auditoría asistida"), status: "assisted" as const, receives: t("A controlled, agreed sample.", "Una muestra controlada y acordada."), rawRetention: t("Defined per engagement; never implied by the public demo.", "Definida por engagement; nunca inferida desde la demo pública."), safeSignals: t("Findings, gaps, evidence coverage and limitations.", "Hallazgos, brechas, cobertura de evidencia y limitaciones."), limitation: t("Scope and deletion terms require an agreed audit plan.", "Alcance y eliminación requieren un plan de auditoría acordado.") },
    { title: "Virro Core · Safe mode", status: "pilot" as const, receives: t("Masked operational content through an authenticated tenant request.", "Contenido operativo enmascarado mediante una solicitud autenticada por tenant."), rawRetention: "No · raw_stored=false", safeSignals: t("Metadata, readiness, risks, patterns and audit trace.", "Metadata, readiness, riesgos, patrones y traza de auditoría."), limitation: t("Technical foundation; production controls depend on the validated pilot deployment.", "Base técnica; los controles productivos dependen del despliegue validado del piloto.") },
  ];
  return <section id="privacidad" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px] rounded-[30px] border border-[var(--border)] bg-[var(--panel)] p-7 md:p-12"><LockKeyhole aria-hidden="true" className="text-[var(--brand-blue)]" /><p className="section-kicker mt-5">Privacy & Trust</p><h2 className="section-display max-w-5xl">{t("Privacy claims depend on the runtime being used.", "Las afirmaciones de privacidad dependen del runtime utilizado.")}</h2><p className="section-lead mt-6 max-w-4xl">{t("Virro separates the public lead form, an assisted audit and the Safe Mode technical foundation instead of presenting one retention claim for every surface.", "Virro separa el formulario público, una auditoría asistida y la base técnica Safe Mode en lugar de presentar una sola afirmación de retención para todas las superficies.")}</p><ol className="mt-9 flex flex-wrap gap-2">{flow.map((item, index) => <li key={item} className="flex items-center gap-2 rounded-full border border-[var(--border)] px-3 py-2 text-[9px] font-semibold"><span className="text-[var(--brand-blue)]">{index + 1}</span>{item}{index < flow.length - 1 && <ArrowRight aria-hidden="true" size={11} />}</li>)}</ol><div className="mt-8 grid gap-3 lg:grid-cols-3">{runtimes.map(runtime => <PrivacyRuntimeCard key={runtime.title} {...runtime} />)}</div><ul className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{principles.map(item => <li key={item} className="flex gap-2 rounded-xl bg-[var(--panel-soft)] p-4 text-[10px]"><ShieldCheck aria-hidden="true" size={13} className="shrink-0 text-teal-300" />{item}</li>)}</ul></div></section>;
}

export function NonJiraSection() { const { t } = useLanguage(); return <section id="empresa" className="px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-[1380px] rounded-[28px] border border-[var(--border)] bg-[var(--panel-soft)] p-7 md:p-12"><p className="section-kicker">Virro Enterprise</p><h2 className="section-display">{t("Start with the workflow you already have.", "Empieza con el flujo que ya tienes.")}</h2><p className="section-lead mt-6">{t("Virro can begin today with an assisted discovery or controlled import. Connectors and API access are introduced only when their validated status and pilot scope apply.", "Virro puede comenzar hoy con descubrimiento asistido o una importación controlada. Los conectores y el acceso por API se incorporan únicamente cuando aplican su estado validado y el alcance del piloto.")}</p><a href="#solicitar-auditoria" className="brand-secondary-button mt-8">{t("Analyze a workflow", "Analizar un flujo")} <ArrowRight aria-hidden="true" size={14} /></a></div></section>; }

export function ShadowScanOfferSection() { const { t } = useLanguage(); return <section id="oferta" className="px-5 py-24 md:px-8 md:py-36"><div className="mx-auto grid max-w-[1380px] gap-8 rounded-[30px] border border-[var(--border)] bg-[var(--panel)] p-6 md:p-10 lg:grid-cols-[.8fr_1.2fr]"><div className="p-2 md:p-5"><p className="section-kicker">Workflow Discovery Audit</p><h2 className="section-display text-[2.6rem]">{t("Begin with one real transfer point.", "Empieza con un punto de transferencia real.")}</h2><p className="section-lead mt-6">{t("Virro maps how information moves, what the receiver needs and which changes are causing context to stop representing reality.", "Virro mapea cómo se mueve la información, qué necesita el receptor y qué cambios están haciendo que el contexto deje de representar la realidad.")}</p></div><DiagnosisRequestForm /></div></section>; }

export function FinalEnterpriseCta() { const { t } = useLanguage(); return <section className="px-5 pb-24 md:px-8 md:pb-36"><div className="mx-auto max-w-[1380px] rounded-[30px] border border-[var(--border)] bg-[linear-gradient(135deg,color-mix(in_srgb,var(--panel)_88%,var(--brand-blue)_12%),var(--panel))] p-7 md:p-14"><h2 className="section-display max-w-5xl">{t("Where is operational understanding being lost today?", "¿Dónde se está perdiendo hoy el entendimiento operativo?")}</h2><p className="section-lead mt-6">{t("Analyze one workflow and make its origin, receiver, expected action and evidence visible.", "Analiza un flujo y haz visibles su origen, receptor, acción esperada y evidencia.")}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#solicitar-auditoria" className="brand-primary-button">{t("Analyze a workflow", "Analizar un flujo")}</a><Link href="/app/demo-scenarios" className="brand-secondary-button">{t("View demo", "Ver demo")}</Link></div></div></section>; }
