"use client";

import { BarChart3, Bot, BriefcaseBusiness, Code2, FileCheck2, Gavel, Palette, Workflow } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { StaggerGroup } from "@/components/landing/motion/motion-primitives";

const areas = [
  { icon: Code2, en: "Work & Delivery", es: "Trabajo y delivery", problemEn: "Ambiguous requirements reach execution.", problemEs: "Requerimientos ambiguos llegan a ejecución.", reviewEn: "Stories, criteria, QA, releases and handoffs.", reviewEs: "Historias, criterios, QA, releases y handoffs.", valueEn: "Less rework and fewer blind spots.", valueEs: "Menos retrabajo y menos puntos ciegos." },
  { icon: Palette, en: "Design & Experience", es: "Diseño y experiencia", problemEn: "Final screens arrive without behavior.", problemEs: "Pantallas finales llegan sin comportamiento.", reviewEn: "States, responsive rules and functional handoff.", reviewEs: "Estados, reglas responsive y handoff funcional.", valueEn: "Design that is easier to implement.", valueEs: "Diseño más listo para implementar." },
  { icon: BriefcaseBusiness, en: "Customer & Revenue", es: "Cliente e ingresos", problemEn: "Commercial intent changes before delivery.", problemEs: "La intención comercial cambia antes de delivery.", reviewEn: "Discovery, scope, support and implementation signals.", reviewEs: "Discovery, alcance, soporte e implementación.", valueEn: "Fewer broken expectations.", valueEs: "Menos expectativas rotas." },
  { icon: BarChart3, en: "Data & Decision", es: "Datos y decisión", problemEn: "Reports answer the wrong question.", problemEs: "Los reportes responden la pregunta equivocada.", reviewEn: "Business question, metric, audience and decision.", reviewEs: "Pregunta de negocio, métrica, audiencia y decisión.", valueEn: "Evidence that supports action.", valueEs: "Evidencia que habilita acción." },
  { icon: Workflow, en: "Process & Operations", es: "Procesos y operaciones", problemEn: "Processes depend on tribal knowledge.", problemEs: "Los procesos dependen de conocimiento tribal.", reviewEn: "Triggers, owners, rules and exceptions.", reviewEs: "Disparadores, responsables, reglas y excepciones.", valueEn: "Flows ready to transfer or automate.", valueEs: "Flujos listos para transferir o automatizar." },
  { icon: Bot, en: "AI Understanding", es: "Entendimiento para IA", problemEn: "AI receives vague or repeated context.", problemEs: "La IA recibe contexto vago o repetido.", reviewEn: "Intent, constraints, evidence and assumptions.", reviewEs: "Intención, restricciones, evidencia y supuestos.", valueEn: "Fewer retries and wasted tokens.", valueEs: "Menos reintentos y tokens desperdiciados." },
  { icon: FileCheck2, en: "Knowledge Continuity", es: "Continuidad de conocimiento", problemEn: "Context leaves when the team changes.", problemEs: "El contexto se va cuando cambia el equipo.", reviewEn: "Decisions, boundaries and readiness evidence.", reviewEs: "Decisiones, límites y evidencia de readiness.", valueEn: "Faster, safer continuity.", valueEs: "Continuidad más rápida y segura." },
  { icon: Gavel, en: "Governance & Trust", es: "Gobernanza y confianza", problemEn: "Policies exist but are hard to apply.", problemEs: "Las políticas existen, pero cuesta aplicarlas.", reviewEn: "Scope, claims, sensitive context and application rules.", reviewEs: "Alcance, claims, contexto sensible y reglas de aplicación.", valueEn: "Information that is safer to operate.", valueEs: "Información más segura para operar." },
];

export function EnterpriseValueMap() {
  const { locale, t } = useLanguage();
  return <section id="donde-entra" className="value-map-section scroll-mt-24 border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="section-kicker">{t("Where Virro enters", "Dónde entra Virro")}</p><h2 className="section-display">{t("Where information changes hands.", "Donde la información cambia de manos.")}</h2></div><p className="section-lead lg:justify-self-end">{t("Virro is not limited to one tool or department. It reviews the transfer points where context, criteria and clarity can degrade before the next receiver acts.", "Virro no se limita a una herramienta o área. Revisa los puntos de transferencia donde contexto, criterio y claridad pueden degradarse antes de que actúe el siguiente receptor.")}</p></div><StaggerGroup className="mt-14 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{areas.map(({ icon: Icon, ...area }, index) => <article key={area.en} className={`value-map-card ${index === 0 || index === 5 ? "value-map-card-featured" : ""}`}><div className="flex items-center justify-between"><span className="value-map-icon"><Icon size={18} /></span><span className="value-map-index">0{index + 1}</span></div><h3>{locale === "es" ? area.es : area.en}</h3><dl><div><dt>{t("Operational friction", "Fricción operativa")}</dt><dd>{locale === "es" ? area.problemEs : area.problemEn}</dd></div><div><dt>{t("Virro reviews", "Virro revisa")}</dt><dd>{locale === "es" ? area.reviewEs : area.reviewEn}</dd></div><div><dt>{t("Value", "Valor")}</dt><dd>{locale === "es" ? area.valueEs : area.valueEn}</dd></div></dl></article>)}</StaggerGroup></div></section>;
}
