"use client";

import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, Eye, LockKeyhole, ShieldCheck } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { DiagnosisRequestForm } from "@/components/landing/diagnosis-request-form";

export function CentralFailuresSection() {
  const { t } = useLanguage();
  const failures = [
    ["Readiness Failure", t("Work tries to start without enough evidence that the receiver can execute it.", "El trabajo intenta comenzar sin evidencia suficiente de que el receptor pueda ejecutarlo.")],
    ["Change Integrity Failure", t("Priority, scope or a decision changes, but stories, tests, documentation and dependent teams are not updated at the same time.", "La prioridad, alcance o decisión cambia, pero historias, pruebas, documentación y equipos dependientes no se actualizan al mismo tiempo.")],
  ];
  return <section id="fallos" className="border-y border-[var(--border)] bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">{t("Two central failures", "Dos fallos centrales")}</p><div className="mt-10 grid gap-4 lg:grid-cols-2">{failures.map(([title, copy], index) => <article key={title} className="rounded-[26px] border border-[var(--border)] bg-[var(--panel)] p-7 md:p-9"><span className="text-[10px] font-semibold text-[var(--brand-coral)]">0{index + 1}</span><h2 className="mt-5 text-3xl font-semibold tracking-[-.04em]">{title}</h2><p className="section-lead mt-5">{copy}</p></article>)}</div></div></section>;
}

export function InitialProductSection() {
  const { t } = useLanguage();
  return <section id="readiness-gate" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto grid max-w-[1380px] gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="section-kicker">{t("Initial product", "Producto inicial")}</p><h2 className="section-display">Virro Readiness & Change Integrity Gate</h2><p className="section-lead mt-6">{t("Connects to Jira in read-only mode. It analyzes whether tickets had enough context before moving to development and detects later changes that may have left criteria, tests or references outdated.", "Se conecta a Jira en modo de solo lectura. Analiza si los tickets tenían suficiente contexto antes de pasar a desarrollo y detecta cambios posteriores que pudieron dejar criterios, pruebas o referencias desactualizadas.")}</p><p className="mt-5 flex items-center gap-2 text-xs font-semibold text-teal-300"><Eye aria-hidden="true" size={15} />{t("Shadow Mode does not modify anything.", "No modifica nada durante Shadow Mode.")}</p><a href="#shadow-scan" className="brand-primary-button mt-8">{t("Start Shadow Scan", "Iniciar Shadow Scan")} <ArrowRight aria-hidden="true" size={14} /></a></div><div className="rounded-[28px] border border-sky-400/20 bg-[linear-gradient(145deg,rgba(13,45,78,.86),rgba(7,20,37,.94))] p-6 text-slate-100 shadow-[0_35px_100px_rgba(0,0,0,.24)] md:p-8"><div className="flex items-center justify-between border-b border-white/10 pb-5"><div><span className="text-[9px] font-semibold uppercase tracking-[.13em] text-sky-300">Shadow Scan / Jira</span><p className="mt-2 text-lg font-semibold">{t("Read-only project review", "Revisión de proyecto en solo lectura")}</p></div><span className="rounded-full border border-teal-300/20 bg-teal-300/10 px-3 py-1 text-[9px] font-semibold text-teal-200">{t("Available", "Disponible")}</span></div><dl className="mt-6 grid gap-3 sm:grid-cols-2"><Metric term="Readiness" value={t("Evidence check", "Suficiencia de evidencia")} /><Metric term="Change Integrity" value={t("Propagation check", "Revisión de propagación")} /><Metric term={t("Access", "Acceso")} value={t("One project · revocable", "Un proyecto · revocable")} /><Metric term={t("Action", "Acción")} value={t("Private report", "Reporte privado")} /></dl></div></div></section>;
}

export function ShadowScanSection() {
  const { t } = useLanguage();
  const steps = [t("Connect Jira", "Conecta Jira"), t("Select one project", "Selecciona un proyecto"), t("Virro observes", "Virro observa"), t("Evaluate signal sufficiency", "Evalúa suficiencia de señal"), t("Identify readiness and changes", "Identifica readiness y cambios"), t("Deliver a private report", "Entrega un reporte privado"), t("Activate Advisory in the same flow", "Activa Advisory dentro del mismo flujo")];
  const trust = [t("Read only", "Solo lectura"), t("One project", "Un proyecto"), t("Revocable", "Revocable"), t("No comments", "Sin comentarios"), t("No blocking", "Sin bloqueo"), t("No raw content stored by default", "Sin contenido crudo almacenado por defecto")];
  return <section id="shadow-scan" className="scroll-mt-24 border-y border-[var(--border)] bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">Shadow Scan</p><h2 className="section-display max-w-5xl">{t("Observe before adding a gate.", "Observa antes de agregar un gate.")}</h2><ol className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{steps.map((step, index) => <li key={step} className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-5"><span className="text-[10px] font-semibold text-[var(--brand-blue)]">{String(index + 1).padStart(2, "0")}</span><p className="mt-3 text-xs font-semibold leading-5">{step}</p></li>)}</ol><div className="mt-8 flex flex-wrap gap-2">{trust.map((item) => <span key={item} className="rounded-full border border-[var(--border)] bg-[var(--panel)] px-3 py-2 text-[9px] font-semibold"><ShieldCheck aria-hidden="true" className="mr-2 inline text-teal-300" size={12} />{item}</span>)}</div><div className="mt-12 rounded-[26px] border border-amber-300/20 bg-amber-300/[.05] p-7 md:p-9"><div className="flex gap-4"><CircleAlert aria-hidden="true" className="shrink-0 text-amber-300" /><div><p className="section-kicker text-amber-300">Signal Sufficiency</p><h3 className="mt-3 text-3xl font-semibold tracking-[-.04em]">{t("Virro also knows when it should not offer an opinion.", "Virro también sabe cuándo no debería opinar.")}</h3><p className="section-lead mt-5">{t("When a ticket is too unstructured, depends on an unavailable meeting or references sources without access, Virro does not force a score.", "Cuando un ticket es demasiado desestructurado, depende de una reunión no disponible o referencia fuentes sin acceso, Virro no fuerza un score.")}</p><p className="mt-6 inline-flex rounded-full border border-amber-300/25 px-3 py-2 text-[10px] font-semibold text-amber-200">{t("Insufficient signal", "Señal insuficiente")}</p><p className="mt-3 text-xs leading-5 text-[var(--muted)]">{t("The available information does not make it possible to determine reliably whether the work was ready.", "La información disponible no permite determinar de forma confiable si el trabajo estaba listo.")}</p></div></div></div></div></section>;
}

export function UnderstandingEventDemo() {
  const { t } = useLanguage();
  const findings = ["Criterios modificados después de iniciar", "QA no confirmado", "Documentación API referenciada", "Soporte no informado", "Posible cambio de regresión"];
  const questions = ["¿Qué comportamiento anterior deja de ser válido?", "¿Qué casos de prueba requieren actualización?", "¿Quién confirma la nueva versión como fuente vigente?"];
  return <section id="demo" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">Shadow Scan · {t("Simulated demo", "Demo simulada")}</p><h2 className="section-display max-w-5xl">{t("A scope change after development begins.", "Un cambio de alcance después de iniciar desarrollo.")}</h2><div className="mt-12 grid gap-4 lg:grid-cols-[.85fr_1.15fr]"><article className="rounded-[26px] border border-[var(--border)] bg-[var(--panel)] p-7"><span className="text-[9px] uppercase tracking-[.12em] text-[var(--subtle)]">{t("Input", "Entrada")}</span><blockquote className="mt-5 text-xl font-semibold leading-8">{t("An authentication story moves to development. Two days later, management changes the scope and requires the date to remain unchanged.", "Una historia de autenticación pasa a desarrollo. Dos días después, gerencia cambia el alcance y exige mantener la fecha.")}</blockquote><div className="mt-7 rounded-xl border border-amber-300/20 bg-amber-300/[.05] p-4"><span className="text-[9px] uppercase tracking-[.12em] text-amber-300">{t("Status", "Estado")}</span><p className="mt-2 text-sm font-semibold">{t("Change partially propagated", "Cambio parcialmente propagado")}</p></div></article><article className="rounded-[26px] border border-[var(--border)] bg-[var(--panel-soft)] p-7"><h3 className="text-xs font-semibold">{t("Virro detects", "Virro detecta")}</h3><ul className="mt-4 grid gap-2 sm:grid-cols-2">{findings.map((item) => <li key={item} className="flex gap-2 rounded-xl border border-[var(--border)] bg-[var(--panel)] p-3 text-[10px] leading-4"><CheckCircle2 aria-hidden="true" size={12} className="shrink-0 text-[var(--brand-blue)]" />{item}</li>)}</ul><h3 className="mt-7 text-xs font-semibold">{t("Critical questions", "Preguntas críticas")}</h3><ol className="mt-3 grid gap-2">{questions.map((question, index) => <li key={question} className="flex gap-3 rounded-xl border border-[var(--border)] p-4 text-[11px] leading-5"><span className="font-semibold text-[var(--brand-blue)]">0{index + 1}</span>{question}</li>)}</ol></article></div><p className="mt-4 text-[10px] text-[var(--subtle)]">{t("Simulated data · Probabilistic evaluation · Human review required", "Datos simulados · Evaluación probabilística · Revisión humana requerida")}</p></div></section>;
}

export function GradualitySection() {
  const { t } = useLanguage(); const stages = [["Shadow Mode", "Disponible"], ["Advisory Gate", "Disponible"], ["Confirmation Gate", "Planeado"], ["Policy Gate", "Visión futura"], ["Handoff Acceptance SLA", "Visión futura"]];
  return <section id="change-integrity" className="scroll-mt-24 border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">Change Integrity</p><h2 className="section-display max-w-5xl">{t("Add control gradually, after observing the real workflow.", "Agrega control gradualmente, después de observar el flujo real.")}</h2><div className="mt-12 grid gap-3 lg:grid-cols-5">{stages.map(([name, state], index) => <article key={name} className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-5"><span className="text-[9px] text-[var(--subtle)]">0{index + 1}</span><h3 className="mt-4 text-sm font-semibold">{name}</h3><p className={`mt-5 text-[9px] font-semibold uppercase tracking-[.1em] ${state === "Disponible" ? "text-teal-300" : "text-[var(--subtle)]"}`}>{state}</p></article>)}</div><p className="mt-6 text-[10px] text-[var(--subtle)]">{t("Confirmation is planned. Policy and SLA are future capabilities subject to calibration.", "Confirmation está planeado. Policy y SLA son capacidades futuras sujetas a calibración.")}</p></div></section>;
}

export function FutureApplicationsSection() {
  const { t } = useLanguage(); const applications = [["Product → Development", "Disponible"], ["Design → Development", "Planeado"], ["Development → QA", "Piloto"], ["QA → Release", "Planeado"], ["Sales → Delivery", "Visión futura"], ["Vendor → Internal Team", "Visión futura"], ["Documentation Freshness", "Planeado"], ["API Readiness", "Visión futura"], ["AI Context and Output Alignment", "Visión futura"]];
  return <section id="aplicaciones" className="scroll-mt-24 bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><p className="section-kicker">{t("Expansion map", "Mapa de expansión")}</p><h2 className="section-display max-w-5xl">Virro Enterprise Understanding Layer</h2><p className="section-lead mt-6">{t("These are expansion paths, not a claim that every integration is already productive.", "Estas son rutas de expansión, no una afirmación de que todas las integraciones ya estén productivas.")}</p><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{applications.map(([name, state]) => <article key={name} className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-5"><h3 className="text-sm font-semibold">{name}</h3>{name === "Design → Development" && <p className="mt-3 text-[10px] leading-5 text-[var(--muted)]">{t("Checks whether design contains states, rules, errors, responsive behavior and enough criteria for development and QA. No Figma integration is claimed.", "Evalúa si el diseño contiene estados, reglas, errores, responsive y criterios suficientes para desarrollo y QA. No se afirma integración con Figma.")}</p>}<span className="mt-5 inline-block text-[9px] font-semibold uppercase tracking-[.1em] text-[var(--subtle)]">{state}</span></article>)}</div></div></section>;
}

export function EnterprisePrivacySection() {
  const { t } = useLanguage(); const flow = ["Receive", "Mask", "Analyze", "Discard raw content", "Store safe signals", "Report"]; const principles = ["Acceso mínimo", "Procesamiento limitado", "No entrenamiento cruzado entre clientes", "Eliminación", "Aislamiento", "Revisión humana", "Sin vigilancia"];
  return <section id="privacidad" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px] rounded-[30px] border border-[var(--border)] bg-[var(--panel)] p-7 md:p-12"><LockKeyhole aria-hidden="true" className="text-[var(--brand-blue)]" /><p className="section-kicker mt-5">Privacy & Trust</p><h2 className="section-display max-w-5xl">{t("Minimum access, limited processing and safe signals.", "Acceso mínimo, procesamiento limitado y señales seguras.")}</h2><ol className="mt-9 flex flex-wrap gap-2">{flow.map((item, index) => <li key={item} className="flex items-center gap-2 rounded-full border border-[var(--border)] px-3 py-2 text-[9px] font-semibold"><span className="text-[var(--brand-blue)]">{index + 1}</span>{item}{index < flow.length - 1 && <ArrowRight aria-hidden="true" size={11} />}</li>)}</ol><ul className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{principles.map((item) => <li key={item} className="flex gap-2 rounded-xl bg-[var(--panel-soft)] p-4 text-[10px]"><ShieldCheck aria-hidden="true" size={13} className="shrink-0 text-teal-300" />{item}</li>)}</ul></div></section>;
}

export function NonJiraSection() { const { t } = useLanguage(); return <section id="empresa" className="px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-[1380px] rounded-[28px] border border-[var(--border)] bg-[var(--panel-soft)] p-7 md:p-12"><p className="section-kicker">Workflow Discovery</p><h2 className="section-display">{t("Not using Jira?", "¿No usas Jira?")}</h2><p className="section-lead mt-6">{t("Virro can begin through Workflow Discovery and Secure Batch Import to identify transfer points, insufficient signal and the first measurable gate without forcing you to change tools.", "Virro puede comenzar mediante Workflow Discovery y Secure Batch Import para identificar puntos de transferencia, señal insuficiente y el primer gate medible sin obligarte a cambiar de herramienta.")}</p><a href="#solicitar-auditoria" className="brand-secondary-button mt-8">{t("Evaluate another workflow", "Evaluar otro flujo")} <ArrowRight aria-hidden="true" size={14} /></a></div></section>; }

export function ShadowScanOfferSection() { const { t } = useLanguage(); return <section id="oferta" className="px-5 py-24 md:px-8 md:py-36"><div className="mx-auto grid max-w-[1380px] gap-8 rounded-[30px] border border-[var(--border)] bg-[var(--panel)] p-6 md:p-10 lg:grid-cols-[.8fr_1.2fr]"><div className="p-2 md:p-5"><p className="section-kicker">Shadow Scan</p><h2 className="section-display text-[2.6rem]">{t("Start with one project and no workflow disruption.", "Empieza con un proyecto y sin interrumpir el flujo.")}</h2><p className="section-lead mt-6">{t("Virro observes readiness and change integrity in read-only mode, then delivers a private report before any gate is activated.", "Virro observa readiness y Change Integrity en modo de solo lectura y entrega un reporte privado antes de activar cualquier gate.")}</p></div><DiagnosisRequestForm /></div></section>; }

export function FinalEnterpriseCta() { const { t } = useLanguage(); return <section className="px-5 pb-24 md:px-8 md:pb-36"><div className="mx-auto max-w-[1380px] rounded-[30px] border border-[var(--border)] bg-[linear-gradient(135deg,color-mix(in_srgb,var(--panel)_88%,var(--brand-blue)_12%),var(--panel))] p-7 md:p-14"><h2 className="section-display max-w-5xl">{t("What moves forward without enough context today?", "¿Qué está avanzando hoy sin contexto suficiente?")}</h2><p className="section-lead mt-6">{t("Analyze one workflow in Shadow Mode before deciding whether a gate is needed.", "Analiza un flujo en Shadow Mode antes de decidir si necesita un gate.")}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#solicitar-auditoria" className="brand-primary-button">{t("Analyze a workflow", "Analizar un flujo")}</a><Link href="/jira-readiness" className="brand-secondary-button">{t("View Shadow Scan", "Ver Shadow Scan")}</Link></div></div></section>; }

function Metric({ term, value }: { term: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><dt className="text-[8px] uppercase tracking-[.12em] text-sky-300">{term}</dt><dd className="mt-2 text-xs font-semibold">{value}</dd></div>; }
