"use client";

import { BarChart3, Bot, BriefcaseBusiness, Code2, FileCheck2, Gavel, Headphones, Landmark, Megaphone, Palette, Workflow } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { StaggerGroup } from "@/components/landing/motion/motion-primitives";

const areas = [
  { icon: Code2, en: "Work & Delivery", es: "Trabajo y delivery", problemEn: "Ambiguous requirements reach execution.", problemEs: "Requerimientos ambiguos llegan a ejecución.", reviewEn: "Stories, criteria, QA, releases and handoffs.", reviewEs: "Historias, criterios, QA, releases y handoffs.", valueEn: "Less rework and fewer blind spots.", valueEs: "Menos retrabajo y menos puntos ciegos." },
  { icon: Palette, en: "Design & Experience", es: "Diseño y experiencia", problemEn: "Final screens arrive without behavior.", problemEs: "Pantallas finales llegan sin comportamiento.", reviewEn: "States, responsive rules and functional handoff.", reviewEs: "Estados, reglas responsive y handoff funcional.", valueEn: "Design that is easier to implement.", valueEs: "Diseño más listo para implementar." },
  { icon: Megaphone, en: "Marketing & Growth", es: "Marketing y crecimiento", problemEn: "Campaign intent fragments across channels.", problemEs: "La intención de campaña se fragmenta entre canales.", reviewEn: "Audience, proposition, evidence and handoffs.", reviewEs: "Audiencia, propuesta, evidencia y handoffs.", valueEn: "More consistent activation.", valueEs: "Activación más consistente." },
  { icon: BriefcaseBusiness, en: "Sales & Revenue", es: "Ventas e ingresos", problemEn: "Commercial scope changes before delivery.", problemEs: "El alcance comercial cambia antes de delivery.", reviewEn: "Discovery, commitments, scope and acceptance.", reviewEs: "Discovery, compromisos, alcance y aceptación.", valueEn: "Fewer broken expectations.", valueEs: "Menos expectativas rotas." },
  { icon: Headphones, en: "Support & Customer Success", es: "Soporte y éxito del cliente", problemEn: "Customer signals lose urgency and context.", problemEs: "Las señales del cliente pierden urgencia y contexto.", reviewEn: "Evidence, impact, pattern and destination team.", reviewEs: "Evidencia, impacto, patrón y equipo receptor.", valueEn: "Signals that reach the right decision.", valueEs: "Señales que llegan a la decisión correcta." },
  { icon: BarChart3, en: "Data & Decision", es: "Datos y decisión", problemEn: "Reports answer the wrong question.", problemEs: "Los reportes responden la pregunta equivocada.", reviewEn: "Business question, metric, audience and decision.", reviewEs: "Pregunta de negocio, métrica, audiencia y decisión.", valueEn: "Evidence that supports action.", valueEs: "Evidencia que habilita acción." },
  { icon: Workflow, en: "Operations & Automation", es: "Operaciones y automatización", problemEn: "Processes depend on tribal knowledge.", problemEs: "Los procesos dependen de conocimiento tribal.", reviewEn: "Triggers, owners, rules and exceptions.", reviewEs: "Disparadores, responsables, reglas y excepciones.", valueEn: "Flows ready to transfer or automate.", valueEs: "Flujos listos para transferir o automatizar." },
  { icon: Landmark, en: "Finance & Procurement", es: "Finanzas y compras", problemEn: "Requests stall between evidence and approval.", problemEs: "Las solicitudes se detienen entre evidencia y aprobación.", reviewEn: "Purpose, threshold, evidence and approver.", reviewEs: "Propósito, umbral, evidencia y aprobador.", valueEn: "Cleaner approval paths.", valueEs: "Rutas de aprobación más claras." },
  { icon: Gavel, en: "Legal, Compliance & Security", es: "Legal, compliance y seguridad", problemEn: "Policies exist but are hard to apply.", problemEs: "Las políticas existen, pero cuesta aplicarlas.", reviewEn: "Scope, claims, controls and application rules.", reviewEs: "Alcance, claims, controles y reglas de aplicación.", valueEn: "Safer operational interpretation.", valueEs: "Interpretación operativa más segura." },
  { icon: FileCheck2, en: "Talent & Knowledge Continuity", es: "Talento y continuidad", problemEn: "Context leaves when people or vendors change.", problemEs: "El contexto se va cuando cambian personas o proveedores.", reviewEn: "Role intent, decisions, boundaries and evidence.", reviewEs: "Intención del rol, decisiones, límites y evidencia.", valueEn: "Faster, safer continuity.", valueEs: "Continuidad más rápida y segura." },
  { icon: Bot, en: "AI & Agents", es: "IA y agentes", problemEn: "AI receives vague or repeated context.", problemEs: "La IA recibe contexto vago o repetido.", reviewEn: "Intent, constraints, evidence and assumptions.", reviewEs: "Intención, restricciones, evidencia y supuestos.", valueEn: "Fewer retries and wasted tokens.", valueEs: "Menos reintentos y tokens desperdiciados." },
];

export function EnterpriseValueMap() {
  const { locale, t } = useLanguage();
  return <section id="donde-entra" className="value-map-section scroll-mt-24 border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="section-kicker">{t("Where Virro enters", "Dónde entra Virro")}</p><h2 className="section-display">{t("Where information changes hands.", "Donde la información cambia de manos.")}</h2></div><p className="section-lead lg:justify-self-end">{t("Virro reviews the transfer points where context, criteria and clarity can degrade across areas, formats, tools and responsibilities.", "Virro revisa los puntos de transferencia donde contexto, criterio y claridad pueden degradarse entre áreas, formatos, herramientas y responsabilidades.")}</p></div><StaggerGroup className="value-family-grid mt-14">{areas.map(({ icon: Icon, ...area }, index) => <article key={area.en} className={`value-map-card ${index === 0 || index === 10 ? "value-map-card-featured" : ""}`}><div className="flex items-center justify-between"><span className="value-map-icon"><Icon size={18} /></span><span className="value-map-index">{String(index + 1).padStart(2, "0")}</span></div><h3>{locale === "es" ? area.es : area.en}</h3><dl><div><dt>{t("Loss relieved", "Pérdida que alivia")}</dt><dd>{locale === "es" ? area.problemEs : area.problemEn}</dd></div><div><dt>{t("Virro reviews", "Virro revisa")}</dt><dd>{locale === "es" ? area.reviewEs : area.reviewEn}</dd></div><div><dt>{t("Client value", "Valor para cliente")}</dt><dd>{locale === "es" ? area.valueEs : area.valueEn}</dd></div></dl></article>)}</StaggerGroup></div></section>;
}
