"use client";

import { type KeyboardEvent, useEffect, useState } from "react";
import { ArrowRight, Check, CircleAlert, FileCheck2, Layers3, LockKeyhole, Radar, ShieldCheck, Sparkles } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";

type Copy = { en: string; es: string };
type Scenario = {
  id: string; flow: Copy; input: Copy; riskLabel: Copy; reason: Copy; risks: Copy[]; pack: string; packCopy: Copy;
  output: Copy; checklist: Copy[]; decision: Copy; decisionCopy: Copy; cta: Copy; score: number; mask: [string, string][];
};

const scenarios: Scenario[] = [
  { id: "meeting", flow: { en: "Meeting → tasks", es: "Junta → tareas" }, input: { en: "Review the client issue, adjust the proposal and see if dev can ship this week.", es: "Revisar lo del cliente, ajustar la propuesta y ver si dev puede sacarlo esta semana." }, riskLabel: { en: "Unstructured agreement", es: "Acuerdo sin estructura" }, reason: { en: "There is no accountable owner, deadline or completion criterion.", es: "No hay responsable, fecha ni criterio de terminado." }, risks: [{ en: "Owner missing", es: "Responsable no definido" }, { en: "Scope is undefined", es: "Alcance no definido" }, { en: "No completion criteria", es: "Sin criterio de terminado" }], pack: "Meeting-to-Readiness Pack", packCopy: { en: "Separates decisions, owners and unresolved points before task creation.", es: "Separa decisiones, responsables y puntos pendientes antes de crear tareas." }, output: { en: "Action brief", es: "Brief de acciones" }, checklist: [{ en: "Owner", es: "Responsable" }, { en: "Deadline", es: "Fecha" }, { en: "Completion criterion", es: "Criterio de terminado" }], decision: { en: "Define owner, date and completion criterion before creating tasks.", es: "Definir responsable, fecha y criterio de terminado antes de convertir la conversación en tareas." }, decisionCopy: { en: "This prevents a meeting from becoming activity without accountable execution.", es: "Esto evita que una junta se convierta en actividad sin ejecución responsable." }, cta: { en: "Audit meeting handoffs", es: "Auditar handoffs de juntas" }, score: 28, mask: [["María López", "[PERSON_1]"], ["Grupo Norte", "[CLIENT_1]"]] },
  { id: "product", flow: { en: "Product → development", es: "Producto → desarrollo" }, input: { en: "Add social login to improve conversion.", es: "Agregar login social para mejorar conversión." }, riskLabel: { en: "Story not ready", es: "Historia no lista" }, reason: { en: "The receiver lacks provider, boundaries, QA evidence and edge cases.", es: "El receptor no tiene proveedor, límites, evidencia QA ni edge cases." }, risks: [{ en: "Provider undefined", es: "Proveedor no definido" }, { en: "Fallback absent", es: "Fallback ausente" }, { en: "Success metric missing", es: "Métrica de éxito ausente" }], pack: "Product Delivery Readiness", packCopy: { en: "Prepares acceptance, dependencies and test evidence for development.", es: "Prepara aceptación, dependencias y evidencia de prueba para desarrollo." }, output: { en: "Delivery-ready story", es: "Historia lista para delivery" }, checklist: [{ en: "Acceptance", es: "Aceptación" }, { en: "Dependencies", es: "Dependencias" }, { en: "Edge cases", es: "Edge cases" }], decision: { en: "Do not start development until acceptance, dependencies, edge cases and QA evidence are validated.", es: "No iniciar desarrollo hasta validar aceptación, dependencias, edge cases y evidencia QA." }, decisionCopy: { en: "The risk is not the story length; it is implementation based on unvalidated assumptions.", es: "El riesgo no es el largo de la historia; es implementar con supuestos no validados." }, cta: { en: "Audit product delivery", es: "Auditar delivery de producto" }, score: 42, mask: [["Sofía", "[PERSON_1]"], ["producto@empresa.com", "[EMAIL_1]"]] },
  { id: "design", flow: { en: "Design → frontend", es: "Diseño → frontend" }, input: { en: "Final Figma screen with no interaction states.", es: "Pantalla final en Figma sin estados de interacción." }, riskLabel: { en: "Handoff not ready", es: "Handoff no listo" }, reason: { en: "Visual intent exists, but behavior, responsive rules and validation are absent.", es: "La intención visual existe, pero faltan comportamiento, reglas responsive y validaciones." }, risks: [{ en: "Critical states missing", es: "Estados críticos ausentes" }, { en: "Responsive undefined", es: "Responsive no definido" }, { en: "Validation unclear", es: "Validación poco clara" }], pack: "Design & Experience Readiness", packCopy: { en: "Makes interaction behavior explicit before frontend implementation.", es: "Hace explícito el comportamiento de interacción antes de implementar frontend." }, output: { en: "Functional design handoff", es: "Handoff funcional de diseño" }, checklist: [{ en: "States", es: "Estados" }, { en: "Responsive", es: "Responsive" }, { en: "Validation", es: "Validaciones" }], decision: { en: "Do not hand off to frontend until states, behavior, responsive rules and validation are defined.", es: "No entregar a frontend hasta definir estados, comportamiento, responsive y validaciones." }, decisionCopy: { en: "The delivery moves from a visual reference to an executable interaction contract.", es: "La entrega pasa de referencia visual a contrato de interacción ejecutable." }, cta: { en: "Audit design handoffs", es: "Auditar handoffs de diseño" }, score: 35, mask: [["Figma Pro", "[CLIENT_1]"], ["ana@studio.io", "[EMAIL_1]"]] },
  { id: "support", flow: { en: "Support → product", es: "Soporte → producto" }, input: { en: "Several customers say exports fail sometimes.", es: "Varios clientes dicen que a veces falla la exportación." }, riskLabel: { en: "Incomplete support signal", es: "Señal de soporte incompleta" }, reason: { en: "The signal exists but cannot yet establish impact, pattern, reproducibility or priority.", es: "La señal existe, pero todavía no permite establecer impacto, patrón, reproducibilidad ni prioridad." }, risks: [{ en: "No reproducible evidence", es: "Sin evidencia reproducible" }, { en: "Impact unknown", es: "Impacto desconocido" }, { en: "Failure pattern ungrouped", es: "Patrón de falla sin agrupar" }, { en: "Priority undefined", es: "Prioridad no definida" }], pack: "Support Signal Readiness", packCopy: { en: "Structures weak support signals so product, QA or engineering can decide whether the flow advances.", es: "Estructura señales débiles de soporte para que producto, QA o ingeniería decidan si el flujo avanza." }, output: { en: "Product and QA-ready signal", es: "Señal lista para producto y QA" }, checklist: [{ en: "Evidence", es: "Evidencia requerida" }, { en: "Affected customers", es: "Clientes afectados" }, { en: "Reproduction", es: "Pasos para reproducir" }, { en: "Priority", es: "Prioridad sugerida" }], decision: { en: "Group evidence before escalating.", es: "Agrupar evidencia antes de escalar." }, decisionCopy: { en: "If a pattern repeats in key customers or affects a critical flow, enter a correction pilot; otherwise keep it as an observed signal.", es: "Si el patrón se repite en clientes clave o afecta un flujo crítico, debe entrar a un piloto de corrección. Si no, se mantiene como señal observada." }, cta: { en: "Audit support signals", es: "Auditar señales de soporte" }, score: 33, mask: [["Acme Health", "[CLIENT_1]"], ["Laura Díaz", "[PERSON_1]"]] },
  { id: "sales", flow: { en: "Sales → delivery", es: "Ventas → delivery" }, input: { en: "The client expects the integration in phase one.", es: "El cliente espera la integración en la primera fase." }, riskLabel: { en: "Commercial commitment unclear", es: "Compromiso comercial poco claro" }, reason: { en: "The delivery team cannot see scope, acceptance or commercial evidence.", es: "El equipo de delivery no puede ver alcance, aceptación ni evidencia comercial." }, risks: [{ en: "Commitment undocumented", es: "Compromiso no documentado" }, { en: "Acceptance undefined", es: "Aceptación no definida" }, { en: "Scope owner unclear", es: "Responsable de alcance poco claro" }], pack: "Sales-to-Delivery Understanding", packCopy: { en: "Aligns what was sold with what delivery can verify and execute.", es: "Alinea lo vendido con lo que delivery puede verificar y ejecutar." }, output: { en: "Commercial commitment map", es: "Mapa de compromisos comerciales" }, checklist: [{ en: "Sold scope", es: "Alcance vendido" }, { en: "Constraints", es: "Restricciones" }, { en: "Success criteria", es: "Criterio de éxito" }], decision: { en: "Do not start implementation until sold scope, constraints and success criteria are aligned.", es: "No iniciar implementación hasta alinear alcance vendido, restricciones y criterio de éxito." }, decisionCopy: { en: "The goal is to stop delivery from discovering commercial ambiguity after kickoff.", es: "El objetivo es evitar que delivery descubra ambigüedad comercial después del kickoff." }, cta: { en: "Audit sales handoffs", es: "Auditar handoffs de ventas" }, score: 39, mask: [["Banco Azul", "[CLIENT_1]"], ["Luis Herrera", "[PERSON_1]"]] },
  { id: "marketing", flow: { en: "Marketing → sales/design", es: "Marketing → ventas/diseño" }, input: { en: "Launch the campaign around simplicity next month.", es: "Lanzar la campaña sobre simplicidad el próximo mes." }, riskLabel: { en: "Campaign premise unclear", es: "Premisa de campaña poco clara" }, reason: { en: "Audience, proof, offer and channel restrictions are not ready for execution.", es: "Audiencia, evidencia, oferta y restricciones por canal no están listas para ejecución." }, risks: [{ en: "Audience not prioritized", es: "Audiencia sin priorizar" }, { en: "Proof missing", es: "Falta evidencia" }, { en: "Channel constraints absent", es: "Sin restricciones por canal" }], pack: "Marketing Understanding", packCopy: { en: "Aligns audience, promise, proof and channel boundaries before launch.", es: "Alinea audiencia, promesa, evidencia y límites de canal antes del lanzamiento." }, output: { en: "Campaign execution brief", es: "Brief de ejecución de campaña" }, checklist: [{ en: "Audience", es: "Audiencia" }, { en: "Promise", es: "Promesa" }, { en: "Proof", es: "Evidencia" }], decision: { en: "Do not launch until audience, promise, offer and brand constraints are aligned.", es: "No lanzar campaña hasta alinear audiencia, promesa, oferta y restricciones de marca." }, decisionCopy: { en: "This avoids creative output that is polished but misaligned to the business ask.", es: "Esto evita una salida creativa pulida pero desalineada con la necesidad de negocio." }, cta: { en: "Audit campaign inputs", es: "Auditar inputs de campaña" }, score: 46, mask: [["Mercado Uno", "[CLIENT_1]"], ["marketing@empresa.com", "[EMAIL_1]"]] },
  { id: "data", flow: { en: "Data request → BI", es: "Solicitud de datos → BI" }, input: { en: "I need a performance report.", es: "Necesito un reporte de desempeño." }, riskLabel: { en: "Ambiguous request", es: "Solicitud ambigua" }, reason: { en: "The request does not define the business decision, key metric, period or report audience.", es: "La solicitud no define qué decisión se quiere tomar, qué métrica importa, qué periodo analizar ni quién usará el reporte." }, risks: [{ en: "Business question undefined", es: "Pregunta de negocio no definida" }, { en: "Primary metric absent", es: "Métrica principal ausente" }, { en: "Expected decision unclear", es: "Decisión esperada poco clara" }, { en: "Audience unspecified", es: "Audiencia del reporte no especificada" }], pack: "Data Request Readiness", packCopy: { en: "Virro identifies that the problem is not building a report; it is clarifying the business question before requesting data.", es: "Virro identifica que el problema no es construir un reporte, sino aclarar la pregunta de negocio antes de pedir datos." }, output: { en: "BI request brief", es: "Brief de solicitud para BI" }, checklist: [{ en: "Business question", es: "Pregunta de negocio" }, { en: "Primary metric", es: "Métrica principal" }, { en: "Period", es: "Periodo" }, { en: "Audience", es: "Audiencia" }, { en: "Decision", es: "Decisión a soportar" }], decision: { en: "Do not build the dashboard yet.", es: "No construir dashboard todavía." }, decisionCopy: { en: "First validate the decision, metric and audience. This reduces the risk of building a correct report for a misunderstood need.", es: "Primero validar la decisión, métrica y audiencia. Esto reduce el riesgo de crear un reporte correcto para una necesidad mal entendida." }, cta: { en: "Audit data requests", es: "Auditar solicitudes de datos" }, score: 31, mask: [["Juan Pérez", "[PERSON_1]"], ["Banco Azul", "[CLIENT_1]"], ["correo@empresa.com", "[EMAIL_1]"]] },
  { id: "process", flow: { en: "Process → automation", es: "Proceso → automatización" }, input: { en: "Automate approvals when the request looks complete.", es: "Automatizar aprobaciones cuando la solicitud parezca completa." }, riskLabel: { en: "Not automatable yet", es: "Proceso no automatizable todavía" }, reason: { en: "The trigger is subjective and rules, exceptions and ownership are missing.", es: "El disparador es subjetivo y faltan reglas, excepciones y responsables." }, risks: [{ en: "Subjective trigger", es: "Disparador subjetivo" }, { en: "Exceptions missing", es: "Faltan excepciones" }, { en: "Escalation owner absent", es: "Sin responsable de escalamiento" }], pack: "Process Understanding", packCopy: { en: "Makes rules, exceptions, inputs and accountability explicit before automation.", es: "Hace explícitas reglas, excepciones, entradas y responsabilidad antes de automatizar." }, output: { en: "Automation readiness map", es: "Mapa de readiness para automatización" }, checklist: [{ en: "Trigger", es: "Disparador" }, { en: "Exceptions", es: "Excepciones" }, { en: "Owner", es: "Responsable" }], decision: { en: "Do not automate yet. First document rules, exceptions, inputs, outputs and owners.", es: "No automatizar todavía. Primero documentar reglas, excepciones, entradas, salidas y responsables." }, decisionCopy: { en: "Automation is safer when the operational rule is deterministic, not merely familiar to the current team.", es: "La automatización es más segura cuando la regla operativa es determinista, no solo familiar para el equipo actual." }, cta: { en: "Audit automation readiness", es: "Auditar readiness de automatización" }, score: 44, mask: [["Operaciones Norte", "[CLIENT_1]"], ["Pablo", "[PERSON_1]"]] },
  { id: "finance", flow: { en: "Finance request → approval", es: "Solicitud financiera → aprobación" }, input: { en: "Approve the vendor because the team needs it urgently.", es: "Aprobar al proveedor porque el equipo lo necesita urgente." }, riskLabel: { en: "Approval without evidence", es: "Aprobación sin evidencia" }, reason: { en: "The approver lacks justification, budget ownership, supplier context and return criteria.", es: "Al aprobador le faltan justificación, ownership de presupuesto, contexto de proveedor y criterio de retorno." }, risks: [{ en: "Evidence threshold missing", es: "Falta umbral de evidencia" }, { en: "Budget owner unclear", es: "Responsable de presupuesto poco claro" }, { en: "No exception rule", es: "Sin regla de excepción" }], pack: "Finance / Procurement Readiness", packCopy: { en: "Structures the request around purpose, evidence, budget and approval conditions.", es: "Estructura la solicitud alrededor de propósito, evidencia, presupuesto y condiciones de aprobación." }, output: { en: "Approval decision brief", es: "Brief de decisión de aprobación" }, checklist: [{ en: "Justification", es: "Justificación" }, { en: "Budget", es: "Presupuesto" }, { en: "Supplier", es: "Proveedor" }, { en: "Return criterion", es: "Criterio de retorno" }], decision: { en: "Do not approve yet. First validate justification, impact, budget, supplier and return criterion.", es: "No aprobar todavía. Primero validar justificación, impacto, presupuesto, proveedor y criterio de retorno." }, decisionCopy: { en: "Urgency alone is not an approval rule; the pack creates a traceable decision surface.", es: "La urgencia por sí sola no es una regla de aprobación; el pack crea una superficie de decisión trazable." }, cta: { en: "Audit approval requests", es: "Auditar solicitudes de aprobación" }, score: 36, mask: [["Proveedor Atlas", "[COMPANY_1]"], ["finanzas@empresa.com", "[EMAIL_1]"]] },
  { id: "policy", flow: { en: "Policy → operations", es: "Política → operación" }, input: { en: "Sensitive requests require enhanced review.", es: "Las solicitudes sensibles requieren revisión reforzada." }, riskLabel: { en: "Policy not executable", es: "Política no ejecutable" }, reason: { en: "Teams cannot identify applicability, control owner or evidence path.", es: "Los equipos no pueden identificar aplicabilidad, responsable de control ni ruta de evidencia." }, risks: [{ en: "Sensitive undefined", es: "Sensible no definido" }, { en: "Control owner missing", es: "Falta responsable del control" }, { en: "Evidence path absent", es: "Sin ruta de evidencia" }], pack: "Legal / Security / Compliance Understanding", packCopy: { en: "Translates policy language into rules, ownership and application scenarios.", es: "Traduce lenguaje de política a reglas, responsables y escenarios de aplicación." }, output: { en: "Operational policy card", es: "Tarjeta operativa de política" }, checklist: [{ en: "Applicability", es: "Aplicabilidad" }, { en: "Rule", es: "Regla" }, { en: "Evidence", es: "Evidencia" }], decision: { en: "Do not communicate the policy yet. First translate it into operational rules, owners and application scenarios.", es: "No comunicar política todavía. Primero traducirla a reglas operativas, responsables y escenarios de aplicación." }, decisionCopy: { en: "A policy earns trust when the receiver can apply it consistently in a real situation.", es: "Una política gana confianza cuando el receptor puede aplicarla consistentemente en una situación real." }, cta: { en: "Audit operational policies", es: "Auditar políticas operativas" }, score: 40, mask: [["Ana Ruiz", "[PERSON_1]"], ["Empresa Sol", "[COMPANY_1]"]] },
  { id: "ai", flow: { en: "Company → AI", es: "Empresa → IA" }, input: { en: "Create an executive summary of this process.", es: "Haz un resumen ejecutivo de este proceso." }, riskLabel: { en: "AI context incomplete", es: "Contexto para IA incompleto" }, reason: { en: "The instruction lacks audience, evidence boundaries, restrictions and expected format.", es: "La instrucción carece de audiencia, límites de evidencia, restricciones y formato esperado." }, risks: [{ en: "Audience missing", es: "Falta audiencia" }, { en: "Format undefined", es: "Formato no definido" }, { en: "Assumption boundaries absent", es: "Sin límites de supuestos" }], pack: "AI Understanding", packCopy: { en: "Prepares objective, context, constraints and review conditions before information reaches AI.", es: "Prepara objetivo, contexto, restricciones y condiciones de revisión antes de que la información llegue a IA." }, output: { en: "AI Context Pack", es: "AI Context Pack" }, checklist: [{ en: "Objective", es: "Objetivo" }, { en: "Context", es: "Contexto" }, { en: "Restrictions", es: "Restricciones" }, { en: "Expected format", es: "Formato esperado" }], decision: { en: "Do not send to AI yet. First prepare context, objective, restrictions, expected format and assumptions it must not make.", es: "No enviar a IA todavía. Primero preparar contexto, objetivo, restricciones, formato esperado y supuestos que no debe asumir." }, decisionCopy: { en: "This reduces generic output and makes human review more purposeful.", es: "Esto reduce resultados genéricos y hace más útil la revisión humana." }, cta: { en: "Audit AI context", es: "Auditar contexto para IA" }, score: 37, mask: [["Carlos Soto", "[PERSON_1]"], ["ai@empresa.com", "[EMAIL_1]"]] },
  { id: "continuity", flow: { en: "Old team → new team", es: "Equipo anterior → equipo nuevo" }, input: { en: "The deployment process is in the messages from the previous lead.", es: "El proceso de despliegue está en los mensajes del líder anterior." }, riskLabel: { en: "Knowledge continuity gap", es: "Brecha de continuidad" }, reason: { en: "Decisions, dependencies, recovery steps and ownership are fragmented across people and messages.", es: "Decisiones, dependencias, recuperación y ownership están fragmentados entre personas y mensajes." }, risks: [{ en: "Decision history fragmented", es: "Historial de decisiones fragmentado" }, { en: "Ownership outdated", es: "Ownership desactualizado" }, { en: "Recovery steps missing", es: "Faltan pasos de recuperación" }], pack: "Knowledge Continuity", packCopy: { en: "Captures the operating context another team needs to sustain the system safely.", es: "Captura el contexto operativo que otro equipo necesita para sostener el sistema de forma segura." }, output: { en: "Living transfer map", es: "Mapa vivo de transferencia" }, checklist: [{ en: "Prior decisions", es: "Decisiones previas" }, { en: "Dependencies", es: "Dependencias" }, { en: "Open risks", es: "Riesgos abiertos" }, { en: "Owners", es: "Responsables" }], decision: { en: "Do not close the handoff yet. First capture prior decisions, dependencies, open risks and owners.", es: "No cerrar handoff todavía. Primero capturar decisiones previas, dependencias, riesgos abiertos y owners." }, decisionCopy: { en: "Knowledge continuity limits the exposure created when operational context leaves with a person or provider.", es: "La continuidad de conocimiento limita la exposición que aparece cuando el contexto operativo sale con una persona o proveedor." }, cta: { en: "Audit knowledge continuity", es: "Auditar continuidad de conocimiento" }, score: 29, mask: [["Diego Ramos", "[PERSON_1]"], ["infra@empresa.com", "[EMAIL_1]"]] },
];

function pick(copy: Copy, locale: string) { return locale === "es" ? copy.es : copy.en; }

function AnimatedScore({ target }: { target: number }) {
  const [value, setValue] = useState(target);
  useEffect(() => {
    let frame = 0; const start = performance.now(); const duration = 820; const initial = Math.max(1, Math.round(target * .25));
    const tick = (now: number) => { const progress = Math.min((now - start) / duration, 1); setValue(Math.round(initial + (target - initial) * (1 - Math.pow(1 - progress, 3)))); if (progress < 1) frame = requestAnimationFrame(tick); };
    frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame);
  }, [target]);
  return <strong aria-label={`Readiness ${target} de 100`}>{value}<small>/100</small></strong>;
}

export function EnterpriseDemoExperienceV2() {
  const { locale, t } = useLanguage(); const [activeId, setActiveId] = useState("data");
  const active = scenarios.find((item) => item.id === activeId) ?? scenarios[0];
  function moveTab(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    if (!['ArrowRight', 'ArrowLeft', 'Home', 'End'].includes(event.key)) return; event.preventDefault();
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? scenarios.length - 1 : (index + (event.key === 'ArrowRight' ? 1 : -1) + scenarios.length) % scenarios.length;
    setActiveId(scenarios[next].id); requestAnimationFrame(() => document.getElementById(`enterprise-demo-tab-${scenarios[next].id}`)?.focus());
  }
  return <section id="demo" className="enterprise-demo-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]">
    <header className="enterprise-demo-header"><p className="section-kicker">{t("Enterprise product demonstration", "Demostración de producto enterprise")}</p><h2 className="section-display">{t("From ambiguous information to a better-prepared decision.", "De información ambigua a una decisión mejor preparada.")}</h2><p className="section-lead">{t("Select a flow and observe how Virro applies privacy, estimates readiness, detects interpretation risks and prepares an operational signal without storing raw content by default.", "Selecciona un flujo y observa cómo Virro aplica privacidad, estima readiness, detecta riesgos de interpretación y entrega una señal operativa sin guardar contenido crudo por defecto.")}</p></header>
    <div className="enterprise-demo-selector" role="tablist" aria-label={t("Enterprise flow selector", "Selector de flujos enterprise")}>{scenarios.map((scenario, index) => <button key={scenario.id} id={`enterprise-demo-tab-${scenario.id}`} role="tab" type="button" aria-selected={scenario.id === activeId} aria-controls={`enterprise-demo-panel-${scenario.id}`} tabIndex={scenario.id === activeId ? 0 : -1} onClick={() => setActiveId(scenario.id)} onKeyDown={(event) => moveTab(event, index)} className={scenario.id === activeId ? "is-active" : ""}>{pick(scenario.flow, locale)}</button>)}</div>
    <div className="enterprise-demo-path" aria-label={t("Virro product decision path", "Ruta de decisión del producto Virro")}><span>{t("Initial information", "Información inicial")}</span><ArrowRight /><span>Privacy Shield</span><ArrowRight /><span>Readiness Gate</span><ArrowRight /><span>{t("Recommended pack", "Pack recomendado")}</span><ArrowRight /><span>{t("Operational deliverable", "Entregable operativo")}</span><ArrowRight /><span>{t("Executive signal", "Señal ejecutiva")}</span></div>
    <div id={`enterprise-demo-panel-${active.id}`} role="tabpanel" aria-labelledby={`enterprise-demo-tab-${active.id}`} className="enterprise-demo-experience" key={active.id}>
      <article className="enterprise-input-zone"><div className="enterprise-zone-label"><Layers3 size={14} />01 · {t("Initial information", "Información inicial")}</div><p className="enterprise-flow-name">{pick(active.flow, locale)}</p><span className="enterprise-risk-badge"><CircleAlert size={13} />{pick(active.riskLabel, locale)}</span><blockquote>“{pick(active.input, locale)}”</blockquote><p className="enterprise-reason">{pick(active.reason, locale)}</p><div className="enterprise-risk-list">{active.risks.map((risk) => <span key={risk.es}><CircleAlert size={12} />{pick(risk, locale)}</span>)}</div></article>
      <article className="enterprise-engine-zone"><div className="enterprise-zone-label"><Radar size={14} />02 · Virro Core Understanding Engine</div><div className="engine-core-marker"><i /><span>Analyze-Safe</span><b>{t("Active", "Activo")}</b></div><div className="engine-module engine-privacy"><div><LockKeyhole size={15} /><span>Privacy Shield</span></div><p>{t("Masking sensitive entities before analysis", "Enmascara entidades sensibles antes del análisis")}</p><div className="masking-lines" aria-label={t("Masking demonstration", "Demostración de enmascaramiento")}>{active.mask.map(([raw, masked], index) => <span key={raw} style={{ "--mask-delay": `${index * 100 + 100}ms` } as React.CSSProperties}><em>{raw}</em><ArrowRight size={11} /><strong>{masked}</strong></span>)}</div></div><div className="engine-module engine-readiness"><div><Radar size={15} /><span>Readiness Gate</span><AnimatedScore target={active.score} /></div><div className="readiness-meter" aria-label={`Readiness ${active.score}/100`}><i style={{ "--readiness": `${active.score}%` } as React.CSSProperties} /></div><p>{t("Context still needs validation before this can advance.", "El contexto todavía necesita validación antes de que esto pueda avanzar.")}</p></div><div className="engine-module engine-pack"><div><Sparkles size={15} /><span>{t("Recommended pack", "Pack recomendado")}</span><b>{t("Selected", "Seleccionado")}</b></div><div className="engine-analysis-status"><span>{t("Reading receiver…", "Analizando receptor…")}</span><span>{t("Detecting pattern…", "Detectando patrón…")}</span><strong>{active.pack}</strong></div><p>{pick(active.packCopy, locale)}</p></div><div className="engine-storage-proof"><ShieldCheck size={14} /><span>Raw data stored: No</span><span>Privacy mode: Safe</span><b>Signals stored: readiness, risks, patterns</b></div><p className="engine-privacy-note">{t("Virro processes raw content transiently and retains operational signals, not private conversations.", "Virro procesa el contenido crudo de forma transitoria y conserva señales operativas, no conversaciones privadas.")}</p></article>
      <article className="enterprise-decision-zone"><div className="enterprise-zone-label"><FileCheck2 size={14} />03 · {t("Executive signal", "Señal ejecutiva")}</div><p className="decision-overline">{t("Recommended decision", "DECISIÓN RECOMENDADA")}</p><h3>{pick(active.decision, locale)}</h3><p>{pick(active.decisionCopy, locale)}</p><div className="decision-deliverable"><span>{t("Operational deliverable", "Entregable operativo")}</span><strong>{pick(active.output, locale)}</strong><ul>{active.checklist.map((item) => <li key={item.es}><Check size={13} />{pick(item, locale)}</li>)}</ul></div><a href="#solicitar-diagnostico">{pick(active.cta, locale)} <ArrowRight size={13} /></a></article>
    </div>
  </div></section>;
}
