"use client";

import Link from "next/link";
import { ArrowRight, CircleAlert, FileText, Network, ShieldCheck, Sparkles } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";

const flows = [
  { en: "Sales → Delivery", es: "Ventas → Delivery", score: 41, tone: "risk" },
  { en: "Product → Development", es: "Producto → Desarrollo", score: 62, tone: "warn" },
  { en: "Support → Product", es: "Soporte → Producto", score: 54, tone: "warn" },
  { en: "Company → AI", es: "Empresa → IA", score: 38, tone: "risk" },
  { en: "Process → Automation", es: "Proceso → Automatización", score: 71, tone: "ready" },
];

export function EnterpriseUnderstandingMap() {
  const { locale, t } = useLanguage();
  return <section id="enterprise-map" className="enterprise-map-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto grid max-w-[1380px] gap-12 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div><p className="section-kicker">Enterprise Understanding Map</p><h2 className="section-display">{t("The map that shows where misunderstood information is costing the company.", "El mapa que muestra dónde la información mal entendida está costando a la empresa.")}</h2><p className="section-lead mt-6">{t("A focused audit reviews real transfers with data minimization and builds an executive view of context gaps, weak handoffs, low readiness and quick wins.", "Una auditoría enfocada revisa transferencias reales con minimización de datos y construye una vista ejecutiva de contexto faltante, handoffs débiles, readiness bajo y quick wins.")}</p><div className="mt-8 grid gap-2 sm:grid-cols-2">{[t("Risk by flow", "Riesgo por flujo"), t("Missing context", "Contexto faltante"), t("Recommended pack", "Pack recomendado"), t("Priority next action", "Siguiente acción prioritaria")].map((item) => <div key={item} className="map-deliverable"><ShieldCheck size={13} />{item}</div>)}</div><Link href="/app/reports" className="mt-8 inline-flex items-center gap-2 text-xs font-semibold text-[var(--brand-blue)]">{t("Open an executive report example", "Abrir ejemplo de reporte ejecutivo")} <ArrowRight size={13} /></Link></div>
    <div className="enterprise-map-visual visual-dark"><div className="enterprise-map-toolbar"><div><span>{t("Audit workspace · Simulated data", "Workspace de auditoría · Datos simulados")}</span><strong>Aperture Systems</strong></div><div className="map-status"><i />{t("Human validation required", "Requiere validación humana")}</div></div><div className="enterprise-map-grid"><div className="map-flow-panel"><p>{t("Understanding transfer map", "Mapa de transferencias de entendimiento")}</p><div className="map-flow-canvas"><div className="map-core-node"><Network size={18} /><b>Virro</b><small>Understanding Layer</small></div>{["Dirección", "Producto", "Diseño", "Dev", "QA", "Ventas", "Soporte", "IA"].map((label, index) => <span key={label} className="map-area-node" style={{ "--map-index": index } as React.CSSProperties}>{locale === "es" ? label : ["Leadership", "Product", "Design", "Dev", "QA", "Sales", "Support", "AI"][index]}</span>)}</div></div><div className="map-scores-panel"><div className="map-panel-heading"><p>{t("Readiness by transfer", "Readiness por transferencia")}</p><span>{t("Estimated", "Estimado")}</span></div><div className="map-flow-list">{flows.map((flow) => <div key={flow.en}><div><span>{locale === "es" ? flow.es : flow.en}</span><b className={`map-score-${flow.tone}`}>{flow.score}</b></div><i><em className={`map-bar-${flow.tone}`} style={{ width: `${flow.score}%` }} /></i></div>)}</div></div></div><div className="enterprise-map-bottom"><article><CircleAlert size={15} /><div><span>{t("Top risk", "Riesgo principal")}</span><strong>{t("Commercial scope changes before delivery", "El alcance comercial cambia antes de delivery")}</strong></div></article><article><Sparkles size={15} /><div><span>{t("Recommended pack", "Pack recomendado")}</span><strong>Handoff Intelligence</strong></div></article><article><FileText size={15} /><div><span>{t("Next action", "Siguiente acción")}</span><strong>{t("Validate scope owner and acceptance evidence", "Validar responsable de alcance y evidencia de aceptación")}</strong></div></article></div></div>
  </div></section>;
}
