"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Bot, ChartNoAxesCombined, CheckCircle2, FileBarChart, Inbox, Layers3, LockKeyhole, ShieldCheck } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";
import { CountUpMetric, MotionCard } from "@/components/landing/motion/motion-primitives";

type WalkthroughId = "dashboard" | "inbox" | "packs" | "reports" | "trust";

export function ProductWalkthrough() {
  const { t } = useLanguage();
  const [active, setActive] = useState<WalkthroughId>("dashboard");
  const tabs: Array<{ id: WalkthroughId; label: string; description: string; href: string }> = [
    { id: "dashboard", label: t("Executive Dashboard", "Dashboard ejecutivo"), description: t("Risk, debt and readiness in one view", "Riesgo, deuda y readiness en una vista"), href: "/app" },
    { id: "inbox", label: "Understanding Inbox", description: t("From scattered input to a traceable event", "Del input disperso a un evento trazable"), href: "/app/inbox" },
    { id: "packs", label: t("Analysis Packs", "Packs de análisis"), description: t("Evidence adapted to each critical flow", "Evidencia adaptada a cada flujo crítico"), href: "/app/product-delivery" },
    { id: "reports", label: t("Executive Reports", "Reportes ejecutivos"), description: t("Findings translated into decisions", "Hallazgos convertidos en decisiones"), href: "/app/reports" },
    { id: "trust", label: t("Trust & Privacy", "Confianza y privacidad"), description: t("Visible data boundaries and governance", "Límites de datos y gobernanza visibles"), href: "/app/privacy-trust" },
  ];
  const current = tabs.find((tab) => tab.id === active) ?? tabs[0];

  return <div className="walkthrough-shell mt-12 overflow-hidden rounded-[28px] border border-[var(--border)] bg-[var(--panel)] shadow-[0_36px_120px_rgba(0,0,0,.18)]"><div className="grid border-b border-[var(--border)] lg:grid-cols-[.32fr_.68fr]"><div className="border-b border-[var(--border)] p-4 lg:border-b-0 lg:border-r lg:p-6"><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-[var(--subtle)]">{t("Enterprise demo · Simulated data", "Demo enterprise · Datos simulados")}</p><div role="tablist" aria-label={t("Product modules", "Módulos del producto")} className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-1">{tabs.map((tab, index) => <button key={tab.id} type="button" role="tab" aria-selected={active === tab.id} aria-controls={`walkthrough-${tab.id}`} onClick={() => setActive(tab.id)} className={`walkthrough-tab group relative rounded-xl border p-3.5 text-left ${active === tab.id ? "is-active border-sky-400/25 bg-sky-400/[.055]" : "border-transparent hover:border-[var(--border)] hover:bg-[var(--hover)]"}`}><div className="flex items-center justify-between"><span className={`text-[9px] font-semibold ${active === tab.id ? "text-[var(--brand-blue)]" : "text-[var(--subtle)]"}`}>0{index + 1}</span><ArrowRight size={12} className={active === tab.id ? "text-[var(--brand-blue)]" : "text-[var(--subtle)]"} /></div><p className="mt-2 text-xs font-semibold">{tab.label}</p><p className="mt-1 text-[9px] leading-4 text-[var(--subtle)]">{tab.description}</p></button>)}</div></div><div className="visual-dark min-h-[500px] min-w-0 bg-[#090d13] p-5 text-[#f2f5f7] md:p-8"><div key={active} id={`walkthrough-${active}`} role="tabpanel" className="walkthrough-panel">{active === "dashboard" && <DashboardScene t={t} />}{active === "inbox" && <InboxScene t={t} />}{active === "packs" && <PacksScene t={t} />}{active === "reports" && <ReportScene t={t} />}{active === "trust" && <TrustScene t={t} />}</div></div></div><div className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center md:px-7"><div><h3 className="text-sm font-semibold">{current.label}</h3><p className="mt-1 text-[10px] text-[var(--muted)]">{current.description}</p></div><Link href={current.href} className="group inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] px-4 text-[10px] font-semibold transition hover:-translate-y-0.5 hover:border-sky-400/25">{t("Open in demo", "Abrir en demo")} <ArrowRight size={12} /></Link></div></div>;
}

type Translator = (english: string, spanish: string) => string;

function SceneHeader({ eyebrow, title, icon: Icon }: { eyebrow: string; title: string; icon: typeof Inbox }) { return <div className="flex items-center justify-between"><div><p className="text-[8px] font-semibold uppercase tracking-[.15em] text-sky-300">{eyebrow}</p><h3 className="mt-2 text-lg font-semibold tracking-[-.03em]">{title}</h3></div><Icon size={20} className="text-sky-300" /></div>; }
function DashboardScene({ t }: { t: Translator }) { return <div><SceneHeader eyebrow={t("Executive workspace", "Workspace ejecutivo")} title={t("Where operational risk concentrates", "Dónde se concentra el riesgo operativo")} icon={ChartNoAxesCombined} /><div className="mt-7 grid grid-cols-3 gap-2"><Metric label="DoU Score" value={68} tone="teal" /><Metric label="Meaning Loss" value={34} tone="rose" /><Metric label={t("At-risk handoffs", "Handoffs en riesgo")} value={1} tone="amber" suffix="" /></div><div className="mt-4 grid gap-4 sm:grid-cols-[1.15fr_.85fr]"><Card title={t("Risk by area", "Riesgo por área")}><RiskLine label={t("Technical context", "Contexto técnico")} value={61} tone="rose" /><RiskLine label="Handoff Intelligence" value={38} tone="amber" /><RiskLine label="Product Delivery" value={24} tone="teal" /></Card><Card title={t("Recommended next action", "Siguiente acción recomendada")}><p className="rounded-xl border border-sky-400/15 bg-sky-400/[.045] p-4 text-[10px] leading-5">{t("Resolve rollback ownership before migrating consumers.", "Resolver el ownership de rollback antes de migrar consumidores.")}</p></Card></div></div>; }
function InboxScene({ t }: { t: Translator }) { return <div><SceneHeader eyebrow="Understanding Event" title={t("Turn ambiguity into an auditable event", "Convierte ambigüedad en un evento auditable")} icon={Inbox} /><div className="mt-7 grid gap-4 sm:grid-cols-2"><Card title={t("Scattered input", "Input disperso")}><p className="text-[11px] leading-6">“{t("Move the service without affecting consumers.", "Mover el servicio sin afectar a los consumidores.")}”</p><p className="mt-5 flex items-center gap-2 text-[9px] text-rose-300"><ShieldCheck size={12} /> {t("Insufficient operational context", "Contexto operativo insuficiente")}</p></Card><Card title={t("Classification", "Clasificación")}><p className="text-xs font-semibold">Handoff Intelligence</p><p className="mt-2 text-[9px] text-[var(--muted)]">Development → QA</p><div className="mt-5 h-2 rounded-full bg-white/[.06]"><div className="h-full w-[48%] rounded-full bg-amber-300" /></div><p className="mt-2 text-[8px] text-[var(--subtle)]">Handoff Readiness · 48/100</p></Card></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{[t("Who approves rollback?", "¿Quién aprueba el rollback?"), t("Which consumers migrate first?", "¿Qué consumidores migran primero?"), t("What evidence defines success?", "¿Qué evidencia define éxito?")].map((q) => <div key={q} className="rounded-xl border border-white/[.07] bg-white/[.025] p-3 text-[9px] leading-4 text-[var(--muted)]"><CheckCircle2 size={11} className="mb-2 text-indigo-300" />{q}</div>)}</div></div>; }
function PacksScene({ t }: { t: Translator }) { const packs = [["Product Delivery", PackageIcon], ["AI Understanding", Bot], ["Handoff Intelligence", Layers3], [t("Technical Documentation", "Documentación técnica"), FileBarChart]]; return <div><SceneHeader eyebrow={t("Context-specific analysis", "Análisis específico por contexto")} title={t("The right evidence for each receiver", "La evidencia adecuada para cada receptor")} icon={Layers3} /><div className="mt-7 grid gap-3 sm:grid-cols-2">{packs.map(([label, Icon]) => { const I = Icon as typeof Bot; return <MotionCard key={String(label)} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><I size={17} className="text-sky-300" /><p className="mt-4 text-xs font-semibold">{String(label)}</p><p className="mt-2 text-[9px] leading-4 text-[var(--muted)]">{t("Missing context · critical questions · readiness · operational deliverable", "Contexto faltante · preguntas críticas · readiness · entregable operativo")}</p></MotionCard>; })}</div></div>; }
function ReportScene({ t }: { t: Translator }) { return <div><SceneHeader eyebrow="Virro Enterprise Report" title="Meaning Loss Audit" icon={FileBarChart} /><div className="mt-7 grid gap-px overflow-hidden rounded-2xl border border-white/[.07] bg-white/[.07] sm:grid-cols-2">{[[t("Analyzed flow", "Flujo analizado"), "Product → Development"], [t("Reviewed events", "Eventos revisados"), t("4 · simulated data", "4 · datos simulados")], [t("Estimated score", "Score estimado"), "Handoff Readiness · 48/100"], [t("Recommendation", "Recomendación"), t("Handoff Intelligence pilot", "Piloto de Handoff Intelligence")]].map(([label, value]) => <div key={label} className="bg-[#0b1019] p-5"><p className="text-[8px] uppercase tracking-[.12em] text-[var(--subtle)]">{label}</p><p className="mt-3 text-[10px] font-medium leading-5">{value}</p></div>)}</div><p className="mt-4 flex items-center gap-2 text-[8px] text-[var(--subtle)]"><ShieldCheck size={11} className="text-sky-300" /> {t("Probabilistic estimate · human validation required", "Estimación probabilística · requiere validación humana")}</p></div>; }
function TrustScene({ t }: { t: Translator }) { return <div><SceneHeader eyebrow={t("Governance by design", "Gobernanza por diseño")} title={t("More trustworthy than intelligent", "Más confiable que inteligente")} icon={LockKeyhole} /><div className="mt-7 grid gap-4 sm:grid-cols-2"><Card title={t("Private Mode", "Modo privado")}><ul className="space-y-3 text-[9px] leading-4 text-[var(--muted)]"><li>✓ {t("Raw inputs are not retained unnecessarily", "Los inputs crudos no se conservan innecesariamente")}</li><li>✓ {t("No employee surveillance", "Sin vigilancia de empleados")}</li><li>✓ {t("Explicit scope before real pilots", "Alcance explícito antes de pilotos reales")}</li></ul></Card><Card title={t("Visible controls", "Controles visibles")}><div className="space-y-3">{[t("Data boundaries", "Límites de datos"), t("Retention policy", "Política de retención"), t("Analysis transparency", "Transparencia del análisis")].map((item) => <div key={item} className="flex items-center justify-between rounded-lg border border-white/[.06] p-3 text-[9px]"><span>{item}</span><span className="text-emerald-300">{t("Defined", "Definido")}</span></div>)}</div></Card></div></div>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <MotionCard className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><p className="mb-4 text-[9px] font-semibold">{title}</p>{children}</MotionCard>; }
function Metric({ label, value, tone, suffix = "/100" }: { label: string; value: number; tone: "teal" | "rose" | "amber"; suffix?: string }) { const color = tone === "rose" ? "text-rose-300" : tone === "amber" ? "text-amber-300" : "text-teal-300"; return <MotionCard className="rounded-xl border border-white/[.07] bg-white/[.025] p-3"><p className="text-[8px] text-[var(--subtle)]">{label}</p><p className={`mt-1 text-xl font-semibold ${color}`}><CountUpMetric value={value} /><span className="ml-1 text-[7px] text-[var(--subtle)]">{suffix}</span></p></MotionCard>; }
function RiskLine({ label, value, tone }: { label: string; value: number; tone: "teal" | "rose" | "amber" }) { const color = tone === "rose" ? "bg-rose-400" : tone === "amber" ? "bg-amber-300" : "bg-teal-300"; return <div className="mb-3 last:mb-0"><div className="flex justify-between text-[8px] text-[var(--muted)]"><span>{label}</span><span>{value}</span></div><div className="mt-1.5 h-1 overflow-hidden rounded-full bg-white/[.07]"><div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} /></div></div>; }
const PackageIcon = Layers3;
