"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Braces, CheckCircle2, CircleAlert, FileBarChart, Inbox, LockKeyhole, Network, ShieldCheck } from "lucide-react";
import { ArchitectureOrbit } from "@/components/landing/architecture-orbit";
import { DiagnosisRequestForm } from "@/components/landing/diagnosis-request-form";
import { RevealOnScroll, StaggerGroup } from "@/components/landing/motion/motion-primitives";
import { ProductWalkthrough } from "@/components/landing/product-walkthrough";
import { PublicNavbar } from "@/components/landing/public-navbar";
import { SolutionPanels } from "@/components/landing/solution-panels";
import { useLanguage } from "@/components/i18n/language-provider";

export function PublicLanding() {
  const { t } = useLanguage();
  const problemCards = [
    [t("Different interpretations", "Interpretaciones distintas"), t("The same information becomes different actions depending on role, context or receiver.", "La misma información se convierte en acciones distintas según el rol, contexto o receptor.")],
    [t("Context trapped in tools", "Contexto atrapado en herramientas"), t("Tickets and documents store data without ensuring operational understanding.", "Tickets y documentos almacenan datos sin asegurar entendimiento operativo.")],
    [t("AI operating on assumptions", "IA operando con supuestos"), t("Generic output appears when intent, constraints and authoritative context are incomplete.", "Los resultados genéricos aparecen cuando intención, restricciones y contexto autorizado están incompletos.")],
  ];
  const auditSteps = [
    [t("Select a critical flow", "Seleccionamos un flujo crítico"), t("Product, AI, documentation, staffing, consulting, handoffs, processes or onboarding.", "Producto, IA, documentación, staffing, consultoras, handoffs, procesos u onboarding."), Network],
    [t("Review 3 to 5 Understanding Events", "Revisamos 3 a 5 Understanding Events"), t("Tickets, briefs, documents, AI instructions, roles, handoffs or processes.", "Tickets, briefs, documentos, instrucciones para IA, vacantes, handoffs o procesos."), Inbox],
    [t("Detect meaning loss risk", "Detectamos riesgo de pérdida de significado"), t("Missing context, interpretation risks, assumptions and critical questions.", "Contexto faltante, riesgos de interpretación, supuestos y preguntas críticas."), CircleAlert],
    [t("Deliver an executive report", "Entregamos un reporte ejecutivo"), t("Estimated scores, correction priorities and a pilot recommendation.", "Scores estimados, prioridades de corrección y recomendación de piloto."), FileBarChart],
  ] as const;
  const reportRows = [
    [t("Analyzed flow", "Flujo analizado"), "Product → Development"],
    [t("Reviewed events", "Eventos revisados"), "3–5 Understanding Events"],
    [t("Primary risk", "Riesgo principal"), t("Rollback ownership is undefined", "Ownership de rollback no definido")],
    [t("Critical questions to validate", "Preguntas críticas para validar"), t("Receiver, decision and boundaries pending validation", "Receptor, decisión y límites pendientes de validar")],
    [t("Estimated score", "Score estimado"), "Handoff Readiness · 48/100"],
    [t("Recommendation", "Recomendación"), t("Handoff Intelligence pilot", "Piloto de Handoff Intelligence")],
  ];

  return <div className="public-landing min-h-screen overflow-hidden bg-[var(--app-bg)] text-[var(--text)]"><PublicNavbar /><main>
    <section id="categoria" className="landing-hero relative px-5 pb-24 pt-36 md:px-8 md:pb-36 md:pt-44"><div className="hero-glow hero-glow-one" /><div className="hero-glow hero-glow-two" /><Image src="/brand/virro-icon.svg" alt="" width={640} height={520} aria-hidden className="hero-watermark pointer-events-none absolute -right-28 top-24 h-auto w-[520px] object-contain" /><div className="relative mx-auto grid max-w-7xl gap-16 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="hero-copy-scene"><div className="hero-scene-item inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--panel)] px-3 py-1.5 text-[9px] font-semibold uppercase tracking-[.17em] text-[var(--brand-blue)]"><Braces size={12} /> Operating Understanding Layer</div><h1 className="hero-scene-item mt-7 max-w-4xl text-[2.75rem] font-semibold leading-[.99] tracking-[-.062em] sm:text-6xl lg:text-[4.9rem]">{t("The Operating Understanding Layer for Modern Organizations.", "La capa de entendimiento operativo para organizaciones modernas.")}</h1><p className="hero-scene-item mt-7 max-w-2xl text-sm leading-7 text-[var(--muted)] md:text-base">{t("Virro makes interpretation risk, missing context and readiness visible before digital information becomes work, a decision or automation.", "Virro hace visibles el riesgo de interpretación, el contexto faltante y el readiness antes de que la información digital se convierta en trabajo, decisión o automatización.")}</p><div className="hero-scene-item mt-9 flex flex-col gap-3 sm:flex-row"><a href="#solicitar-diagnostico" className="brand-primary-button inline-flex h-12 items-center justify-center gap-2 rounded-full px-6 text-sm font-semibold shadow-[0_20px_60px_rgba(9,105,255,.22)]">{t("Diagnose a critical flow", "Diagnosticar un flujo crítico")} <ArrowRight size={15} /></a><Link href="/app" className="inline-flex h-12 items-center justify-center rounded-full border border-[var(--border)] bg-[var(--panel)] px-6 text-sm font-medium transition hover:-translate-y-0.5 hover:shadow-lg">{t("View enterprise demo", "Ver demo enterprise")}</Link></div><p className="hero-scene-item mt-5 flex items-center gap-2 text-[10px] text-[var(--subtle)]"><ShieldCheck size={13} className="text-[var(--brand-blue)]" /> {t("Estimated scores · No guarantees · No people evaluation", "Scores estimados · No son garantías · No evalúan personas")}</p></div><HeroPreview t={t} /></div></section>

    <section className="thesis-section border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-32"><div className="mx-auto max-w-7xl"><RevealOnScroll><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[var(--brand-coral)]">{t("The invisible operational cost", "El costo operativo invisible")}</p><h2 className="mt-5 max-w-5xl text-4xl font-semibold leading-[1.03] tracking-[-.052em] md:text-6xl">{t("Information can exist, be documented and still not be understood.", "La información puede existir, estar documentada y aun así no estar entendida.")}</h2><p className="mt-6 max-w-3xl text-sm leading-7 text-[var(--muted)]">{t("Virro examines the transfer—not the person—to reveal where meaning can distort before it becomes rework, risk or a weak automation.", "Virro examina la transferencia —no a la persona— para revelar dónde puede distorsionarse el significado antes de convertirse en retrabajo, riesgo o una automatización débil.")}</p></RevealOnScroll><StaggerGroup className="mt-12 grid gap-4 md:grid-cols-3">{problemCards.map(([title, text], index) => <article key={title} className="premium-card min-h-[220px] rounded-[24px] border border-[var(--border)] bg-[var(--panel)] p-6"><span className="text-[9px] font-semibold text-[var(--brand-coral)]">0{index + 1}</span><h3 className="mt-8 text-xl font-semibold tracking-[-.035em]">{title}</h3><p className="mt-3 text-xs leading-6 text-[var(--muted)]">{text}</p></article>)}</StaggerGroup></div></section>

    <ArchitectureOrbit />

    <section id="producto" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[var(--brand-blue)]">{t("Product walkthrough", "Recorrido del producto")}</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.052em] md:text-6xl">{t("From scattered input to executive clarity.", "Del input disperso a claridad ejecutiva.")}</h2></div><p className="max-w-xl text-sm leading-7 text-[var(--muted)] lg:justify-self-end">{t("Explore the complete operating loop with simulated data. Every result remains traceable, estimated and ready for human validation.", "Explora el ciclo operativo completo con datos simulados. Cada resultado permanece trazable, estimado y listo para validación humana.")}</p></div><ProductWalkthrough /></div></section>

    <SolutionPanels />

    <section id="audit" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-7xl overflow-hidden rounded-[32px] border border-[var(--border)] bg-[var(--panel)] shadow-[0_40px_130px_rgba(0,0,0,.18)]"><div className="grid lg:grid-cols-[.76fr_1.24fr]"><div className="audit-offer-panel p-7 md:p-12 lg:p-14"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-[var(--brand-blue)]">{t("Start here", "Empieza aquí")}</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.052em] md:text-6xl">Meaning Loss Audit</h2><p className="mt-5 max-w-xl text-sm leading-7 text-[var(--muted)]">{t("A focused diagnosis of one critical flow to identify where operational meaning can distort before execution.", "Un diagnóstico enfocado en un flujo crítico para identificar dónde puede distorsionarse el significado operativo antes de ejecutar.")}</p><div className="mt-7 inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--panel-soft)] px-4 py-2 text-[10px] font-medium"><CheckCircle2 size={13} className="text-[var(--brand-blue)]" /> {t("Estimated duration: 1 to 2 weeks", "Duración estimada: 1 a 2 semanas")}</div><a href="#solicitar-diagnostico" className="brand-primary-button mt-8 inline-flex h-12 items-center gap-2 rounded-full px-6 text-xs font-semibold">{t("Request a diagnosis", "Solicitar diagnóstico")} <ArrowRight size={14} /></a></div><div className="border-t border-[var(--border)] p-6 md:p-10 lg:border-l lg:border-t-0"><p className="text-[10px] font-semibold uppercase tracking-[.15em] text-[var(--subtle)]">{t("How the audit starts", "Cómo empieza el audit")}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{auditSteps.map(([title, text, Icon], index) => <article key={title} className="audit-step rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-5"><div className="flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-[color-mix(in_srgb,var(--brand-blue)_9%,transparent)] text-[var(--brand-blue)]"><Icon size={16} /></span><span className="text-[9px] font-semibold text-[var(--subtle)]">0{index + 1}</span></div><h3 className="mt-5 text-xs font-semibold">{title}</h3><p className="mt-2 text-[10px] leading-5 text-[var(--muted)]">{text}</p></article>)}</div></div></div><div className="grid gap-3 border-t border-[var(--border)] bg-[var(--panel-soft)] px-7 py-5 text-[9px] leading-4 text-[var(--subtle)] md:grid-cols-3 md:px-12"><p>{t("No people evaluation. The audit examines operational information.", "No evalúa personas. El audit examina información operativa.")}</p><p>{t("Scores are probabilistic estimates, not guarantees.", "Los scores son estimaciones probabilísticas, no garantías.")}</p><p>{t("Privacy and scope are defined before reviewing real events.", "La privacidad y el alcance se definen antes de revisar eventos reales.")}</p></div></div></section>

    <section id="reporte-ejecutivo" className="report-proof scroll-mt-24 border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.78fr_1.22fr] lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-[var(--brand-blue)]">{t("Customer value proof", "Prueba de valor para el cliente")}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.04] tracking-[-.052em] md:text-6xl">{t("Executive clarity on where meaning is lost.", "Claridad ejecutiva sobre dónde se pierde significado.")}</h2><p className="mt-6 text-sm leading-7 text-[var(--muted)]">{t("Virro turns reviewed events into an executive report with interpretation risks, missing context, estimated scores and recommended actions.", "Virro convierte eventos revisados en un reporte ejecutivo con riesgos de interpretación, contexto faltante, scores estimados y acciones recomendadas.")}</p><Link href="/app/reports" className="mt-8 inline-flex h-11 items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--panel)] px-5 text-xs font-semibold">{t("View executive report", "Ver reporte ejecutivo")} <ArrowRight size={13} /></Link></div><div className="report-sheet overflow-hidden rounded-[26px] border border-[var(--border)] bg-[var(--panel)] shadow-[0_34px_110px_rgba(0,0,0,.16)]"><div className="flex items-center justify-between border-b border-[var(--border)] p-6"><div><p className="text-[9px] font-semibold uppercase tracking-[.15em] text-[var(--brand-blue)]">Virro Enterprise Report</p><p className="mt-2 text-lg font-semibold">Meaning Loss Audit</p></div><FileBarChart size={21} className="text-[var(--brand-blue)]" /></div><div className="grid sm:grid-cols-2">{reportRows.map(([label, value]) => <div key={label} className="border-b border-r border-[var(--border)] p-5"><p className="text-[8px] uppercase tracking-[.12em] text-[var(--subtle)]">{label}</p><p className="mt-3 text-[10px] font-medium leading-5">{value}</p></div>)}</div><p className="p-5 text-[9px] leading-5 text-[var(--subtle)]">{t("Reports do not evaluate people. They estimate interpretation risk in operational information.", "Los reportes no evalúan personas. Estiman riesgos de interpretación en información operativa.")}</p></div></div></section>

    <section id="trust" className="scroll-mt-24 px-5 py-24 md:px-8 md:py-32"><div className="mx-auto grid max-w-7xl gap-8 rounded-[30px] border border-[var(--border)] bg-[var(--panel)] p-7 md:p-12 lg:grid-cols-[.8fr_1.2fr]"><div><span className="grid size-11 place-items-center rounded-2xl bg-[color-mix(in_srgb,var(--brand-blue)_9%,transparent)] text-[var(--brand-blue)]"><LockKeyhole size={19} /></span><h2 className="mt-7 text-4xl font-semibold tracking-[-.05em]">{t("More trustworthy than intelligent.", "Más confiable que inteligente.")}</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">{t("Trust is not a disclaimer. It is part of how Virro defines scope, retention, evidence and human validation.", "La confianza no es un disclaimer. Es parte de cómo Virro define alcance, retención, evidencia y validación humana.")}</p></div><div className="grid gap-3 sm:grid-cols-2">{[t("No private conversations stored by default", "No guarda conversaciones privadas por defecto"), t("No unnecessary raw messages retained", "No conserva mensajes crudos innecesarios"), t("No employee surveillance", "No vigila empleados"), t("No personal performance scores", "No genera scores de desempeño personal")].map((item) => <div key={item} className="flex items-start gap-3 rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-5 text-[10px] leading-5"><ShieldCheck size={14} className="mt-0.5 shrink-0 text-[var(--brand-blue)]" />{item}</div>)}</div></div></section>

    <DiagnosisRequestForm />
  </main><footer className="border-t border-[var(--border)] px-5 py-10 md:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><Link href="/" className="flex items-center gap-2"><Image src="/brand/virro-icon.svg" alt="" width={25} height={21} /><span className="font-semibold tracking-[-.04em]">Virro</span></Link><p className="text-[9px] text-[var(--subtle)]">Operating Understanding Layer · {t("Probabilistic estimates, human validation", "Estimaciones probabilísticas, validación humana")}</p><div className="flex gap-4 text-[10px]"><Link href="/app/privacy-trust">{t("Privacy", "Privacidad")}</Link><Link href="/app">{t("Enterprise demo", "Demo enterprise")}</Link></div></div></footer></div>;
}

type Translator = (english: string, spanish: string) => string;
function HeroPreview({ t }: { t: Translator }) { return <div className="hero-product-scene relative"><div className="hero-preview-back absolute inset-8 -rotate-3 rounded-[28px] border border-[var(--border)] bg-[var(--panel-soft)]" /><div className="hero-preview relative overflow-hidden rounded-[28px] border border-[var(--border)] bg-[var(--panel)] shadow-[0_40px_130px_rgba(0,0,0,.24)]"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><div><p className="text-[8px] font-semibold uppercase tracking-[.14em] text-[var(--brand-blue)]">{t("Demo workspace · Simulated data", "Demo workspace · Datos simulados")}</p><p className="mt-1 text-xs font-semibold">{t("Executive understanding", "Entendimiento ejecutivo")}</p></div><span className="size-2 rounded-full bg-emerald-400" /></div><div className="p-5"><div className="grid grid-cols-3 gap-2">{[["DoU Score", "68"], ["Meaning Loss", "34"], ["Handoff", "48"]].map(([label, value], index) => <div key={label} className="rounded-xl border border-[var(--border)] bg-[var(--panel-soft)] p-3"><p className="text-[8px] text-[var(--subtle)]">{label}</p><p className={`mt-2 text-2xl font-semibold ${index === 1 ? "text-rose-300" : index === 2 ? "text-amber-300" : "text-[var(--brand-blue)]"}`}>{value}</p></div>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-4"><p className="text-[9px] font-semibold">{t("Meaning loss risk", "Riesgo de pérdida de significado")}</p>{[[t("Technical context", "Contexto técnico"), 61], [t("Product handoff", "Handoff de producto"), 38], [t("AI context", "Contexto para IA"), 24]].map(([label, value]) => <div key={String(label)} className="mt-4"><div className="flex justify-between text-[8px] text-[var(--subtle)]"><span>{label}</span><span>{value}</span></div><div className="mt-1.5 h-1 rounded-full bg-[var(--border)]"><div className="h-full rounded-full bg-[var(--brand-blue)]" style={{ width: `${value}%` }} /></div></div>)}</div><div className="rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] p-4"><p className="text-[9px] font-semibold">{t("Next action", "Siguiente acción")}</p><div className="mt-4 rounded-xl border border-[color-mix(in_srgb,var(--brand-blue)_20%,transparent)] bg-[color-mix(in_srgb,var(--brand-blue)_5%,transparent)] p-3 text-[9px] leading-5 text-[var(--muted)]">{t("Validate rollback ownership before the handoff advances.", "Validar ownership de rollback antes de que avance el handoff.")}</div></div></div></div></div></div>; }
