"use client";

import Link from "next/link";
import { ArrowUpRight, BarChart3, Bot, BriefcaseBusiness, Code2, FileCog, Network, RefreshCw, UsersRound, Workflow } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";

const packs = [
  { icon: Code2, name: "Product Delivery Understanding", en: "Helps product, design, development, QA and scrum work with stories, criteria, bugs, matrices, recaps and handoffs aligned to company standards.", es: "Ayuda a producto, diseño, desarrollo, QA y scrum a trabajar con HUs, criterios, bugs, matrices, recaps y handoffs más claros y alineados a los estándares de la empresa.", risk: ["Delivery based on outdated or incomplete criteria.", "Delivery basado en criterios incompletos o desactualizados."], review: ["Stories, acceptance, bugs and QA evidence.", "HUs, aceptación, bugs y evidencia QA."], outputs: ["Story Bundle", "Acceptance Gate", "QA Pack"] },
  { icon: Network, name: "Handoff Intelligence", en: "Checks whether information moving between teams retains enough context, criteria and expected action to reduce rework.", es: "Valida si la información que pasa de un equipo a otro conserva suficiente contexto, criterio y acción esperada para reducir retrabajo.", risk: ["Context lost between teams.", "Contexto perdido entre equipos."], review: ["Owner, dependencies and expected action.", "Responsable, dependencias y acción esperada."], outputs: ["Handoff Pack", "Receiver Check", "Readiness"] },
  { icon: Bot, name: "AI Understanding", en: "Helps the AI already used by the company understand its context, processes, rules, standards and operating changes.", es: "Ayuda a que la IA que ya usa la empresa entienda mejor su contexto, procesos, reglas, estándares y cambios operativos.", risk: ["AI acting on old or incomplete context.", "IA actuando con contexto viejo o incompleto."], review: ["Rules, boundaries, evidence and updates.", "Reglas, límites, evidencia y actualizaciones."], outputs: ["AI Context Pack", "Output Check", "Context Update"] },
  { icon: Workflow, name: "Process Understanding", en: "Turns internal processes into guides understandable by area, role, provider, consultancy or AI system.", es: "Convierte procesos internos en guías entendibles por área, rol, proveedor, consultora o sistema de IA.", risk: ["Processes interpreted differently by each receiver.", "Procesos interpretados distinto por cada receptor."], review: ["Triggers, decisions, rules and exceptions.", "Disparadores, decisiones, reglas y excepciones."], outputs: ["Process Map", "Decision Rules", "Role Guide"] },
  { icon: FileCog, name: "Technical Documentation Understanding", en: "Keeps documentation, runbooks, ADRs, tickets and technical criteria understandable, current and actionable.", es: "Mantiene documentación, runbooks, ADRs, tickets y criterios técnicos entendibles, vigentes y accionables.", risk: ["Technical knowledge becoming obsolete.", "Conocimiento técnico que queda obsoleto."], review: ["Dependencies, decisions and recovery rules.", "Dependencias, decisiones y reglas de recuperación."], outputs: ["Runbook Update", "ADR Context", "Technical Brief"] },
  { icon: RefreshCw, name: "Change Understanding", en: "Helps when priorities, scope, providers, tools, integrations, critical errors or blockers change.", es: "Ayuda cuando cambian prioridades, alcance, proveedores, herramientas, integraciones, errores críticos o bloqueantes.", risk: ["Teams continuing with the previous reality.", "Equipos operando con la realidad anterior."], review: ["Impact, affected artifacts and next actions.", "Impacto, artefactos afectados y siguientes acciones."], outputs: ["Change Map", "Update Plan", "Executive Summary"] },
  { icon: UsersRound, name: "Onboarding & Knowledge Transfer", en: "Turns operating context, tools, standards, processes and recent changes into guides for new people, consultants, providers or external talent.", es: "Convierte contexto operativo, herramientas, estándares, procesos y cambios recientes en guías para nuevas personas, consultores, proveedores o talento externo.", risk: ["Critical knowledge leaving with people or vendors.", "Conocimiento crítico que se va con personas o proveedores."], review: ["Recent decisions, owners and operating standards.", "Decisiones recientes, responsables y estándares operativos."], outputs: ["Onboarding Pack", "Transfer Map", "Role Guide"] },
  { icon: BriefcaseBusiness, name: "Consulting Delivery", en: "Helps consultancies and software factories understand client context, delivery rules, handoffs, risks and execution standards.", es: "Ayuda a consultoras y software factories a entender mejor el contexto del cliente, reglas de entrega, handoffs, riesgos y estándares de ejecución.", risk: ["External delivery misaligned with client operations.", "Entrega externa desalineada de la operación del cliente."], review: ["Client context, scope and delivery rules.", "Contexto del cliente, alcance y reglas de entrega."], outputs: ["Client Context Pack", "Delivery Rules", "Risk Brief"] },
  { icon: UsersRound, name: "Talent & Staffing Understanding", en: "Translates real client needs into criteria for sourcing, evaluation, presentation and candidate onboarding.", es: "Ayuda a consultoras de talento a traducir necesidades reales del cliente en criterios de búsqueda, evaluación, presentación y onboarding de candidatos.", risk: ["Profiles evaluated against an ambiguous need.", "Perfiles evaluados contra una necesidad ambigua."], review: ["Role context, evidence and success criteria.", "Contexto del rol, evidencia y criterios de éxito."], outputs: ["Role Brief", "Evaluation Matrix", "Onboarding Context"] },
  { icon: BarChart3, name: "Data Request Understanding", en: "Turns report, metric or dashboard requests into clear business questions for Data and BI.", es: "Ayuda a convertir solicitudes de reportes, métricas o dashboards en preguntas de negocio claras, accionables y entendibles para Data/BI.", risk: ["Data work without a clear business decision.", "Trabajo de datos sin una decisión de negocio clara."], review: ["Question, metric, period and audience.", "Pregunta, métrica, periodo y audiencia."], outputs: ["Data Request Pack", "Metric Context", "Decision Brief"] },
];

export function SolutionPanels() {
  const { locale, t } = useLanguage();
  return <section id="packs" className="solution-panels-section scroll-mt-24 border-y border-[var(--border)] bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="max-w-4xl"><p className="section-kicker">{t("Operational understanding applications", "Aplicaciones de entendimiento operativo")}</p><h2 className="section-display">{t("One understanding layer. Applied across the company.", "Una capa de entendimiento. Aplicada en toda la empresa.")}</h2><p className="section-lead mt-6 max-w-3xl">{t("Each pack applies the same enterprise layer to the flow, change or knowledge transfer that needs clarity.", "Cada pack aplica la misma capa enterprise al flujo, cambio o transferencia de conocimiento que necesita claridad.")}</p></div><div className="pack-catalog-grid mt-12">{packs.map(({ icon: Icon, name, en, es, risk, review, outputs }, index) => <article key={name} className="solution-panel is-priority group relative overflow-hidden rounded-[26px] border border-[var(--border)] bg-[var(--panel)]"><div className="solution-panel-number">{String(index + 1).padStart(2, "0")}</div><div className="relative flex h-full flex-col"><span className="grid size-11 place-items-center rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] text-[var(--brand-blue)]"><Icon aria-hidden="true" size={19} /></span><h3>{name}</h3><div className="solution-panel-brief"><div><span>{t("Application", "Aplicación")}</span><p>{locale === "es" ? es : en}</p></div><div><span>{t("Risk reduced", "Riesgo que reduce")}</span><p>{locale === "es" ? risk[1] : risk[0]}</p></div><div><span>{t("Virro reviews", "Virro revisa")}</span><p>{locale === "es" ? review[1] : review[0]}</p></div><div><span>{t("Deliverables", "Entregables")}</span><p>{outputs.join(" · ")}</p></div></div><Link href="#solicitar-diagnostico" className="brand-secondary-button mt-auto self-start text-[10px]">{t("Evaluate in an audit", "Evaluar en auditoría")} <ArrowUpRight aria-hidden="true" size={13} className="transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link></div></article>)}</div><div className="solution-bundle-note"><span>{t("Start with one pack", "Inicia con un pack")}</span><span>{t("Combine capability blocks", "Combina bloques")}</span><span>{t("Receive an audit recommendation", "Recibe recomendación")}</span><span>{t("Scale through staged bundles", "Escala por bundles")}</span></div><Link href="/app" className="brand-secondary-button mx-auto mt-7 text-xs">{t("View all packs", "Ver todos los packs")} <ArrowUpRight aria-hidden="true" size={14} /></Link></div></section>;
}
