"use client";

import Link from "next/link";
import { ArrowUpRight, BarChart3, Bot, BriefcaseBusiness, Code2, FileCheck2, Gavel, Headphones, Landmark, Megaphone, Network, Palette, Settings2, UserRoundSearch, Workflow } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";

const packs = [
  { icon: Code2, name: "Product Delivery Readiness", href: "/app/product-delivery", en: "Turns product intent into information ready for development and QA.", es: "Convierte intención de producto en información lista para desarrollo y QA.", outputs: ["Story Bundle", "Acceptance Gate", "QA Pack"] },
  { icon: Bot, name: "AI Understanding", href: "/app/ai-understanding", en: "Prepares context, boundaries and evidence for safer AI use.", es: "Prepara contexto, límites y evidencia para un uso más seguro de IA.", outputs: ["AI Context Pack", "Output Check", "Token Waste Risk"] },
  { icon: Network, name: "Handoff Intelligence", href: "/app/handoff-intelligence", en: "Checks whether the next receiver can act without preventable rework.", es: "Valida si el siguiente receptor puede actuar sin retrabajo prevenible.", outputs: ["Handoff Pack", "Receiver Check", "Readiness"] },
  { icon: Workflow, name: "Process Understanding", href: "/app/process-understanding", en: "Makes triggers, decisions, rules and exceptions transferable.", es: "Hace transferibles disparadores, decisiones, reglas y excepciones.", outputs: ["Process Map", "Decision Rules", "Automation Gate"] },
  { icon: FileCheck2, name: "Technical Documentation Readiness", href: "/app/technical-documentation", en: "Validates whether technical context supports safe action and change.", es: "Valida si el contexto técnico permite actuar y cambiar con seguridad.", outputs: ["Technical Map", "Decision Gaps", "Runbook Gate"] },
  { icon: Palette, name: "Design & Experience Readiness", href: "#solicitar-diagnostico", en: "Connects visual intent with states, behavior and implementation constraints.", es: "Conecta intención visual con estados, comportamiento y restricciones de implementación.", outputs: ["Design Handoff", "State Matrix", "Experience Gate"] },
  { icon: BarChart3, name: "Data Request Readiness", href: "#solicitar-diagnostico", en: "Aligns business question, metric, audience and decision.", es: "Alinea pregunta de negocio, métrica, audiencia y decisión.", outputs: ["Data Request Pack", "Metric Context", "Decision Brief"] },
  { icon: BriefcaseBusiness, name: "Sales-to-Delivery Understanding", href: "#solicitar-diagnostico", en: "Preserves commitments, scope and acceptance from sale to delivery.", es: "Preserva compromisos, alcance y aceptación desde ventas hasta delivery.", outputs: ["Commitment Map", "Scope Gate", "Delivery Brief"] },
  { icon: Headphones, name: "Support Signal Understanding", href: "#solicitar-diagnostico", en: "Turns customer signals into evidence ready for product decisions.", es: "Convierte señales del cliente en evidencia lista para decisiones de producto.", outputs: ["Support Signal Pack", "Evidence Map", "Impact Brief"] },
  { icon: Megaphone, name: "Marketing Understanding", href: "#solicitar-diagnostico", en: "Keeps audience, proposition, evidence and channels aligned.", es: "Mantiene alineados audiencia, propuesta, evidencia y canales.", outputs: ["Campaign Brief", "Claim Check", "Channel Handoff"] },
  { icon: Landmark, name: "Finance / Procurement Readiness", href: "#solicitar-diagnostico", en: "Clarifies evidence, thresholds, ownership and approval paths.", es: "Aclara evidencia, umbrales, ownership y rutas de aprobación.", outputs: ["Approval Pack", "Evidence Gate", "Vendor Brief"] },
  { icon: Gavel, name: "Legal / Security / Compliance Understanding", href: "#solicitar-diagnostico", en: "Translates policy intent into applicable operating rules.", es: "Traduce intención de política en reglas operativas aplicables.", outputs: ["Policy Card", "Control Map", "Applicability Gate"] },
  { icon: UserRoundSearch, name: "Talent & Staffing Understanding", href: "/app/talent-staffing", en: "Aligns role need, screening evidence and candidate handoff.", es: "Alinea necesidad del rol, evidencia de screening y handoff de candidato.", outputs: ["Role Pack", "Screening Gate", "Candidate Handoff"] },
  { icon: Settings2, name: "Knowledge Continuity", href: "/app/onboarding", en: "Preserves decisions and operating context through team change.", es: "Preserva decisiones y contexto operativo cuando cambia el equipo.", outputs: ["Continuity Map", "Decision Record", "Transfer Pack"] },
];

export function SolutionPanels() {
  const { locale, t } = useLanguage();
  return <section id="packs" className="solution-panels-section scroll-mt-24 border-y border-[var(--border)] bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="max-w-4xl"><p className="section-kicker">{t("Official understanding packs", "Packs oficiales de entendimiento")}</p><h2 className="section-display">{t("One infrastructure. Configured for the flow at risk.", "Una infraestructura. Configurada para el flujo en riesgo.")}</h2><p className="section-lead mt-6 max-w-3xl">{t("The audit recommends one pack or a combined bundle. Existing demo modules open directly; additional packs are configured through the pilot.", "La auditoría recomienda un pack o un bundle combinado. Los módulos existentes abren directo en la demo; los packs adicionales se configuran mediante el piloto.")}</p></div><div className="pack-catalog-grid mt-12">{packs.map(({ icon: Icon, name, href, en, es, outputs }, index) => <article key={name} className={`solution-panel group relative overflow-hidden rounded-[26px] border border-[var(--border)] bg-[var(--panel)] ${index < 5 ? "is-priority" : ""}`}><div className="solution-panel-number">{String(index + 1).padStart(2, "0")}</div><div className="relative flex h-full flex-col"><span className="grid size-11 place-items-center rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] text-[var(--brand-blue)]"><Icon size={19} /></span><h3>{name}</h3><p>{locale === "es" ? es : en}</p><div className="mt-6 flex flex-wrap gap-2">{outputs.map((item) => <span key={item} className="rounded-full border border-[var(--border)] bg-[var(--panel-soft)] px-3 py-1.5 text-[9px] text-[var(--subtle)]">{item}</span>)}</div><Link href={href} className="mt-auto inline-flex items-center gap-2 pt-8 text-[10px] font-semibold text-[var(--brand-blue)]">{href.startsWith("/app") ? t("Explore in enterprise demo", "Explorar en demo enterprise") : t("Configure in an audit", "Configurar en una auditoría")} <ArrowUpRight size={13} className="transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></Link></div></article>)}</div><div className="solution-bundle-note"><span>{t("Start with one pack", "Inicia con un pack")}</span><span>{t("Combine capability blocks", "Combina bloques")}</span><span>{t("Receive an audit recommendation", "Recibe recomendación")}</span><span>{t("Scale through staged bundles", "Escala por bundles")}</span></div></div></section>;
}
