"use client";

import Link from "next/link";
import { ArrowUpRight, Bot, Code2, RefreshCw } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";

const entryPoints = [
  { icon: Code2, name: "Product Delivery", en: "Product, development and QA working from the same understanding", es: "Producto, desarrollo y QA trabajando desde el mismo entendimiento", enCopy: "Turns incomplete information into stories, criteria, matrices, bugs, handoffs and critical questions.", esCopy: "Convierte información incompleta en HUs, criterios, matrices, bugs, handoffs y preguntas críticas." },
  { icon: RefreshCw, name: "Change & Handoff Understanding", en: "Keep what changes synchronized across teams", es: "Mantén sincronizado lo que cambia entre equipos", enCopy: "Identifies impact, outdated knowledge, dependencies, owners and readiness before a change creates rework.", esCopy: "Identifica impacto, conocimiento obsoleto, dependencias, responsables y readiness antes de que un cambio produzca retrabajo." },
  { icon: Bot, name: "AI Understanding", en: "Help AI better understand how your company operates", es: "Ayuda a que la IA entienda mejor cómo opera tu empresa", enCopy: "Turns processes, rules and enterprise context into understandable instructions for the AI tools the company already uses.", esCopy: "Convierte procesos, reglas y contexto empresarial en instrucciones entendibles para las herramientas de IA que la empresa ya utiliza." },
];

export function SolutionPanels() {
  const { locale, t } = useLanguage();
  return <section id="aplicaciones" className="solution-panels-section scroll-mt-24 border-y border-[var(--border)] bg-[var(--panel-soft)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="max-w-4xl"><p className="section-kicker">{t("Three starting points", "Tres puertas de entrada")}</p><h2 className="section-display">{t("Start where operational understanding is costing the most.", "Empieza donde el entendimiento operativo está costando más.")}</h2></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{entryPoints.map(({ icon: Icon, name, en, es, enCopy, esCopy }, index) => <article key={name} className="solution-panel is-priority rounded-[26px] border border-[var(--border)] bg-[var(--panel)] p-6"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl border border-[var(--border)] bg-[var(--panel-soft)] text-[var(--brand-blue)]"><Icon aria-hidden="true" size={19} /></span><span className="text-[10px] text-[var(--subtle)]">0{index + 1}</span></div><p className="mt-6 text-[10px] font-semibold uppercase tracking-[.12em] text-[var(--brand-blue)]">{name}</p><h3 className="mt-3 text-xl font-semibold leading-7 tracking-[-.03em]">{locale === "es" ? es : en}</h3><p className="mt-4 text-xs leading-6 text-[var(--muted)]">{locale === "es" ? esCopy : enCopy}</p><a href="#solicitar-auditoria" className="brand-secondary-button mt-7 self-start text-[10px]">{t("Evaluate this flow", "Evaluar este flujo")} <ArrowUpRight aria-hidden="true" size={13} /></a></article>)}</div><Link href="/app" className="brand-secondary-button mx-auto mt-8 text-xs">{t("Explore all Enterprise applications", "Explorar todas las aplicaciones Enterprise")} <ArrowUpRight aria-hidden="true" size={14} /></Link></div></section>;
}
