"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2, CircleAlert, Filter, FileOutput, Layers3 } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-provider";

const scenarios = [
  { id: "meeting", en: "Meeting → tasks", es: "Junta → tareas", inputEn: "We agreed to review the client issue, adjust the proposal and check with dev if it can ship this week.", inputEs: "Quedamos en revisar lo del cliente, ajustar la propuesta y ver con dev si se puede sacar esta semana.", gapsEn: ["No accountable owner", "Scope is undefined", "No success criteria"], gapsEs: ["No hay responsable", "El alcance no está definido", "No hay criterio de éxito"], outputEn: "Action brief by team with owners and validation questions.", outputEs: "Brief de acciones por área con responsables y preguntas para validar.", score: 28 },
  { id: "product", en: "Product → development", es: "Producto → desarrollo", inputEn: "Add social login to improve conversion.", inputEs: "Agregar login social para mejorar conversión.", gapsEn: ["Provider undefined", "Fallback rules missing", "No success metric"], gapsEs: ["Proveedor no definido", "Faltan reglas de fallback", "No hay métrica de éxito"], outputEn: "Delivery-ready story, boundaries and acceptance criteria.", outputEs: "Historia lista para delivery, límites y criterios de aceptación.", score: 42 },
  { id: "design", en: "Design → frontend", es: "Diseño → frontend", inputEn: "Final Figma screen with no interaction states.", inputEs: "Pantalla final en Figma sin estados de interacción.", gapsEn: ["Loading and error states", "Responsive behavior", "Validation rules"], gapsEs: ["Estados de carga y error", "Comportamiento responsive", "Reglas de validación"], outputEn: "Design-to-dev handoff with states and behavior checklist.", outputEs: "Handoff diseño-desarrollo con estados y checklist de comportamiento.", score: 35 },
  { id: "data", en: "Data request → BI", es: "Solicitud de datos → BI", inputEn: "I need a performance report.", inputEs: "Necesito un reporte de desempeño.", gapsEn: ["Business question missing", "Metric undefined", "Decision is unclear"], gapsEs: ["Falta la pregunta de negocio", "Métrica no definida", "Decisión poco clara"], outputEn: "Data request brief with metric, audience and decision.", outputEs: "Brief de solicitud con métrica, audiencia y decisión.", score: 31 },
  { id: "ai", en: "Company → AI", es: "Empresa → IA", inputEn: "Create an executive summary of this process.", inputEs: "Haz un resumen ejecutivo de este proceso.", gapsEn: ["Audience missing", "Format undefined", "Assumption boundaries absent"], gapsEs: ["Falta la audiencia", "Formato no definido", "Sin límites de supuestos"], outputEn: "Context Pack with intent, evidence, rules and review checkpoint.", outputEs: "Context Pack con intención, evidencia, reglas y checkpoint de revisión.", score: 37 },
];

export function TransversalDemo() {
  const { locale, t } = useLanguage(); const [activeId, setActiveId] = useState("meeting"); const active = scenarios.find((item) => item.id === activeId) ?? scenarios[0];
  return <section id="demo" className="demo-lab-section scroll-mt-24 border-y border-[var(--border)] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><div className="max-w-4xl"><p className="section-kicker">{t("Transversal product demo", "Demo transversal del producto")}</p><h2 className="section-display">{t("See what changes before information moves forward.", "Mira qué cambia antes de que la información avance.")}</h2><p className="section-lead mt-6">{t("Choose a flow. The same understanding filter adapts to the receiver, risk and operational outcome.", "Selecciona un flujo. El mismo filtro de entendimiento se adapta al receptor, riesgo y resultado operativo.")}</p></div><div className="demo-selector mt-10" role="tablist" aria-label={t("Demo flow selector", "Selector de flujo demo")}>{scenarios.map((item) => <button key={item.id} type="button" role="tab" aria-selected={item.id === activeId} onClick={() => setActiveId(item.id)} className={item.id === activeId ? "is-active" : ""}>{locale === "es" ? item.es : item.en}</button>)}</div><div className="demo-lab" key={active.id}><section><div className="demo-panel-label"><Layers3 size={13} />01 · {t("Scattered input", "Input disperso")}</div><blockquote>“{locale === "es" ? active.inputEs : active.inputEn}”</blockquote><span className="demo-source-tag">{locale === "es" ? active.es : active.en}</span></section><div className="demo-filter-column"><div className="demo-filter-icon"><Filter size={18} /></div><strong>Virro Understanding Filter</strong><ul>{(locale === "es" ? active.gapsEs : active.gapsEn).map((gap) => <li key={gap}><CircleAlert size={12} />{gap}</li>)}</ul><div className="demo-readiness"><span>Readiness</span><b>{active.score}/100</b><i><em style={{ width: `${active.score}%` }} /></i></div></div><section><div className="demo-panel-label"><FileOutput size={13} />03 · {t("Ready-to-advance output", "Entregable listo para avanzar")}</div><p className="demo-output-copy">{locale === "es" ? active.outputEs : active.outputEn}</p><div className="demo-output-list"><span><CheckCircle2 size={12} />{t("Critical questions to validate", "Preguntas críticas para validar")}</span><span><CheckCircle2 size={12} />{t("Receiver checklist", "Checklist del receptor")}</span><span><CheckCircle2 size={12} />{t("Recommended next action", "Siguiente acción recomendada")}</span></div><a href="#solicitar-diagnostico">{t("Diagnose this kind of flow", "Diagnosticar este tipo de flujo")} <ArrowRight size={12} /></a></section></div></div></section>;
}
