"use client";

import { ArrowRight, CheckCircle2, History, Network, Radar, RefreshCw } from "lucide-react";
import Link from "next/link";
import { useLanguage } from "@/components/i18n/language-provider";
import { RevealOnScroll } from "@/components/landing/motion/motion-primitives";

export function VirroCoreSection() {
  const { t } = useLanguage();
  const flow = [t("Source", "Fuente"), t("Transfer point", "Punto de transferencia"), t("Receiver", "Receptor"), t("Expected action", "Acción esperada"), t("Required evidence", "Evidencia necesaria"), "Readiness", t("Change", "Cambio"), "Outcome"];
  const capabilities = [
    ["Readiness", t("Checks whether the available information is sufficient for the next receiver to act.", "Evalúa si la información disponible es suficiente para que el siguiente responsable actúe."), Radar],
    ["Change Integrity", t("Detects when reality changes but dependent information remains on a previous version.", "Detecta cuando la realidad cambia, pero la información dependiente conserva una versión anterior."), RefreshCw],
    ["Handoff Integrity", t("Reviews responsibility, evidence and the expected action at each transfer.", "Revisa responsabilidad, evidencia y acción esperada en cada transferencia."), Network],
    ["Knowledge Continuity", t("Makes critical context reusable beyond one person, meeting or provider.", "Hace reutilizable el contexto crítico más allá de una persona, reunión o proveedor."), History],
  ] as const;
  return <section id="virro-core" className="virro-core-section scroll-mt-24 px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1380px]"><RevealOnScroll><p className="section-kicker">Virro Core</p><h2 className="section-display max-w-5xl">{t("Understand the transfer before judging the result.", "Entiende la transferencia antes de evaluar el resultado.")}</h2><p className="section-lead mt-6 max-w-4xl">{t("Virro analyzes the points where work is created, changes or passes to the next owner, and detects when information still does not enable sufficiently clear execution.", "Virro analiza los puntos donde el trabajo se crea, cambia o pasa al siguiente responsable, y detecta cuándo la información todavía no permite ejecutar con suficiente claridad.")}</p></RevealOnScroll><ol className="mt-12 flex flex-wrap items-center gap-2" aria-label={t("Virro Core operating sequence", "Secuencia operativa de Virro Core")}>{flow.map((item, index) => <li key={item} className="flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--panel)] px-3 py-2 text-[9px] font-semibold"><span className="text-[var(--brand-blue)]">{index + 1}</span>{item}{index < flow.length - 1 && <ArrowRight aria-hidden="true" size={11} />}</li>)}</ol><div className="mt-10 grid gap-4 md:grid-cols-2">{capabilities.map(([title, copy, Icon]) => <article key={title} className="rounded-[24px] border border-[var(--border)] bg-[var(--panel)] p-6"><Icon aria-hidden="true" className="text-[var(--brand-blue)]" size={19} /><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-xs leading-6 text-[var(--muted)]">{copy}</p></article>)}</div><p className="mt-8 flex items-start gap-2 text-[10px] leading-5 text-[var(--subtle)]"><CheckCircle2 aria-hidden="true" size={13} className="mt-0.5 shrink-0 text-teal-300" />{t("Virro also recognizes when there is not enough evidence to issue a reliable verdict.", "Virro también reconoce cuándo no existe evidencia suficiente para emitir un veredicto confiable.")}</p><Link href="/app" className="brand-secondary-button mt-7 text-sm">{t("Explore enterprise demo", "Explorar demo enterprise")} <ArrowRight aria-hidden="true" size={14} /></Link></div></section>;
}
